ALTER TABLE game_room
    ADD COLUMN IF NOT EXISTS next_question_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS paused_by_profile_id BIGINT REFERENCES profile(id),
    ADD COLUMN IF NOT EXISTS pause_started_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS pause_until_at TIMESTAMPTZ;

ALTER TABLE game_room_member
    ADD COLUMN IF NOT EXISTS pause_used BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS force_resume_requested BOOLEAN NOT NULL DEFAULT FALSE;
