UPDATE game_question AS q
SET question_text_ru = t.question_text_ru,
    question_text_en = t.question_text_en
FROM (
    VALUES
        ('В каком году человек впервые высадился на Луне?', 'В каком году человек впервые высадился на Луне?', 'In what year did humans first land on the Moon?'),
        ('Сколько фильмов входит в основную серию о Гарри Поттере?', 'Сколько фильмов входит в основную серию о Гарри Поттере?', 'How many films are in the main Harry Potter series?'),
        ('В каком году вышла полная версия Minecraft 1.0?', 'В каком году вышла полная версия Minecraft 1.0?', 'In what year was the full version of Minecraft 1.0 released?'),
        ('Сколько Камней Бесконечности в киновселенной Marvel?', 'Сколько Камней Бесконечности в киновселенной Marvel?', 'How many Infinity Stones are there in the Marvel Cinematic Universe?'),
        ('Сколько химических элементов официально входит в периодическую таблицу?', 'Сколько химических элементов официально входит в периодическую таблицу?', 'How many chemical elements are officially in the periodic table?'),
        ('В каком году затонул Титаник?', 'В каком году затонул Титаник?', 'In what year did the Titanic sink?'),
        ('Сколько эпизодов входит в сагу Скайуокеров?', 'Сколько эпизодов входит в сагу Скайуокеров?', 'How many episodes are in the Skywalker saga?'),
        ('В каком году Apple представила первый iPhone?', 'В каком году Apple представила первый iPhone?', 'In what year did Apple introduce the first iPhone?'),
        ('Сколько колец на олимпийском флаге?', 'Сколько колец на олимпийском флаге?', 'How many rings are on the Olympic flag?'),
        ('В каком году впервые опубликован роман Хоббит?', 'В каком году впервые опубликован роман Хоббит?', 'In what year was the novel The Hobbit first published?'),
        ('Сколько клеток на шахматной доске?', 'Сколько клеток на шахматной доске?', 'How many squares are there on a chessboard?'),
        ('Сколько покемонов было в первом поколении?', 'Сколько покемонов было в первом поколении?', 'How many Pokemon were in the first generation?'),
        ('В каком году началась Вторая мировая война?', 'В каком году началась Вторая мировая война?', 'In what year did World War II begin?'),
        ('В каком году Юрий Гагарин совершил первый космический полёт?', 'В каком году Юрий Гагарин совершил первый космический полёт?', 'In what year did Yuri Gagarin make the first human spaceflight?'),
        ('В каком году Колумб достиг берегов Америки?', 'В каком году Колумб достиг берегов Америки?', 'In what year did Columbus reach the shores of the Americas?'),
        ('В каком году произошла битва при Ватерлоо?', 'В каком году произошла битва при Ватерлоо?', 'In what year did the Battle of Waterloo take place?'),
        ('Сколько лет фактически длилась Столетняя война?', 'Сколько лет фактически длилась Столетняя война?', 'How many years did the Hundred Years War actually last?'),
        ('В каком году была принята Конституция США?', 'В каком году была принята Конституция США?', 'In what year was the United States Constitution adopted?'),
        ('В каком году прекратил существование СССР?', 'В каком году прекратил существование СССР?', 'In what year did the USSR cease to exist?'),
        ('В каком году Пётр I основал Санкт-Петербург?', 'В каком году Пётр I основал Санкт-Петербург?', 'In what year did Peter the Great found Saint Petersburg?'),
        ('Скорость света в вакууме (км/с, округлённо)?', 'Скорость света в вакууме (км/с, округлённо)?', 'What is the speed of light in a vacuum, rounded, in km/s?'),
        ('Сколько планет в Солнечной системе?', 'Сколько планет в Солнечной системе?', 'How many planets are there in the Solar System?'),
        ('Атомный номер водорода в таблице Менделеева?', 'Атомный номер водорода в таблице Менделеева?', 'What is the atomic number of hydrogen in the periodic table?'),
        ('В каком году был открыт пенициллин?', 'В каком году был открыт пенициллин?', 'In what year was penicillin discovered?'),
        ('Температура кипения воды при нормальном давлении (°C)?', 'Температура кипения воды при нормальном давлении (°C)?', 'What is the boiling point of water at normal pressure, in °C?'),
        ('Сколько костей в скелете взрослого человека?', 'Сколько костей в скелете взрослого человека?', 'How many bones are in an adult human skeleton?'),
        ('Молярная масса углекислого газа (г/моль)?', 'Молярная масса углекислого газа (г/моль)?', 'What is the molar mass of carbon dioxide, in g/mol?'),
        ('Средний диаметр Земли (км)?', 'Средний диаметр Земли (км)?', 'What is the average diameter of Earth, in km?'),
        ('Сколько простых чисел от 1 до 50 включительно?', 'Сколько простых чисел от 1 до 50 включительно?', 'How many prime numbers are there from 1 to 50 inclusive?'),
        ('Квадратный корень из 144?', 'Квадратный корень из 144?', 'What is the square root of 144?'),
        ('Сколько нулей содержит число один миллиард?', 'Сколько нулей содержит число один миллиард?', 'How many zeros are in the number one billion?'),
        ('Сколько градусов в полном круге?', 'Сколько градусов в полном круге?', 'How many degrees are in a full circle?'),
        ('Какое седьмое число в последовательности Фибоначчи?', 'Какое седьмое число в последовательности Фибоначчи?', 'What is the seventh number in the Fibonacci sequence?'),
        ('Длина реки Нил (км)?', 'Длина реки Нил (км)?', 'What is the length of the Nile River, in km?'),
        ('В каком году был открыт Суэцкий канал?', 'В каком году был открыт Суэцкий канал?', 'In what year was the Suez Canal opened?'),
        ('Высота горы Эверест над уровнем моря (метров)?', 'Высота горы Эверест над уровнем моря (метров)?', 'What is the height of Mount Everest above sea level, in meters?'),
        ('Сколько официально признанных стран в Африке?', 'Сколько официально признанных стран в Африке?', 'How many officially recognized countries are there in Africa?'),
        ('Площадь России в миллионах кв. км (округлённо)?', 'Площадь России в миллионах кв. км (округлённо)?', 'What is the area of Russia in million square kilometers, rounded?'),
        ('В каком году официально распались The Beatles?', 'В каком году официально распались The Beatles?', 'In what year did The Beatles officially break up?'),
        ('Сколько струн у классической гитары?', 'Сколько струн у классической гитары?', 'How many strings does a classical guitar have?'),
        ('В каком году написана Лунная соната Бетховена?', 'В каком году написана Лунная соната Бетховена?', 'In what year was Moonlight Sonata by Beethoven written?'),
        ('Сколько нот в одной октаве?', 'Сколько нот в одной октаве?', 'How many notes are in one octave?'),
        ('Сколько игроков от команды на площадке в баскетболе?', 'Сколько игроков от команды на площадке в баскетболе?', 'How many players from one team are on the court in basketball?'),
        ('В каком году основан ФК Реал Мадрид?', 'В каком году основан ФК Реал Мадрид?', 'In what year was Real Madrid CF founded?'),
        ('В каком году прошли первые современные Олимпийские игры?', 'В каком году прошли первые современные Олимпийские игры?', 'In what year were the first modern Olympic Games held?'),
        ('Сколько геймов нужно выиграть для победы в сете (минимум)?', 'Сколько геймов нужно выиграть для победы в сете (минимум)?', 'How many games must be won to win a tennis set at minimum?'),
        ('Сколько минут длится стандартный футбольный матч?', 'Сколько минут длится стандартный футбольный матч?', 'How many minutes does a standard football match last?'),
        ('Длина дистанции марафона (км, округлённо)?', 'Длина дистанции марафона (км, округлённо)?', 'What is the marathon distance, rounded, in km?'),
        ('В каком году создан язык программирования Python?', 'В каком году создан язык программирования Python?', 'In what year was the Python programming language created?'),
        ('Сколько бит в одном байте?', 'Сколько бит в одном байте?', 'How many bits are in one byte?'),
        ('В каком году выпущен первый микропроцессор Intel 4004?', 'В каком году выпущен первый микропроцессор Intel 4004?', 'In what year was the first Intel 4004 microprocessor released?'),
        ('Количество пикселей по горизонтали в Full HD?', 'Количество пикселей по горизонтали в Full HD?', 'How many horizontal pixels are there in Full HD?')
) AS t(question_text, question_text_ru, question_text_en)
WHERE q.question_text = t.question_text;

ALTER TABLE game_question
    DROP COLUMN IF EXISTS answer_unit,
    DROP COLUMN IF EXISTS answer_unit_ru,
    DROP COLUMN IF EXISTS answer_unit_en;
