// Code generated by MockGen. DO NOT EDIT.
// Source: services/community/internal/handler/http/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/go-park-mail-ru/2026_1_ARIS/services/community/internal/model"
	usecase "github.com/go-park-mail-ru/2026_1_ARIS/services/community/internal/usecase"
	gomock "github.com/golang/mock/gomock"
)

// MockCommunityService is a mock of CommunityService interface.
type MockCommunityService struct {
	ctrl     *gomock.Controller
	recorder *MockCommunityServiceMockRecorder
}

// MockCommunityServiceMockRecorder is the mock recorder for MockCommunityService.
type MockCommunityServiceMockRecorder struct {
	mock *MockCommunityService
}

// NewMockCommunityService creates a new mock instance.
func NewMockCommunityService(ctrl *gomock.Controller) *MockCommunityService {
	mock := &MockCommunityService{ctrl: ctrl}
	mock.recorder = &MockCommunityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommunityService) EXPECT() *MockCommunityServiceMockRecorder {
	return m.recorder
}

// ChangeMemberRole mocks base method.
func (m *MockCommunityService) ChangeMemberRole(arg0 context.Context, arg1, arg2, arg3 int64, arg4 model.CommunityMemberRole) (*usecase.MemberDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeMemberRole", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*usecase.MemberDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeMemberRole indicates an expected call of ChangeMemberRole.
func (mr *MockCommunityServiceMockRecorder) ChangeMemberRole(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeMemberRole", reflect.TypeOf((*MockCommunityService)(nil).ChangeMemberRole), arg0, arg1, arg2, arg3, arg4)
}

// CheckExists mocks base method.
func (m *MockCommunityService) CheckExists(arg0 context.Context, arg1 usecase.CheckExistsInput) (*usecase.CheckExistsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExists", arg0, arg1)
	ret0, _ := ret[0].(*usecase.CheckExistsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExists indicates an expected call of CheckExists.
func (mr *MockCommunityServiceMockRecorder) CheckExists(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExists", reflect.TypeOf((*MockCommunityService)(nil).CheckExists), arg0, arg1)
}

// Create mocks base method.
func (m *MockCommunityService) Create(arg0 context.Context, arg1 int64, arg2 usecase.CreateInput) (*usecase.Details, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*usecase.Details)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommunityServiceMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommunityService)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockCommunityService) Delete(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommunityServiceMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommunityService)(nil).Delete), arg0, arg1, arg2)
}

// GetDetails mocks base method.
func (m *MockCommunityService) GetDetails(arg0 context.Context, arg1 int64, arg2 *int64) (*usecase.Details, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetails", arg0, arg1, arg2)
	ret0, _ := ret[0].(*usecase.Details)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetails indicates an expected call of GetDetails.
func (mr *MockCommunityServiceMockRecorder) GetDetails(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetails", reflect.TypeOf((*MockCommunityService)(nil).GetDetails), arg0, arg1, arg2)
}

// GetDetailsByProfileID mocks base method.
func (m *MockCommunityService) GetDetailsByProfileID(arg0 context.Context, arg1 int64, arg2 *int64) (*usecase.Details, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetailsByProfileID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*usecase.Details)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetailsByProfileID indicates an expected call of GetDetailsByProfileID.
func (mr *MockCommunityServiceMockRecorder) GetDetailsByProfileID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetailsByProfileID", reflect.TypeOf((*MockCommunityService)(nil).GetDetailsByProfileID), arg0, arg1, arg2)
}

// Join mocks base method.
func (m *MockCommunityService) Join(arg0 context.Context, arg1, arg2 int64) (*usecase.MemberDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", arg0, arg1, arg2)
	ret0, _ := ret[0].(*usecase.MemberDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Join indicates an expected call of Join.
func (mr *MockCommunityServiceMockRecorder) Join(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockCommunityService)(nil).Join), arg0, arg1, arg2)
}

// Leave mocks base method.
func (m *MockCommunityService) Leave(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leave", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Leave indicates an expected call of Leave.
func (mr *MockCommunityServiceMockRecorder) Leave(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leave", reflect.TypeOf((*MockCommunityService)(nil).Leave), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockCommunityService) List(arg0 context.Context, arg1, arg2 int, arg3 *int64) ([]usecase.Details, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]usecase.Details)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCommunityServiceMockRecorder) List(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCommunityService)(nil).List), arg0, arg1, arg2, arg3)
}

// ListMembers mocks base method.
func (m *MockCommunityService) ListMembers(arg0 context.Context, arg1 int64, arg2 *int64, arg3 bool) ([]usecase.MemberDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]usecase.MemberDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockCommunityServiceMockRecorder) ListMembers(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockCommunityService)(nil).ListMembers), arg0, arg1, arg2, arg3)
}

// RemoveMember mocks base method.
func (m *MockCommunityService) RemoveMember(arg0 context.Context, arg1, arg2, arg3 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockCommunityServiceMockRecorder) RemoveMember(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockCommunityService)(nil).RemoveMember), arg0, arg1, arg2, arg3)
}

// Update mocks base method.
func (m *MockCommunityService) Update(arg0 context.Context, arg1, arg2 int64, arg3 usecase.UpdateInput) (*usecase.Details, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*usecase.Details)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCommunityServiceMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommunityService)(nil).Update), arg0, arg1, arg2, arg3)
}
