// Code generated by MockGen. DO NOT EDIT.
// Source: services/game/internal/handler/http/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/go-park-mail-ru/2026_1_ARIS/services/game/internal/usecase"
	gomock "github.com/golang/mock/gomock"
)

// MockGameService is a mock of GameService interface.
type MockGameService struct {
	ctrl     *gomock.Controller
	recorder *MockGameServiceMockRecorder
}

// MockGameServiceMockRecorder is the mock recorder for MockGameService.
type MockGameServiceMockRecorder struct {
	mock *MockGameService
}

// NewMockGameService creates a new mock instance.
func NewMockGameService(ctrl *gomock.Controller) *MockGameService {
	mock := &MockGameService{ctrl: ctrl}
	mock.recorder = &MockGameServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameService) EXPECT() *MockGameServiceMockRecorder {
	return m.recorder
}

// AssignAdmin mocks base method.
func (m *MockGameService) AssignAdmin(arg0 context.Context, arg1, arg2, arg3 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignAdmin", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignAdmin indicates an expected call of AssignAdmin.
func (mr *MockGameServiceMockRecorder) AssignAdmin(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignAdmin", reflect.TypeOf((*MockGameService)(nil).AssignAdmin), arg0, arg1, arg2, arg3)
}

// CreateQuestion mocks base method.
func (m *MockGameService) CreateQuestion(arg0 context.Context, arg1 int64, arg2 usecase.QuestionInput) (usecase.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuestion", arg0, arg1, arg2)
	ret0, _ := ret[0].(usecase.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuestion indicates an expected call of CreateQuestion.
func (mr *MockGameServiceMockRecorder) CreateQuestion(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuestion", reflect.TypeOf((*MockGameService)(nil).CreateQuestion), arg0, arg1, arg2)
}

// CreateRoom mocks base method.
func (m *MockGameService) CreateRoom(arg0 context.Context, arg1 int64, arg2 usecase.CreateRoomInput) (usecase.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", arg0, arg1, arg2)
	ret0, _ := ret[0].(usecase.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockGameServiceMockRecorder) CreateRoom(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockGameService)(nil).CreateRoom), arg0, arg1, arg2)
}

// DeleteQuestion mocks base method.
func (m *MockGameService) DeleteQuestion(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuestion", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuestion indicates an expected call of DeleteQuestion.
func (mr *MockGameServiceMockRecorder) DeleteQuestion(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuestion", reflect.TypeOf((*MockGameService)(nil).DeleteQuestion), arg0, arg1, arg2)
}

// DisbandRoom mocks base method.
func (m *MockGameService) DisbandRoom(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisbandRoom", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisbandRoom indicates an expected call of DisbandRoom.
func (mr *MockGameServiceMockRecorder) DisbandRoom(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisbandRoom", reflect.TypeOf((*MockGameService)(nil).DisbandRoom), arg0, arg1, arg2)
}

// ForceResumeRoom mocks base method.
func (m *MockGameService) ForceResumeRoom(arg0 context.Context, arg1, arg2 int64) (usecase.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceResumeRoom", arg0, arg1, arg2)
	ret0, _ := ret[0].(usecase.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForceResumeRoom indicates an expected call of ForceResumeRoom.
func (mr *MockGameServiceMockRecorder) ForceResumeRoom(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceResumeRoom", reflect.TypeOf((*MockGameService)(nil).ForceResumeRoom), arg0, arg1, arg2)
}

// GetRoom mocks base method.
func (m *MockGameService) GetRoom(arg0 context.Context, arg1, arg2 int64) (usecase.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", arg0, arg1, arg2)
	ret0, _ := ret[0].(usecase.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockGameServiceMockRecorder) GetRoom(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockGameService)(nil).GetRoom), arg0, arg1, arg2)
}

// History mocks base method.
func (m *MockGameService) History(arg0 context.Context, arg1 int64, arg2, arg3 int) ([]usecase.HistoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]usecase.HistoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockGameServiceMockRecorder) History(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockGameService)(nil).History), arg0, arg1, arg2, arg3)
}

// JoinRoom mocks base method.
func (m *MockGameService) JoinRoom(arg0 context.Context, arg1 int64, arg2, arg3, arg4 string) (usecase.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinRoom", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(usecase.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinRoom indicates an expected call of JoinRoom.
func (mr *MockGameServiceMockRecorder) JoinRoom(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinRoom", reflect.TypeOf((*MockGameService)(nil).JoinRoom), arg0, arg1, arg2, arg3, arg4)
}

// KickPlayer mocks base method.
func (m *MockGameService) KickPlayer(arg0 context.Context, arg1, arg2, arg3 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KickPlayer", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// KickPlayer indicates an expected call of KickPlayer.
func (mr *MockGameServiceMockRecorder) KickPlayer(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KickPlayer", reflect.TypeOf((*MockGameService)(nil).KickPlayer), arg0, arg1, arg2, arg3)
}

// Leaderboard mocks base method.
func (m *MockGameService) Leaderboard(arg0 context.Context, arg1 string, arg2, arg3 int) (usecase.Leaderboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leaderboard", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(usecase.Leaderboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Leaderboard indicates an expected call of Leaderboard.
func (mr *MockGameServiceMockRecorder) Leaderboard(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leaderboard", reflect.TypeOf((*MockGameService)(nil).Leaderboard), arg0, arg1, arg2, arg3)
}

// LeaveRoom mocks base method.
func (m *MockGameService) LeaveRoom(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveRoom", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveRoom indicates an expected call of LeaveRoom.
func (mr *MockGameServiceMockRecorder) LeaveRoom(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveRoom", reflect.TypeOf((*MockGameService)(nil).LeaveRoom), arg0, arg1, arg2)
}

// LeaveWaitingRoomOnDisconnect mocks base method.
func (m *MockGameService) LeaveWaitingRoomOnDisconnect(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveWaitingRoomOnDisconnect", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveWaitingRoomOnDisconnect indicates an expected call of LeaveWaitingRoomOnDisconnect.
func (mr *MockGameServiceMockRecorder) LeaveWaitingRoomOnDisconnect(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveWaitingRoomOnDisconnect", reflect.TypeOf((*MockGameService)(nil).LeaveWaitingRoomOnDisconnect), arg0, arg1, arg2)
}

// ListQuestions mocks base method.
func (m *MockGameService) ListQuestions(arg0 context.Context, arg1 string, arg2 bool, arg3, arg4 int) ([]usecase.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQuestions", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]usecase.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQuestions indicates an expected call of ListQuestions.
func (mr *MockGameServiceMockRecorder) ListQuestions(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQuestions", reflect.TypeOf((*MockGameService)(nil).ListQuestions), arg0, arg1, arg2, arg3, arg4)
}

// ListRoomMessages mocks base method.
func (m *MockGameService) ListRoomMessages(arg0 context.Context, arg1, arg2 int64, arg3, arg4 int) ([]usecase.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomMessages", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]usecase.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomMessages indicates an expected call of ListRoomMessages.
func (mr *MockGameServiceMockRecorder) ListRoomMessages(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomMessages", reflect.TypeOf((*MockGameService)(nil).ListRoomMessages), arg0, arg1, arg2, arg3, arg4)
}

// ListRooms mocks base method.
func (m *MockGameService) ListRooms(arg0 context.Context, arg1 int64, arg2, arg3 int) ([]usecase.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]usecase.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockGameServiceMockRecorder) ListRooms(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockGameService)(nil).ListRooms), arg0, arg1, arg2, arg3)
}

// PauseRoom mocks base method.
func (m *MockGameService) PauseRoom(arg0 context.Context, arg1, arg2 int64) (usecase.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseRoom", arg0, arg1, arg2)
	ret0, _ := ret[0].(usecase.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PauseRoom indicates an expected call of PauseRoom.
func (mr *MockGameServiceMockRecorder) PauseRoom(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseRoom", reflect.TypeOf((*MockGameService)(nil).PauseRoom), arg0, arg1, arg2)
}

// SendRoomMessage mocks base method.
func (m *MockGameService) SendRoomMessage(arg0 context.Context, arg1, arg2 int64, arg3 string) (usecase.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRoomMessage", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(usecase.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendRoomMessage indicates an expected call of SendRoomMessage.
func (mr *MockGameServiceMockRecorder) SendRoomMessage(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRoomMessage", reflect.TypeOf((*MockGameService)(nil).SendRoomMessage), arg0, arg1, arg2, arg3)
}

// SetNotifier mocks base method.
func (m *MockGameService) SetNotifier(arg0 usecase.Notifier) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNotifier", arg0)
}

// SetNotifier indicates an expected call of SetNotifier.
func (mr *MockGameServiceMockRecorder) SetNotifier(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNotifier", reflect.TypeOf((*MockGameService)(nil).SetNotifier), arg0)
}

// SetReady mocks base method.
func (m *MockGameService) SetReady(arg0 context.Context, arg1, arg2 int64, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReady", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReady indicates an expected call of SetReady.
func (mr *MockGameServiceMockRecorder) SetReady(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReady", reflect.TypeOf((*MockGameService)(nil).SetReady), arg0, arg1, arg2, arg3)
}

// SetReplayReady mocks base method.
func (m *MockGameService) SetReplayReady(arg0 context.Context, arg1, arg2 int64, arg3 bool) (usecase.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReplayReady", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(usecase.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetReplayReady indicates an expected call of SetReplayReady.
func (mr *MockGameServiceMockRecorder) SetReplayReady(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReplayReady", reflect.TypeOf((*MockGameService)(nil).SetReplayReady), arg0, arg1, arg2, arg3)
}

// StartRoom mocks base method.
func (m *MockGameService) StartRoom(arg0 context.Context, arg1, arg2 int64) (usecase.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartRoom", arg0, arg1, arg2)
	ret0, _ := ret[0].(usecase.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartRoom indicates an expected call of StartRoom.
func (mr *MockGameServiceMockRecorder) StartRoom(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRoom", reflect.TypeOf((*MockGameService)(nil).StartRoom), arg0, arg1, arg2)
}

// Stats mocks base method.
func (m *MockGameService) Stats(arg0 context.Context, arg1 int64) (usecase.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", arg0, arg1)
	ret0, _ := ret[0].(usecase.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockGameServiceMockRecorder) Stats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockGameService)(nil).Stats), arg0, arg1)
}

// SubmitAnswer mocks base method.
func (m *MockGameService) SubmitAnswer(arg0 context.Context, arg1, arg2 int64, arg3 float64) (usecase.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitAnswer", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(usecase.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitAnswer indicates an expected call of SubmitAnswer.
func (mr *MockGameServiceMockRecorder) SubmitAnswer(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitAnswer", reflect.TypeOf((*MockGameService)(nil).SubmitAnswer), arg0, arg1, arg2, arg3)
}

// TouchWaitingRoomMember mocks base method.
func (m *MockGameService) TouchWaitingRoomMember(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchWaitingRoomMember", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchWaitingRoomMember indicates an expected call of TouchWaitingRoomMember.
func (mr *MockGameServiceMockRecorder) TouchWaitingRoomMember(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchWaitingRoomMember", reflect.TypeOf((*MockGameService)(nil).TouchWaitingRoomMember), arg0, arg1, arg2)
}

// UpdateQuestion mocks base method.
func (m *MockGameService) UpdateQuestion(arg0 context.Context, arg1, arg2 int64, arg3 usecase.QuestionInput) (usecase.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestion", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(usecase.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuestion indicates an expected call of UpdateQuestion.
func (mr *MockGameServiceMockRecorder) UpdateQuestion(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestion", reflect.TypeOf((*MockGameService)(nil).UpdateQuestion), arg0, arg1, arg2, arg3)
}

// UpdateRoomPassword mocks base method.
func (m *MockGameService) UpdateRoomPassword(arg0 context.Context, arg1, arg2 int64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoomPassword", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoomPassword indicates an expected call of UpdateRoomPassword.
func (mr *MockGameServiceMockRecorder) UpdateRoomPassword(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoomPassword", reflect.TypeOf((*MockGameService)(nil).UpdateRoomPassword), arg0, arg1, arg2, arg3)
}

// UpdateRoomRanked mocks base method.
func (m *MockGameService) UpdateRoomRanked(arg0 context.Context, arg1, arg2 int64, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoomRanked", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoomRanked indicates an expected call of UpdateRoomRanked.
func (mr *MockGameServiceMockRecorder) UpdateRoomRanked(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoomRanked", reflect.TypeOf((*MockGameService)(nil).UpdateRoomRanked), arg0, arg1, arg2, arg3)
}

// UpdateRoomTitle mocks base method.
func (m *MockGameService) UpdateRoomTitle(arg0 context.Context, arg1, arg2 int64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoomTitle", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoomTitle indicates an expected call of UpdateRoomTitle.
func (mr *MockGameServiceMockRecorder) UpdateRoomTitle(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoomTitle", reflect.TypeOf((*MockGameService)(nil).UpdateRoomTitle), arg0, arg1, arg2, arg3)
}
