// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/community/community.proto

package communitypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   int64                  `protobuf:"varint,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityRequest) Reset() {
	*x = GetCommunityRequest{}
	mi := &file_proto_community_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityRequest) ProtoMessage() {}

func (x *GetCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityRequest.ProtoReflect.Descriptor instead.
func (*GetCommunityRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_community_proto_rawDescGZIP(), []int{0}
}

func (x *GetCommunityRequest) GetCommunityId() int64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

type GetCommunityByProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int64                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityByProfileRequest) Reset() {
	*x = GetCommunityByProfileRequest{}
	mi := &file_proto_community_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityByProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityByProfileRequest) ProtoMessage() {}

func (x *GetCommunityByProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityByProfileRequest.ProtoReflect.Descriptor instead.
func (*GetCommunityByProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_community_proto_rawDescGZIP(), []int{1}
}

func (x *GetCommunityByProfileRequest) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type CommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   int64                  `protobuf:"varint,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Bio           *string                `protobuf:"bytes,4,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	ProfileId     int64                  `protobuf:"varint,6,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Username      string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	CoverMediaId  *int64                 `protobuf:"varint,8,opt,name=cover_media_id,json=coverMediaId,proto3,oneof" json:"cover_media_id,omitempty"`
	AvatarId      *int64                 `protobuf:"varint,9,opt,name=avatar_id,json=avatarId,proto3,oneof" json:"avatar_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityResponse) Reset() {
	*x = CommunityResponse{}
	mi := &file_proto_community_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityResponse) ProtoMessage() {}

func (x *CommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityResponse.ProtoReflect.Descriptor instead.
func (*CommunityResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_community_proto_rawDescGZIP(), []int{2}
}

func (x *CommunityResponse) GetCommunityId() int64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *CommunityResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CommunityResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CommunityResponse) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *CommunityResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CommunityResponse) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *CommunityResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CommunityResponse) GetCoverMediaId() int64 {
	if x != nil && x.CoverMediaId != nil {
		return *x.CoverMediaId
	}
	return 0
}

func (x *CommunityResponse) GetAvatarId() int64 {
	if x != nil && x.AvatarId != nil {
		return *x.AvatarId
	}
	return 0
}

func (x *CommunityResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CommunityResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CommunityResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   int64                  `protobuf:"varint,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	ProfileId     int64                  `protobuf:"varint,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRequest) Reset() {
	*x = GetMemberRequest{}
	mi := &file_proto_community_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRequest) ProtoMessage() {}

func (x *GetMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_community_proto_rawDescGZIP(), []int{3}
}

func (x *GetMemberRequest) GetCommunityId() int64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *GetMemberRequest) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type MemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	CommunityId   int64                  `protobuf:"varint,2,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	ProfileId     int64                  `protobuf:"varint,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberResponse) Reset() {
	*x = MemberResponse{}
	mi := &file_proto_community_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberResponse) ProtoMessage() {}

func (x *MemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberResponse.ProtoReflect.Descriptor instead.
func (*MemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_community_proto_rawDescGZIP(), []int{4}
}

func (x *MemberResponse) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *MemberResponse) GetCommunityId() int64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *MemberResponse) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *MemberResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MemberResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CanPostByProfileRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CommunityProfileId int64                  `protobuf:"varint,1,opt,name=community_profile_id,json=communityProfileId,proto3" json:"community_profile_id,omitempty"`
	ActorProfileId     int64                  `protobuf:"varint,2,opt,name=actor_profile_id,json=actorProfileId,proto3" json:"actor_profile_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CanPostByProfileRequest) Reset() {
	*x = CanPostByProfileRequest{}
	mi := &file_proto_community_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanPostByProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanPostByProfileRequest) ProtoMessage() {}

func (x *CanPostByProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanPostByProfileRequest.ProtoReflect.Descriptor instead.
func (*CanPostByProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_community_proto_rawDescGZIP(), []int{5}
}

func (x *CanPostByProfileRequest) GetCommunityProfileId() int64 {
	if x != nil {
		return x.CommunityProfileId
	}
	return 0
}

func (x *CanPostByProfileRequest) GetActorProfileId() int64 {
	if x != nil {
		return x.ActorProfileId
	}
	return 0
}

type CanPostAsMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommunityId    int64                  `protobuf:"varint,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	ActorProfileId int64                  `protobuf:"varint,2,opt,name=actor_profile_id,json=actorProfileId,proto3" json:"actor_profile_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CanPostAsMemberRequest) Reset() {
	*x = CanPostAsMemberRequest{}
	mi := &file_proto_community_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanPostAsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanPostAsMemberRequest) ProtoMessage() {}

func (x *CanPostAsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanPostAsMemberRequest.ProtoReflect.Descriptor instead.
func (*CanPostAsMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_community_proto_rawDescGZIP(), []int{6}
}

func (x *CanPostAsMemberRequest) GetCommunityId() int64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *CanPostAsMemberRequest) GetActorProfileId() int64 {
	if x != nil {
		return x.ActorProfileId
	}
	return 0
}

type CanPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanPostResponse) Reset() {
	*x = CanPostResponse{}
	mi := &file_proto_community_community_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanPostResponse) ProtoMessage() {}

func (x *CanPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_community_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanPostResponse.ProtoReflect.Descriptor instead.
func (*CanPostResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_community_proto_rawDescGZIP(), []int{7}
}

func (x *CanPostResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SearchCommunitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCommunitiesRequest) Reset() {
	*x = SearchCommunitiesRequest{}
	mi := &file_proto_community_community_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCommunitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCommunitiesRequest) ProtoMessage() {}

func (x *SearchCommunitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_community_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCommunitiesRequest.ProtoReflect.Descriptor instead.
func (*SearchCommunitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_community_proto_rawDescGZIP(), []int{8}
}

func (x *SearchCommunitiesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchCommunitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchCommunityItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   int64                  `protobuf:"varint,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	ProfileId     int64                  `protobuf:"varint,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Bio           *string                `protobuf:"bytes,5,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	AvatarId      *int64                 `protobuf:"varint,7,opt,name=avatar_id,json=avatarId,proto3,oneof" json:"avatar_id,omitempty"`
	CoverMediaId  *int64                 `protobuf:"varint,8,opt,name=cover_media_id,json=coverMediaId,proto3,oneof" json:"cover_media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCommunityItem) Reset() {
	*x = SearchCommunityItem{}
	mi := &file_proto_community_community_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCommunityItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCommunityItem) ProtoMessage() {}

func (x *SearchCommunityItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_community_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCommunityItem.ProtoReflect.Descriptor instead.
func (*SearchCommunityItem) Descriptor() ([]byte, []int) {
	return file_proto_community_community_proto_rawDescGZIP(), []int{9}
}

func (x *SearchCommunityItem) GetCommunityId() int64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *SearchCommunityItem) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *SearchCommunityItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SearchCommunityItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchCommunityItem) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *SearchCommunityItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SearchCommunityItem) GetAvatarId() int64 {
	if x != nil && x.AvatarId != nil {
		return *x.AvatarId
	}
	return 0
}

func (x *SearchCommunityItem) GetCoverMediaId() int64 {
	if x != nil && x.CoverMediaId != nil {
		return *x.CoverMediaId
	}
	return 0
}

type SearchCommunitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Communities   []*SearchCommunityItem `protobuf:"bytes,1,rep,name=communities,proto3" json:"communities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCommunitiesResponse) Reset() {
	*x = SearchCommunitiesResponse{}
	mi := &file_proto_community_community_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCommunitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCommunitiesResponse) ProtoMessage() {}

func (x *SearchCommunitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_community_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCommunitiesResponse.ProtoReflect.Descriptor instead.
func (*SearchCommunitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_community_proto_rawDescGZIP(), []int{10}
}

func (x *SearchCommunitiesResponse) GetCommunities() []*SearchCommunityItem {
	if x != nil {
		return x.Communities
	}
	return nil
}

var File_proto_community_community_proto protoreflect.FileDescriptor

const file_proto_community_community_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/community/community.proto\x12\x11aris.community.v1\"8\n" +
	"\x13GetCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\x03R\vcommunityId\"=\n" +
	"\x1cGetCommunityByProfileRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x03R\tprofileId\"\x95\x03\n" +
	"\x11CommunityResponse\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\x03R\vcommunityId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x15\n" +
	"\x03bio\x18\x04 \x01(\tH\x00R\x03bio\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x06 \x01(\x03R\tprofileId\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\x12)\n" +
	"\x0ecover_media_id\x18\b \x01(\x03H\x01R\fcoverMediaId\x88\x01\x01\x12 \n" +
	"\tavatar_id\x18\t \x01(\x03H\x02R\bavatarId\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAtB\x06\n" +
	"\x04_bioB\x11\n" +
	"\x0f_cover_media_idB\f\n" +
	"\n" +
	"_avatar_id\"T\n" +
	"\x10GetMemberRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\x03R\vcommunityId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\x03R\tprofileId\"\xa0\x01\n" +
	"\x0eMemberResponse\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\x12!\n" +
	"\fcommunity_id\x18\x02 \x01(\x03R\vcommunityId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\x03R\tprofileId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"u\n" +
	"\x17CanPostByProfileRequest\x120\n" +
	"\x14community_profile_id\x18\x01 \x01(\x03R\x12communityProfileId\x12(\n" +
	"\x10actor_profile_id\x18\x02 \x01(\x03R\x0eactorProfileId\"e\n" +
	"\x16CanPostAsMemberRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\x03R\vcommunityId\x12(\n" +
	"\x10actor_profile_id\x18\x02 \x01(\x03R\x0eactorProfileId\"!\n" +
	"\x0fCanPostResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"F\n" +
	"\x18SearchCommunitiesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xaa\x02\n" +
	"\x13SearchCommunityItem\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\x03R\vcommunityId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\x03R\tprofileId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x15\n" +
	"\x03bio\x18\x05 \x01(\tH\x00R\x03bio\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12 \n" +
	"\tavatar_id\x18\a \x01(\x03H\x01R\bavatarId\x88\x01\x01\x12)\n" +
	"\x0ecover_media_id\x18\b \x01(\x03H\x02R\fcoverMediaId\x88\x01\x01B\x06\n" +
	"\x04_bioB\f\n" +
	"\n" +
	"_avatar_idB\x11\n" +
	"\x0f_cover_media_id\"e\n" +
	"\x19SearchCommunitiesResponse\x12H\n" +
	"\vcommunities\x18\x01 \x03(\v2&.aris.community.v1.SearchCommunityItemR\vcommunities2\xeb\x04\n" +
	"\x10CommunityService\x12\\\n" +
	"\fGetCommunity\x12&.aris.community.v1.GetCommunityRequest\x1a$.aris.community.v1.CommunityResponse\x12n\n" +
	"\x15GetCommunityByProfile\x12/.aris.community.v1.GetCommunityByProfileRequest\x1a$.aris.community.v1.CommunityResponse\x12S\n" +
	"\tGetMember\x12#.aris.community.v1.GetMemberRequest\x1a!.aris.community.v1.MemberResponse\x12b\n" +
	"\x10CanPostByProfile\x12*.aris.community.v1.CanPostByProfileRequest\x1a\".aris.community.v1.CanPostResponse\x12`\n" +
	"\x0fCanPostAsMember\x12).aris.community.v1.CanPostAsMemberRequest\x1a\".aris.community.v1.CanPostResponse\x12n\n" +
	"\x11SearchCommunities\x12+.aris.community.v1.SearchCommunitiesRequest\x1a,.aris.community.v1.SearchCommunitiesResponseBDZBgithub.com/go-park-mail-ru/2026_1_ARIS/proto/community;communitypbb\x06proto3"

var (
	file_proto_community_community_proto_rawDescOnce sync.Once
	file_proto_community_community_proto_rawDescData []byte
)

func file_proto_community_community_proto_rawDescGZIP() []byte {
	file_proto_community_community_proto_rawDescOnce.Do(func() {
		file_proto_community_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_community_community_proto_rawDesc), len(file_proto_community_community_proto_rawDesc)))
	})
	return file_proto_community_community_proto_rawDescData
}

var file_proto_community_community_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_community_community_proto_goTypes = []any{
	(*GetCommunityRequest)(nil),          // 0: aris.community.v1.GetCommunityRequest
	(*GetCommunityByProfileRequest)(nil), // 1: aris.community.v1.GetCommunityByProfileRequest
	(*CommunityResponse)(nil),            // 2: aris.community.v1.CommunityResponse
	(*GetMemberRequest)(nil),             // 3: aris.community.v1.GetMemberRequest
	(*MemberResponse)(nil),               // 4: aris.community.v1.MemberResponse
	(*CanPostByProfileRequest)(nil),      // 5: aris.community.v1.CanPostByProfileRequest
	(*CanPostAsMemberRequest)(nil),       // 6: aris.community.v1.CanPostAsMemberRequest
	(*CanPostResponse)(nil),              // 7: aris.community.v1.CanPostResponse
	(*SearchCommunitiesRequest)(nil),     // 8: aris.community.v1.SearchCommunitiesRequest
	(*SearchCommunityItem)(nil),          // 9: aris.community.v1.SearchCommunityItem
	(*SearchCommunitiesResponse)(nil),    // 10: aris.community.v1.SearchCommunitiesResponse
}
var file_proto_community_community_proto_depIdxs = []int32{
	9,  // 0: aris.community.v1.SearchCommunitiesResponse.communities:type_name -> aris.community.v1.SearchCommunityItem
	0,  // 1: aris.community.v1.CommunityService.GetCommunity:input_type -> aris.community.v1.GetCommunityRequest
	1,  // 2: aris.community.v1.CommunityService.GetCommunityByProfile:input_type -> aris.community.v1.GetCommunityByProfileRequest
	3,  // 3: aris.community.v1.CommunityService.GetMember:input_type -> aris.community.v1.GetMemberRequest
	5,  // 4: aris.community.v1.CommunityService.CanPostByProfile:input_type -> aris.community.v1.CanPostByProfileRequest
	6,  // 5: aris.community.v1.CommunityService.CanPostAsMember:input_type -> aris.community.v1.CanPostAsMemberRequest
	8,  // 6: aris.community.v1.CommunityService.SearchCommunities:input_type -> aris.community.v1.SearchCommunitiesRequest
	2,  // 7: aris.community.v1.CommunityService.GetCommunity:output_type -> aris.community.v1.CommunityResponse
	2,  // 8: aris.community.v1.CommunityService.GetCommunityByProfile:output_type -> aris.community.v1.CommunityResponse
	4,  // 9: aris.community.v1.CommunityService.GetMember:output_type -> aris.community.v1.MemberResponse
	7,  // 10: aris.community.v1.CommunityService.CanPostByProfile:output_type -> aris.community.v1.CanPostResponse
	7,  // 11: aris.community.v1.CommunityService.CanPostAsMember:output_type -> aris.community.v1.CanPostResponse
	10, // 12: aris.community.v1.CommunityService.SearchCommunities:output_type -> aris.community.v1.SearchCommunitiesResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_community_community_proto_init() }
func file_proto_community_community_proto_init() {
	if File_proto_community_community_proto != nil {
		return
	}
	file_proto_community_community_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_community_community_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_community_community_proto_rawDesc), len(file_proto_community_community_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_community_community_proto_goTypes,
		DependencyIndexes: file_proto_community_community_proto_depIdxs,
		MessageInfos:      file_proto_community_community_proto_msgTypes,
	}.Build()
	File_proto_community_community_proto = out.File
	file_proto_community_community_proto_goTypes = nil
	file_proto_community_community_proto_depIdxs = nil
}
