// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package http

import (
	json "encoding/json"
	model "github.com/go-park-mail-ru/2026_1_ARIS/services/user/internal/model"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp(in *jlexer.Lexer, out *workResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "company":
			if in.IsNull() {
				in.Skip()
				out.Company = nil
			} else {
				if out.Company == nil {
					out.Company = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Company = string(in.String())
				}
			}
		case "jobTitle":
			if in.IsNull() {
				in.Skip()
				out.JobTitle = nil
			} else {
				if out.JobTitle == nil {
					out.JobTitle = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.JobTitle = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp(out *jwriter.Writer, in workResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Company != nil {
		const prefix string = ",\"company\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Company))
	}
	if in.JobTitle != nil {
		const prefix string = ",\"jobTitle\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.JobTitle))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v workResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v workResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *workResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *workResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp1(in *jlexer.Lexer, out *userCardsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]userCardDTO, 0, 0)
					} else {
						out.Items = []userCardDTO{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v1 userCardDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp1(out *jwriter.Writer, in userCardsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix[1:])
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Items {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v userCardsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v userCardsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *userCardsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *userCardsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp1(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp2(in *jlexer.Lexer, out *userCardDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "firstName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "lastName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastName = string(in.String())
			}
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "avatarLink":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvatarLink = string(in.String())
			}
		case "isOnline":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsOnline = bool(in.Bool())
			}
		case "lastSeenAt":
			if in.IsNull() {
				in.Skip()
				out.LastSeenAt = nil
			} else {
				if out.LastSeenAt == nil {
					out.LastSeenAt = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.LastSeenAt = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp2(out *jwriter.Writer, in userCardDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"firstName\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"lastName\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"avatarLink\":"
		out.RawString(prefix)
		out.String(string(in.AvatarLink))
	}
	{
		const prefix string = ",\"isOnline\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsOnline))
	}
	if in.LastSeenAt != nil {
		const prefix string = ",\"lastSeenAt\":"
		out.RawString(prefix)
		out.String(string(*in.LastSeenAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v userCardDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v userCardDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *userCardDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *userCardDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp2(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp3(in *jlexer.Lexer, out *updateProfileRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "login":
			if in.IsNull() {
				in.Skip()
				out.Username = nil
			} else {
				if out.Username == nil {
					out.Username = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Username = string(in.String())
				}
			}
		case "email":
			if in.IsNull() {
				in.Skip()
				out.Email = nil
			} else {
				if out.Email == nil {
					out.Email = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Email = string(in.String())
				}
			}
		case "phone":
			if in.IsNull() {
				in.Skip()
				out.Phone = nil
			} else {
				if out.Phone == nil {
					out.Phone = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Phone = string(in.String())
				}
			}
		case "firstName":
			if in.IsNull() {
				in.Skip()
				out.FirstName = nil
			} else {
				if out.FirstName == nil {
					out.FirstName = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.FirstName = string(in.String())
				}
			}
		case "lastName":
			if in.IsNull() {
				in.Skip()
				out.LastName = nil
			} else {
				if out.LastName == nil {
					out.LastName = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.LastName = string(in.String())
				}
			}
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Bio = string(in.String())
				}
			}
		case "birthdayDate":
			if in.IsNull() {
				in.Skip()
				out.BirthdayDate = nil
			} else {
				if out.BirthdayDate == nil {
					out.BirthdayDate = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.BirthdayDate = string(in.String())
				}
			}
		case "gender":
			if in.IsNull() {
				in.Skip()
				out.Gender = nil
			} else {
				if out.Gender == nil {
					out.Gender = new(model.Gender)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Gender = model.Gender(in.String())
				}
			}
		case "avatarID":
			if in.IsNull() {
				in.Skip()
				out.AvatarID = nil
			} else {
				if out.AvatarID == nil {
					out.AvatarID = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AvatarID = int64(in.Int64())
				}
			}
		case "removeAvatar":
			if in.IsNull() {
				in.Skip()
				out.RemoveAvatar = nil
			} else {
				if out.RemoveAvatar == nil {
					out.RemoveAvatar = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.RemoveAvatar = bool(in.Bool())
				}
			}
		case "nativeTown":
			if in.IsNull() {
				in.Skip()
				out.NativeTown = nil
			} else {
				if out.NativeTown == nil {
					out.NativeTown = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.NativeTown = string(in.String())
				}
			}
		case "town":
			if in.IsNull() {
				in.Skip()
				out.Town = nil
			} else {
				if out.Town == nil {
					out.Town = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Town = string(in.String())
				}
			}
		case "institution":
			if in.IsNull() {
				in.Skip()
				out.Institution = nil
			} else {
				if out.Institution == nil {
					out.Institution = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Institution = string(in.String())
				}
			}
		case "group":
			if in.IsNull() {
				in.Skip()
				out.Group = nil
			} else {
				if out.Group == nil {
					out.Group = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Group = string(in.String())
				}
			}
		case "company":
			if in.IsNull() {
				in.Skip()
				out.Company = nil
			} else {
				if out.Company == nil {
					out.Company = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Company = string(in.String())
				}
			}
		case "jobTitle":
			if in.IsNull() {
				in.Skip()
				out.JobTitle = nil
			} else {
				if out.JobTitle == nil {
					out.JobTitle = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.JobTitle = string(in.String())
				}
			}
		case "interests":
			if in.IsNull() {
				in.Skip()
				out.Interests = nil
			} else {
				if out.Interests == nil {
					out.Interests = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Interests = string(in.String())
				}
			}
		case "favMusic":
			if in.IsNull() {
				in.Skip()
				out.FavMusic = nil
			} else {
				if out.FavMusic == nil {
					out.FavMusic = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.FavMusic = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp3(out *jwriter.Writer, in updateProfileRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Username != nil {
		const prefix string = ",\"login\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Username))
	}
	if in.Email != nil {
		const prefix string = ",\"email\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Email))
	}
	if in.Phone != nil {
		const prefix string = ",\"phone\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Phone))
	}
	if in.FirstName != nil {
		const prefix string = ",\"firstName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.FirstName))
	}
	if in.LastName != nil {
		const prefix string = ",\"lastName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.LastName))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Bio))
	}
	if in.BirthdayDate != nil {
		const prefix string = ",\"birthdayDate\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.BirthdayDate))
	}
	if in.Gender != nil {
		const prefix string = ",\"gender\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Gender))
	}
	if in.AvatarID != nil {
		const prefix string = ",\"avatarID\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(*in.AvatarID))
	}
	if in.RemoveAvatar != nil {
		const prefix string = ",\"removeAvatar\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(*in.RemoveAvatar))
	}
	if in.NativeTown != nil {
		const prefix string = ",\"nativeTown\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.NativeTown))
	}
	if in.Town != nil {
		const prefix string = ",\"town\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Town))
	}
	if in.Institution != nil {
		const prefix string = ",\"institution\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Institution))
	}
	if in.Group != nil {
		const prefix string = ",\"group\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Group))
	}
	if in.Company != nil {
		const prefix string = ",\"company\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Company))
	}
	if in.JobTitle != nil {
		const prefix string = ",\"jobTitle\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.JobTitle))
	}
	if in.Interests != nil {
		const prefix string = ",\"interests\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Interests))
	}
	if in.FavMusic != nil {
		const prefix string = ",\"favMusic\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.FavMusic))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v updateProfileRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v updateProfileRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *updateProfileRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *updateProfileRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp3(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp4(in *jlexer.Lexer, out *settingsUpdateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "language":
			if in.IsNull() {
				in.Skip()
				out.Language = nil
			} else {
				if out.Language == nil {
					out.Language = new(model.LanguageSetting)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Language = model.LanguageSetting(in.String())
				}
			}
		case "theme":
			if in.IsNull() {
				in.Skip()
				out.Theme = nil
			} else {
				if out.Theme == nil {
					out.Theme = new(model.ThemeSetting)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Theme = model.ThemeSetting(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp4(out *jwriter.Writer, in settingsUpdateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"language\":"
		out.RawString(prefix[1:])
		if in.Language == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Language))
		}
	}
	{
		const prefix string = ",\"theme\":"
		out.RawString(prefix)
		if in.Theme == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Theme))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v settingsUpdateRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v settingsUpdateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *settingsUpdateRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *settingsUpdateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp4(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp5(in *jlexer.Lexer, out *profileResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "profileId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProfileID = int64(in.Int64())
			}
		case "userAccountId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserAccountID = int64(in.Int64())
			}
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "firstName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "lastName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastName = string(in.String())
			}
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Bio = string(in.String())
				}
			}
		case "imageLink":
			if in.IsNull() {
				in.Skip()
				out.ImageLink = nil
			} else {
				if out.ImageLink == nil {
					out.ImageLink = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ImageLink = string(in.String())
				}
			}
		case "gender":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Gender = model.Gender(in.String())
			}
		case "birthday":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BirthdayDate = string(in.String())
			}
		case "nativeTown":
			if in.IsNull() {
				in.Skip()
				out.NativeTown = nil
			} else {
				if out.NativeTown == nil {
					out.NativeTown = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.NativeTown = string(in.String())
				}
			}
		case "phone":
			if in.IsNull() {
				in.Skip()
				out.Phone = nil
			} else {
				if out.Phone == nil {
					out.Phone = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Phone = string(in.String())
				}
			}
		case "email":
			if in.IsNull() {
				in.Skip()
				out.Email = nil
			} else {
				if out.Email == nil {
					out.Email = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Email = string(in.String())
				}
			}
		case "town":
			if in.IsNull() {
				in.Skip()
				out.Town = nil
			} else {
				if out.Town == nil {
					out.Town = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Town = string(in.String())
				}
			}
		case "education":
			if in.IsNull() {
				in.Skip()
				out.Education = nil
			} else {
				in.Delim('[')
				if out.Education == nil {
					if !in.IsDelim(']') {
						out.Education = make([]educationResponse, 0, 4)
					} else {
						out.Education = []educationResponse{}
					}
				} else {
					out.Education = (out.Education)[:0]
				}
				for !in.IsDelim(']') {
					var v4 educationResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Education = append(out.Education, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "work":
			if in.IsNull() {
				in.Skip()
				out.Work = nil
			} else {
				in.Delim('[')
				if out.Work == nil {
					if !in.IsDelim(']') {
						out.Work = make([]workResponse, 0, 4)
					} else {
						out.Work = []workResponse{}
					}
				} else {
					out.Work = (out.Work)[:0]
				}
				for !in.IsDelim(']') {
					var v5 workResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v5).UnmarshalEasyJSON(in)
					}
					out.Work = append(out.Work, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "interests":
			if in.IsNull() {
				in.Skip()
				out.Interests = nil
			} else {
				if out.Interests == nil {
					out.Interests = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Interests = string(in.String())
				}
			}
		case "favMusic":
			if in.IsNull() {
				in.Skip()
				out.FavMusic = nil
			} else {
				if out.FavMusic == nil {
					out.FavMusic = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.FavMusic = string(in.String())
				}
			}
		case "isOnline":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsOnline = bool(in.Bool())
			}
		case "lastSeenAt":
			if in.IsNull() {
				in.Skip()
				out.LastSeenAt = nil
			} else {
				if out.LastSeenAt == nil {
					out.LastSeenAt = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.LastSeenAt = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp5(out *jwriter.Writer, in profileResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"profileId\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ProfileID))
	}
	{
		const prefix string = ",\"userAccountId\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserAccountID))
	}
	if in.Username != "" {
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	if in.FirstName != "" {
		const prefix string = ",\"firstName\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	if in.LastName != "" {
		const prefix string = ",\"lastName\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		out.RawString(prefix)
		out.String(string(*in.Bio))
	}
	if in.ImageLink != nil {
		const prefix string = ",\"imageLink\":"
		out.RawString(prefix)
		out.String(string(*in.ImageLink))
	}
	if in.Gender != "" {
		const prefix string = ",\"gender\":"
		out.RawString(prefix)
		out.String(string(in.Gender))
	}
	if in.BirthdayDate != "" {
		const prefix string = ",\"birthday\":"
		out.RawString(prefix)
		out.String(string(in.BirthdayDate))
	}
	if in.NativeTown != nil {
		const prefix string = ",\"nativeTown\":"
		out.RawString(prefix)
		out.String(string(*in.NativeTown))
	}
	if in.Phone != nil {
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(*in.Phone))
	}
	if in.Email != nil {
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(*in.Email))
	}
	if in.Town != nil {
		const prefix string = ",\"town\":"
		out.RawString(prefix)
		out.String(string(*in.Town))
	}
	if len(in.Education) != 0 {
		const prefix string = ",\"education\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v6, v7 := range in.Education {
				if v6 > 0 {
					out.RawByte(',')
				}
				(v7).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.Work) != 0 {
		const prefix string = ",\"work\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v8, v9 := range in.Work {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Interests != nil {
		const prefix string = ",\"interests\":"
		out.RawString(prefix)
		out.String(string(*in.Interests))
	}
	if in.FavMusic != nil {
		const prefix string = ",\"favMusic\":"
		out.RawString(prefix)
		out.String(string(*in.FavMusic))
	}
	{
		const prefix string = ",\"isOnline\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsOnline))
	}
	if in.LastSeenAt != nil {
		const prefix string = ",\"lastSeenAt\":"
		out.RawString(prefix)
		out.String(string(*in.LastSeenAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v profileResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v profileResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *profileResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *profileResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp5(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp6(in *jlexer.Lexer, out *latestEventsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]latestEventDTO, 0, 0)
					} else {
						out.Items = []latestEventDTO{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v10 latestEventDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v10).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp6(out *jwriter.Writer, in latestEventsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix[1:])
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Items {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v latestEventsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v latestEventsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *latestEventsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *latestEventsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp6(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp7(in *jlexer.Lexer, out *latestEventDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "firstName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "lastName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastName = string(in.String())
			}
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "avatarLink":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvatarLink = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp7(out *jwriter.Writer, in latestEventDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"firstName\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"lastName\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"avatarLink\":"
		out.RawString(prefix)
		out.String(string(in.AvatarLink))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.Int(int(in.Type))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v latestEventDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v latestEventDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *latestEventDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *latestEventDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp7(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp8(in *jlexer.Lexer, out *friendsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "friends":
			if in.IsNull() {
				in.Skip()
				out.Friends = nil
			} else {
				in.Delim('[')
				if out.Friends == nil {
					if !in.IsDelim(']') {
						out.Friends = make([]friendDTO, 0, 0)
					} else {
						out.Friends = []friendDTO{}
					}
				} else {
					out.Friends = (out.Friends)[:0]
				}
				for !in.IsDelim(']') {
					var v13 friendDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v13).UnmarshalEasyJSON(in)
					}
					out.Friends = append(out.Friends, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp8(out *jwriter.Writer, in friendsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"friends\":"
		out.RawString(prefix[1:])
		if in.Friends == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Friends {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v friendsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v friendsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *friendsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *friendsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp8(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp9(in *jlexer.Lexer, out *friendRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "friendID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FriendID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp9(out *jwriter.Writer, in friendRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"friendID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.FriendID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v friendRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v friendRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *friendRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *friendRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp9(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp10(in *jlexer.Lexer, out *friendDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "avatarID":
			if in.IsNull() {
				in.Skip()
				out.AvatarID = nil
			} else {
				if out.AvatarID == nil {
					out.AvatarID = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AvatarID = int64(in.Int64())
				}
			}
		case "profileID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProfileID = int64(in.Int64())
			}
		case "firstName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "lastName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastName = string(in.String())
			}
		case "login":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = model.FriendshipStatus(in.String())
			}
		case "link":
			if in.IsNull() {
				in.Skip()
				out.AvatarLink = nil
			} else {
				if out.AvatarLink == nil {
					out.AvatarLink = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AvatarLink = string(in.String())
				}
			}
		case "createdAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp10(out *jwriter.Writer, in friendDTO) {
	out.RawByte('{')
	first := true
	_ = first
	if in.AvatarID != nil {
		const prefix string = ",\"avatarID\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(*in.AvatarID))
	}
	{
		const prefix string = ",\"profileID\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.ProfileID))
	}
	{
		const prefix string = ",\"firstName\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"lastName\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.AvatarLink != nil {
		const prefix string = ",\"link\":"
		out.RawString(prefix)
		out.String(string(*in.AvatarLink))
	}
	{
		const prefix string = ",\"createdAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v friendDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v friendDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *friendDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *friendDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp10(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp11(in *jlexer.Lexer, out *educationResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "institution":
			if in.IsNull() {
				in.Skip()
				out.Institution = nil
			} else {
				if out.Institution == nil {
					out.Institution = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Institution = string(in.String())
				}
			}
		case "grade":
			if in.IsNull() {
				in.Skip()
				out.Group = nil
			} else {
				if out.Group == nil {
					out.Group = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Group = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp11(out *jwriter.Writer, in educationResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Institution != nil {
		const prefix string = ",\"institution\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Institution))
	}
	if in.Group != nil {
		const prefix string = ",\"grade\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Group))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v educationResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v educationResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *educationResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *educationResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261ARISServicesUserInternalHandlerHttp11(l, v)
}
