// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_ARIS/internal/repository/chat_member (interfaces: ChatMemberRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_ARIS/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockChatMemberRepo is a mock of ChatMemberRepo interface.
type MockChatMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockChatMemberRepoMockRecorder
}

// MockChatMemberRepoMockRecorder is the mock recorder for MockChatMemberRepo.
type MockChatMemberRepoMockRecorder struct {
	mock *MockChatMemberRepo
}

// NewMockChatMemberRepo creates a new mock instance.
func NewMockChatMemberRepo(ctrl *gomock.Controller) *MockChatMemberRepo {
	mock := &MockChatMemberRepo{ctrl: ctrl}
	mock.recorder = &MockChatMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatMemberRepo) EXPECT() *MockChatMemberRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockChatMemberRepo) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockChatMemberRepoMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockChatMemberRepo)(nil).Delete), arg0, arg1)
}

// GetByChatID mocks base method.
func (m *MockChatMemberRepo) GetByChatID(arg0 context.Context, arg1 int64) ([]models.ChatMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByChatID", arg0, arg1)
	ret0, _ := ret[0].([]models.ChatMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByChatID indicates an expected call of GetByChatID.
func (mr *MockChatMemberRepoMockRecorder) GetByChatID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByChatID", reflect.TypeOf((*MockChatMemberRepo)(nil).GetByChatID), arg0, arg1)
}

// GetByUserID mocks base method.
func (m *MockChatMemberRepo) GetByUserID(arg0 context.Context, arg1 int64) ([]models.ChatMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].([]models.ChatMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockChatMemberRepoMockRecorder) GetByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockChatMemberRepo)(nil).GetByUserID), arg0, arg1)
}

// Save mocks base method.
func (m *MockChatMemberRepo) Save(arg0 context.Context, arg1 models.ChatMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockChatMemberRepoMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockChatMemberRepo)(nil).Save), arg0, arg1)
}
