// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_ARIS/internal/repository/post (interfaces: PostWithMediaRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_ARIS/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockPostWithMediaRepo is a mock of PostWithMediaRepo interface.
type MockPostWithMediaRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPostWithMediaRepoMockRecorder
}

// MockPostWithMediaRepoMockRecorder is the mock recorder for MockPostWithMediaRepo.
type MockPostWithMediaRepoMockRecorder struct {
	mock *MockPostWithMediaRepo
}

// NewMockPostWithMediaRepo creates a new mock instance.
func NewMockPostWithMediaRepo(ctrl *gomock.Controller) *MockPostWithMediaRepo {
	mock := &MockPostWithMediaRepo{ctrl: ctrl}
	mock.recorder = &MockPostWithMediaRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostWithMediaRepo) EXPECT() *MockPostWithMediaRepoMockRecorder {
	return m.recorder
}

// DeleteByPostID mocks base method.
func (m *MockPostWithMediaRepo) DeleteByPostID(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPostID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByPostID indicates an expected call of DeleteByPostID.
func (mr *MockPostWithMediaRepoMockRecorder) DeleteByPostID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPostID", reflect.TypeOf((*MockPostWithMediaRepo)(nil).DeleteByPostID), arg0, arg1)
}

// GetMediaByPostID mocks base method.
func (m *MockPostWithMediaRepo) GetMediaByPostID(arg0 context.Context, arg1 int64) []int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaByPostID", arg0, arg1)
	ret0, _ := ret[0].([]int64)
	return ret0
}

// GetMediaByPostID indicates an expected call of GetMediaByPostID.
func (mr *MockPostWithMediaRepoMockRecorder) GetMediaByPostID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaByPostID", reflect.TypeOf((*MockPostWithMediaRepo)(nil).GetMediaByPostID), arg0, arg1)
}

// Save mocks base method.
func (m *MockPostWithMediaRepo) Save(arg0 context.Context, arg1 models.PostWithMedia) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPostWithMediaRepoMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPostWithMediaRepo)(nil).Save), arg0, arg1)
}
