// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_ARIS/internal/repository/settings (interfaces: UserSettingsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_ARIS/internal/handler/dto"
	models "github.com/go-park-mail-ru/2026_1_ARIS/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockUserSettingsRepository is a mock of UserSettingsRepository interface.
type MockUserSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserSettingsRepositoryMockRecorder
}

// MockUserSettingsRepositoryMockRecorder is the mock recorder for MockUserSettingsRepository.
type MockUserSettingsRepositoryMockRecorder struct {
	mock *MockUserSettingsRepository
}

// NewMockUserSettingsRepository creates a new mock instance.
func NewMockUserSettingsRepository(ctrl *gomock.Controller) *MockUserSettingsRepository {
	mock := &MockUserSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockUserSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSettingsRepository) EXPECT() *MockUserSettingsRepositoryMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockUserSettingsRepository) GetByUserID(arg0 context.Context, arg1 int64) (*models.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].(*models.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserSettingsRepositoryMockRecorder) GetByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserSettingsRepository)(nil).GetByUserID), arg0, arg1)
}

// Update mocks base method.
func (m *MockUserSettingsRepository) Update(arg0 context.Context, arg1 int64, arg2 dto.UserSettingsUpdate) (*models.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserSettingsRepositoryMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserSettingsRepository)(nil).Update), arg0, arg1, arg2)
}
