// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_ARIS/internal/repository/user_profile (interfaces: UserProfileRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_ARIS/internal/dto"
	models "github.com/go-park-mail-ru/2026_1_ARIS/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockUserProfileRepo is a mock of UserProfileRepo interface.
type MockUserProfileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileRepoMockRecorder
}

// MockUserProfileRepoMockRecorder is the mock recorder for MockUserProfileRepo.
type MockUserProfileRepoMockRecorder struct {
	mock *MockUserProfileRepo
}

// NewMockUserProfileRepo creates a new mock instance.
func NewMockUserProfileRepo(ctrl *gomock.Controller) *MockUserProfileRepo {
	mock := &MockUserProfileRepo{ctrl: ctrl}
	mock.recorder = &MockUserProfileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfileRepo) EXPECT() *MockUserProfileRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUserProfileRepo) Get(arg0 context.Context, arg1 int64) (*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserProfileRepoMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserProfileRepo)(nil).Get), arg0, arg1)
}

// GetByProfileID mocks base method.
func (m *MockUserProfileRepo) GetByProfileID(arg0 context.Context, arg1 int64) (*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProfileID", arg0, arg1)
	ret0, _ := ret[0].(*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProfileID indicates an expected call of GetByProfileID.
func (mr *MockUserProfileRepoMockRecorder) GetByProfileID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProfileID", reflect.TypeOf((*MockUserProfileRepo)(nil).GetByProfileID), arg0, arg1)
}

// GetByUserAccountID mocks base method.
func (m *MockUserProfileRepo) GetByUserAccountID(arg0 context.Context, arg1 int64) (*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAccountID", arg0, arg1)
	ret0, _ := ret[0].(*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAccountID indicates an expected call of GetByUserAccountID.
func (mr *MockUserProfileRepoMockRecorder) GetByUserAccountID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAccountID", reflect.TypeOf((*MockUserProfileRepo)(nil).GetByUserAccountID), arg0, arg1)
}

// Save mocks base method.
func (m *MockUserProfileRepo) Save(arg0 context.Context, arg1 models.UserProfile) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockUserProfileRepoMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserProfileRepo)(nil).Save), arg0, arg1)
}

// Update mocks base method.
func (m *MockUserProfileRepo) Update(arg0 context.Context, arg1 dto.UpdateUserProfileDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserProfileRepoMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserProfileRepo)(nil).Update), arg0, arg1)
}
