---
title: ARIS
config:
    layout: elk
---
erDiagram
    %% Entities

    USER_ACCOUNT {
        bigint id PK
        uuid uid
        string email
        string phone
        string password_hash
        bool is_active
        datetime created_at
        datetime updated_at
    }

    USER_PROFILE {
        bigint id PK
        uuid uid
        bigint user_account_id FK
        bigint profile_id FK
        string firstName
        string lastName
        string bio
        date birthday_date
        string gender
        bool is_active
        datetime created_at
        datetime updated_at
    }

    PROFILE {
        bigint id PK
        uuid uid
        bigint avatar_id FK
        string username
        bool is_active
        datetime created_at
        datetime updated_at
    }

    "MEDIA (MinIO, S3)" {
        bigint id PK
        uuid uid
        string media_name
        string extension
        string description
        string mime_type
        bigint size
        bool is_active
        datetime created_at
        datetime updated_at
    }

    POST {
        bigint id PK
        uuid uid
        string post_text
        bigint author_id FK
        bool is_active
        datetime created_at
        datetime updated_at
    }

    POST_WITH_MEDIA {
        bigint post_id FK
        bigint media_id FK
        bigint sort_order
    }

    CHAT {
        bigint id PK
        uuid uid
        string chat_type
        string title
        bigint avatar_id FK
        bool is_active
        datetime created_at
        datetime updated_at
    }

    CHAT_MEMBER {
        bigint id PK
        uuid uid
        bigint chat_id FK
        bigint profile_id FK
        datetime joined_at
        datetime leaveAt
        string role
        bool is_active
        datetime created_at
        datetime updated_at
    }

    MESSAGE {
        bigint id PK
        uuid uid
        string message_text
        bigint parent_message_id FK
        bigint chat_id FK
        bigint sticker_id FK
        bigint author_id FK
        bool is_active
        datetime created_at
        datetime updated_at
    }

    MESSAGE_WITH_MEDIA {
        bigint message_id FK
        bigint media_id FK
        bigint sort_order
    }

    COMMUNITY {
        bigint id PK
        uuid uid
        string title
        string bio
        string community_type
        bigint profile_id FK
        bool is_active
        datetime created_at
        datetime updated_at
    }

    COMMUNITY_MEMBER {
        bigint id PK
        uuid uid
        bigint profile_id FK
        bigint community_id FK
        string community_role
        datetime joined_at
        datetime leave_at
        bool is_active
        datetime created_at
        datetime updated_at
    }

    COMMENT {
        bigint id PK
        uuid uid
        string comment_text
        bigint post_id FK
        bigint parent_comment_id FK
        bigint sticker_id FK
        bigint author_id FK
        bool is_active
        datetime created_at
        datetime updated_at
    }

    COMMENT_WITH_MEDIA {
        bigint comment_id FK
        bigint media_id FK
        bigint sort_order
    }

    LIKE_RECORD {
        bigint id PK
        uuid uid
        bigint post_id FK
        bigint comment_id FK
        bigint author_id FK
        bool is_active
        datetime created_at
        datetime updated_at
    }

    REACTION {
        bigint id PK
        uuid uid
        bigint message_id FK
        string reaction_type
        bigint author_id FK
        bool is_active
        datetime created_at
        datetime updated_at
    }

    FRIENDSHIP {
        bigint friend1_id FK
        bigint friend2_id FK
        bigint requester_id FK
        bool is_active
        datetime created_at
        datetime updated_at
    }

    STICKERPACK {
        bigint id PK
        uuid uid
        string title
        bigint author_id FK
        bool is_active
        datetime created_at
        datetime updated_at
    }

    STICKER {
        bigint id PK
        uuid uid
        bigint size
        bigint sort_order
        bigint pack_id FK
        bool is_active
        datetime created_at
        datetime updated_at
    }

    AD {
        bigint id PK
        uuid uid
        string title
        string description
        string link
        bigint media_id FK
        bigint author_id FK
        bool is_active
        datetime created_at
        datetime updated_at
    }

    AD_META {
        bigint id PK
        uuid uid
        bigint ad_id FK
        string meta_key
        string meta_value
    }

    "SESSION (REDIS)" {
        bigint id
        bigint profile_id
        datetime created_at
        datetime expires_at
        bool is_active
        datetime created_at
        datetime updated_at
    }

    %% Relationships

    USER_ACCOUNT ||--|| USER_PROFILE : has
    PROFILE ||--|| USER_PROFILE : has
    "MEDIA (MinIO, S3)" ||--o{ PROFILE : "avatars"
    PROFILE ||--o{ POST : "authors"
    POST ||--o{ POST_WITH_MEDIA : "MEDIA (MinIO, S3)"
    "MEDIA (MinIO, S3)" ||--o{ POST_WITH_MEDIA : "posts"
    "MEDIA (MinIO, S3)" ||--o{ CHAT : "avatars"
    CHAT ||--o{ CHAT_MEMBER : "members"
    PROFILE ||--|| CHAT_MEMBER : "members"
    MESSAGE ||--o{ MESSAGE : "replies"
    CHAT ||--o{ MESSAGE : "messages"
    MESSAGE ||--o| STICKER : "sticker"
    PROFILE ||--o{ MESSAGE : "authors"
    MESSAGE ||--o{ MESSAGE_WITH_MEDIA : "MEDIA (MinIO, S3)"
    "MEDIA (MinIO, S3)" ||--o{ MESSAGE_WITH_MEDIA : "messages"
    PROFILE ||--o{ "COMMUNITY" : "group profile"
    PROFILE ||--|| COMMUNITY_MEMBER : "members"
    COMMUNITY ||--o{ COMMUNITY_MEMBER : "members"
    POST ||--o{ COMMENT : "comments"
    COMMENT ||--o{ COMMENT : "replies"
    MESSAGE ||--o| STICKER : "sticker"
    PROFILE ||--o{ COMMENT : "authors"
    COMMENT ||--o{ COMMENT_WITH_MEDIA : "MEDIA (MinIO, S3)"
    "MEDIA (MinIO, S3)" ||--o{ COMMENT_WITH_MEDIA : "comments"
    POST ||--o{ "LIKE_RECORD" : "likes"
    COMMENT ||--o{ "LIKE_RECORD" : "likes"
    PROFILE ||--o{ LIKE_RECORD : "authors"
    MESSAGE ||--o{ REACTION : "reactions"
    PROFILE ||--o{ REACTION : "authors"
    PROFILE ||--o{ FRIENDSHIP : "friend1"
    PROFILE ||--o{ FRIENDSHIP : "friend2"
    PROFILE ||--o{ FRIENDSHIP : "requester"
    PROFILE ||--o{ STICKERPACK : "authors"
    STICKERPACK ||--o{ STICKER : "stickers"
    "MEDIA (MinIO, S3)" ||--o{ AD : "MEDIA (MinIO, S3)"
    PROFILE ||--o{ AD : "authors"
    AD ||--o{ AD_META : "meta"