// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/user_account/user_account.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_ARIS/internal/dto"
	models "github.com/go-park-mail-ru/2026_1_ARIS/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
)

// MockUserAccountRepo is a mock of UserAccountRepo interface.
type MockUserAccountRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserAccountRepoMockRecorder
}

// MockUserAccountRepoMockRecorder is the mock recorder for MockUserAccountRepo.
type MockUserAccountRepoMockRecorder struct {
	mock *MockUserAccountRepo
}

// NewMockUserAccountRepo creates a new mock instance.
func NewMockUserAccountRepo(ctrl *gomock.Controller) *MockUserAccountRepo {
	mock := &MockUserAccountRepo{ctrl: ctrl}
	mock.recorder = &MockUserAccountRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAccountRepo) EXPECT() *MockUserAccountRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserAccountRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserAccountRepoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserAccountRepo)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockUserAccountRepo) Get(ctx context.Context, id int64) (*models.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserAccountRepoMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserAccountRepo)(nil).Get), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockUserAccountRepo) GetByEmail(ctx context.Context, email string) (*models.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*models.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserAccountRepoMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserAccountRepo)(nil).GetByEmail), ctx, email)
}

// GetByPhone mocks base method.
func (m *MockUserAccountRepo) GetByPhone(ctx context.Context, phone string) (*models.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPhone", ctx, phone)
	ret0, _ := ret[0].(*models.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPhone indicates an expected call of GetByPhone.
func (mr *MockUserAccountRepoMockRecorder) GetByPhone(ctx, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPhone", reflect.TypeOf((*MockUserAccountRepo)(nil).GetByPhone), ctx, phone)
}

// GetByUid mocks base method.
func (m *MockUserAccountRepo) GetByUid(ctx context.Context, uid uuid.UUID) (*models.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUid", ctx, uid)
	ret0, _ := ret[0].(*models.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUid indicates an expected call of GetByUid.
func (mr *MockUserAccountRepoMockRecorder) GetByUid(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUid", reflect.TypeOf((*MockUserAccountRepo)(nil).GetByUid), ctx, uid)
}

// GetByUsername mocks base method.
func (m *MockUserAccountRepo) GetByUsername(ctx context.Context, username string) (*models.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*models.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserAccountRepoMockRecorder) GetByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserAccountRepo)(nil).GetByUsername), ctx, username)
}

// List mocks base method.
func (m *MockUserAccountRepo) List(ctx context.Context, offset, limit int) ([]models.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]models.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserAccountRepoMockRecorder) List(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserAccountRepo)(nil).List), ctx, offset, limit)
}

// Save mocks base method.
func (m *MockUserAccountRepo) Save(ctx context.Context, userAccount models.UserAccount) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userAccount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockUserAccountRepoMockRecorder) Save(ctx, userAccount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserAccountRepo)(nil).Save), ctx, userAccount)
}

// Update mocks base method.
func (m *MockUserAccountRepo) Update(ctx context.Context, dto dto.UpdateUserAccountDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserAccountRepoMockRecorder) Update(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserAccountRepo)(nil).Update), ctx, dto)
}

// MockuserAccountDB is a mock of userAccountDB interface.
type MockuserAccountDB struct {
	ctrl     *gomock.Controller
	recorder *MockuserAccountDBMockRecorder
}

// MockuserAccountDBMockRecorder is the mock recorder for MockuserAccountDB.
type MockuserAccountDBMockRecorder struct {
	mock *MockuserAccountDB
}

// NewMockuserAccountDB creates a new mock instance.
func NewMockuserAccountDB(ctrl *gomock.Controller) *MockuserAccountDB {
	mock := &MockuserAccountDB{ctrl: ctrl}
	mock.recorder = &MockuserAccountDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserAccountDB) EXPECT() *MockuserAccountDBMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockuserAccountDB) Exec(arg0 context.Context, arg1 string, arg2 ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockuserAccountDBMockRecorder) Exec(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockuserAccountDB)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockuserAccountDB) Query(arg0 context.Context, arg1 string, arg2 ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockuserAccountDBMockRecorder) Query(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockuserAccountDB)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockuserAccountDB) QueryRow(arg0 context.Context, arg1 string, arg2 ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockuserAccountDBMockRecorder) QueryRow(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockuserAccountDB)(nil).QueryRow), varargs...)
}
