// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/go-park-mail-ru/2026_1_ARIS/services/user/internal/model"
	repository "github.com/go-park-mail-ru/2026_1_ARIS/services/user/internal/repository"
	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDB) Begin(arg0 context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", arg0)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockDBMockRecorder) Begin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDB)(nil).Begin), arg0)
}

// Exec mocks base method.
func (m *MockDB) Exec(arg0 context.Context, arg1 string, arg2 ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBMockRecorder) Exec(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDB)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockDB) Query(arg0 context.Context, arg1 string, arg2 ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDBMockRecorder) Query(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDB)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockDB) QueryRow(arg0 context.Context, arg1 string, arg2 ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockDBMockRecorder) QueryRow(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockDB)(nil).QueryRow), varargs...)
}

// MockAccountRepo is a mock of AccountRepo interface.
type MockAccountRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepoMockRecorder
}

// MockAccountRepoMockRecorder is the mock recorder for MockAccountRepo.
type MockAccountRepoMockRecorder struct {
	mock *MockAccountRepo
}

// NewMockAccountRepo creates a new mock instance.
func NewMockAccountRepo(ctrl *gomock.Controller) *MockAccountRepo {
	mock := &MockAccountRepo{ctrl: ctrl}
	mock.recorder = &MockAccountRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepo) EXPECT() *MockAccountRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAccountRepo) Get(ctx context.Context, id int64) (*model.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAccountRepoMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAccountRepo)(nil).Get), ctx, id)
}

// GetByUsername mocks base method.
func (m *MockAccountRepo) GetByUsername(ctx context.Context, username string) (*model.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*model.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockAccountRepoMockRecorder) GetByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockAccountRepo)(nil).GetByUsername), ctx, username)
}

// Save mocks base method.
func (m *MockAccountRepo) Save(ctx context.Context, account model.UserAccount) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, account)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockAccountRepoMockRecorder) Save(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAccountRepo)(nil).Save), ctx, account)
}

// Update mocks base method.
func (m *MockAccountRepo) Update(ctx context.Context, update repository.AccountUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAccountRepoMockRecorder) Update(ctx, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountRepo)(nil).Update), ctx, update)
}

// MockOAuthAccountRepo is a mock of OAuthAccountRepo interface.
type MockOAuthAccountRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthAccountRepoMockRecorder
}

// MockOAuthAccountRepoMockRecorder is the mock recorder for MockOAuthAccountRepo.
type MockOAuthAccountRepoMockRecorder struct {
	mock *MockOAuthAccountRepo
}

// NewMockOAuthAccountRepo creates a new mock instance.
func NewMockOAuthAccountRepo(ctrl *gomock.Controller) *MockOAuthAccountRepo {
	mock := &MockOAuthAccountRepo{ctrl: ctrl}
	mock.recorder = &MockOAuthAccountRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthAccountRepo) EXPECT() *MockOAuthAccountRepoMockRecorder {
	return m.recorder
}

// GetUserAccountID mocks base method.
func (m *MockOAuthAccountRepo) GetUserAccountID(ctx context.Context, provider, providerUserID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccountID", ctx, provider, providerUserID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccountID indicates an expected call of GetUserAccountID.
func (mr *MockOAuthAccountRepoMockRecorder) GetUserAccountID(ctx, provider, providerUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccountID", reflect.TypeOf((*MockOAuthAccountRepo)(nil).GetUserAccountID), ctx, provider, providerUserID)
}

// Save mocks base method.
func (m *MockOAuthAccountRepo) Save(ctx context.Context, provider, providerUserID string, userAccountID int64, email *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, provider, providerUserID, userAccountID, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockOAuthAccountRepoMockRecorder) Save(ctx, provider, providerUserID, userAccountID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockOAuthAccountRepo)(nil).Save), ctx, provider, providerUserID, userAccountID, email)
}

// MockProfileRepo is a mock of ProfileRepo interface.
type MockProfileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProfileRepoMockRecorder
}

// MockProfileRepoMockRecorder is the mock recorder for MockProfileRepo.
type MockProfileRepoMockRecorder struct {
	mock *MockProfileRepo
}

// NewMockProfileRepo creates a new mock instance.
func NewMockProfileRepo(ctrl *gomock.Controller) *MockProfileRepo {
	mock := &MockProfileRepo{ctrl: ctrl}
	mock.recorder = &MockProfileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileRepo) EXPECT() *MockProfileRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProfileRepo) Get(ctx context.Context, profileID int64) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, profileID)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProfileRepoMockRecorder) Get(ctx, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProfileRepo)(nil).Get), ctx, profileID)
}

// GetAll mocks base method.
func (m *MockProfileRepo) GetAll(ctx context.Context) ([]model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockProfileRepoMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockProfileRepo)(nil).GetAll), ctx)
}

// GetByUserAccountID mocks base method.
func (m *MockProfileRepo) GetByUserAccountID(ctx context.Context, userAccountID int64) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAccountID", ctx, userAccountID)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAccountID indicates an expected call of GetByUserAccountID.
func (mr *MockProfileRepoMockRecorder) GetByUserAccountID(ctx, userAccountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAccountID", reflect.TypeOf((*MockProfileRepo)(nil).GetByUserAccountID), ctx, userAccountID)
}

// Save mocks base method.
func (m *MockProfileRepo) Save(ctx context.Context, profile model.Profile) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, profile)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockProfileRepoMockRecorder) Save(ctx, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProfileRepo)(nil).Save), ctx, profile)
}

// UpdateAvatar mocks base method.
func (m *MockProfileRepo) UpdateAvatar(ctx context.Context, profileID int64, avatarID *int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, profileID, avatarID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockProfileRepoMockRecorder) UpdateAvatar(ctx, profileID, avatarID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockProfileRepo)(nil).UpdateAvatar), ctx, profileID, avatarID)
}

// MockUserProfileRepo is a mock of UserProfileRepo interface.
type MockUserProfileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileRepoMockRecorder
}

// MockUserProfileRepoMockRecorder is the mock recorder for MockUserProfileRepo.
type MockUserProfileRepoMockRecorder struct {
	mock *MockUserProfileRepo
}

// NewMockUserProfileRepo creates a new mock instance.
func NewMockUserProfileRepo(ctrl *gomock.Controller) *MockUserProfileRepo {
	mock := &MockUserProfileRepo{ctrl: ctrl}
	mock.recorder = &MockUserProfileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfileRepo) EXPECT() *MockUserProfileRepoMockRecorder {
	return m.recorder
}

// GetByProfileID mocks base method.
func (m *MockUserProfileRepo) GetByProfileID(ctx context.Context, profileID int64) (*model.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProfileID", ctx, profileID)
	ret0, _ := ret[0].(*model.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProfileID indicates an expected call of GetByProfileID.
func (mr *MockUserProfileRepoMockRecorder) GetByProfileID(ctx, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProfileID", reflect.TypeOf((*MockUserProfileRepo)(nil).GetByProfileID), ctx, profileID)
}

// GetByUserAccountID mocks base method.
func (m *MockUserProfileRepo) GetByUserAccountID(ctx context.Context, userAccountID int64) (*model.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAccountID", ctx, userAccountID)
	ret0, _ := ret[0].(*model.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAccountID indicates an expected call of GetByUserAccountID.
func (mr *MockUserProfileRepoMockRecorder) GetByUserAccountID(ctx, userAccountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAccountID", reflect.TypeOf((*MockUserProfileRepo)(nil).GetByUserAccountID), ctx, userAccountID)
}

// Save mocks base method.
func (m *MockUserProfileRepo) Save(ctx context.Context, userProfile model.UserProfile) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userProfile)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockUserProfileRepoMockRecorder) Save(ctx, userProfile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserProfileRepo)(nil).Save), ctx, userProfile)
}

// Search mocks base method.
func (m *MockUserProfileRepo) Search(ctx context.Context, query string, limit int) ([]repository.SearchProfileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit)
	ret0, _ := ret[0].([]repository.SearchProfileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockUserProfileRepoMockRecorder) Search(ctx, query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockUserProfileRepo)(nil).Search), ctx, query, limit)
}

// Update mocks base method.
func (m *MockUserProfileRepo) Update(ctx context.Context, update repository.UserProfileUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserProfileRepoMockRecorder) Update(ctx, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserProfileRepo)(nil).Update), ctx, update)
}

// MockSettingsRepo is a mock of SettingsRepo interface.
type MockSettingsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsRepoMockRecorder
}

// MockSettingsRepoMockRecorder is the mock recorder for MockSettingsRepo.
type MockSettingsRepoMockRecorder struct {
	mock *MockSettingsRepo
}

// NewMockSettingsRepo creates a new mock instance.
func NewMockSettingsRepo(ctrl *gomock.Controller) *MockSettingsRepo {
	mock := &MockSettingsRepo{ctrl: ctrl}
	mock.recorder = &MockSettingsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsRepo) EXPECT() *MockSettingsRepoMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockSettingsRepo) GetByUserID(ctx context.Context, userID int64) (*model.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockSettingsRepoMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockSettingsRepo)(nil).GetByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockSettingsRepo) Update(ctx context.Context, userID int64, update repository.SettingsUpdate) (*model.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, update)
	ret0, _ := ret[0].(*model.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSettingsRepoMockRecorder) Update(ctx, userID, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSettingsRepo)(nil).Update), ctx, userID, update)
}

// MockFriendshipRepo is a mock of FriendshipRepo interface.
type MockFriendshipRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFriendshipRepoMockRecorder
}

// MockFriendshipRepoMockRecorder is the mock recorder for MockFriendshipRepo.
type MockFriendshipRepoMockRecorder struct {
	mock *MockFriendshipRepo
}

// NewMockFriendshipRepo creates a new mock instance.
func NewMockFriendshipRepo(ctrl *gomock.Controller) *MockFriendshipRepo {
	mock := &MockFriendshipRepo{ctrl: ctrl}
	mock.recorder = &MockFriendshipRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendshipRepo) EXPECT() *MockFriendshipRepoMockRecorder {
	return m.recorder
}

// AcceptFriendship mocks base method.
func (m *MockFriendshipRepo) AcceptFriendship(ctx context.Context, profileID1, profileID2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptFriendship", ctx, profileID1, profileID2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptFriendship indicates an expected call of AcceptFriendship.
func (mr *MockFriendshipRepoMockRecorder) AcceptFriendship(ctx, profileID1, profileID2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptFriendship", reflect.TypeOf((*MockFriendshipRepo)(nil).AcceptFriendship), ctx, profileID1, profileID2)
}

// Create mocks base method.
func (m *MockFriendshipRepo) Create(ctx context.Context, profileID, friendID int64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, profileID, friendID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFriendshipRepoMockRecorder) Create(ctx, profileID, friendID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFriendshipRepo)(nil).Create), ctx, profileID, friendID, status)
}

// DeclineFriendship mocks base method.
func (m *MockFriendshipRepo) DeclineFriendship(ctx context.Context, profileID1, profileID2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeclineFriendship", ctx, profileID1, profileID2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeclineFriendship indicates an expected call of DeclineFriendship.
func (mr *MockFriendshipRepoMockRecorder) DeclineFriendship(ctx, profileID1, profileID2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeclineFriendship", reflect.TypeOf((*MockFriendshipRepo)(nil).DeclineFriendship), ctx, profileID1, profileID2)
}

// DeleteFriend mocks base method.
func (m *MockFriendshipRepo) DeleteFriend(ctx context.Context, profileID, friendID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFriend", ctx, profileID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFriend indicates an expected call of DeleteFriend.
func (mr *MockFriendshipRepoMockRecorder) DeleteFriend(ctx, profileID, friendID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFriend", reflect.TypeOf((*MockFriendshipRepo)(nil).DeleteFriend), ctx, profileID, friendID)
}

// GetFriends mocks base method.
func (m *MockFriendshipRepo) GetFriends(ctx context.Context, profileID int64, status model.FriendshipStatus) ([]model.Friend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriends", ctx, profileID, status)
	ret0, _ := ret[0].([]model.Friend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriends indicates an expected call of GetFriends.
func (mr *MockFriendshipRepoMockRecorder) GetFriends(ctx, profileID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriends", reflect.TypeOf((*MockFriendshipRepo)(nil).GetFriends), ctx, profileID, status)
}

// GetFriendshipStatusBy mocks base method.
func (m *MockFriendshipRepo) GetFriendshipStatusBy(ctx context.Context, profileID, friendID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendshipStatusBy", ctx, profileID, friendID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendshipStatusBy indicates an expected call of GetFriendshipStatusBy.
func (mr *MockFriendshipRepoMockRecorder) GetFriendshipStatusBy(ctx, profileID, friendID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendshipStatusBy", reflect.TypeOf((*MockFriendshipRepo)(nil).GetFriendshipStatusBy), ctx, profileID, friendID)
}

// GetIncomingFriends mocks base method.
func (m *MockFriendshipRepo) GetIncomingFriends(ctx context.Context, profileID int64, status string) ([]model.Friend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomingFriends", ctx, profileID, status)
	ret0, _ := ret[0].([]model.Friend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomingFriends indicates an expected call of GetIncomingFriends.
func (mr *MockFriendshipRepoMockRecorder) GetIncomingFriends(ctx, profileID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomingFriends", reflect.TypeOf((*MockFriendshipRepo)(nil).GetIncomingFriends), ctx, profileID, status)
}

// GetOutgoingFriends mocks base method.
func (m *MockFriendshipRepo) GetOutgoingFriends(ctx context.Context, profileID int64, status string) ([]model.Friend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutgoingFriends", ctx, profileID, status)
	ret0, _ := ret[0].([]model.Friend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutgoingFriends indicates an expected call of GetOutgoingFriends.
func (mr *MockFriendshipRepoMockRecorder) GetOutgoingFriends(ctx, profileID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutgoingFriends", reflect.TypeOf((*MockFriendshipRepo)(nil).GetOutgoingFriends), ctx, profileID, status)
}

// RevokeFriendRequest mocks base method.
func (m *MockFriendshipRepo) RevokeFriendRequest(ctx context.Context, profileID, friendID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeFriendRequest", ctx, profileID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeFriendRequest indicates an expected call of RevokeFriendRequest.
func (mr *MockFriendshipRepoMockRecorder) RevokeFriendRequest(ctx, profileID, friendID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeFriendRequest", reflect.TypeOf((*MockFriendshipRepo)(nil).RevokeFriendRequest), ctx, profileID, friendID)
}
