// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_ARIS/tools/seed/internal/repository/like (interfaces: LikeRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_ARIS/tools/seed/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockLikeRepo is a mock of LikeRepo interface.
type MockLikeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLikeRepoMockRecorder
}

// MockLikeRepoMockRecorder is the mock recorder for MockLikeRepo.
type MockLikeRepoMockRecorder struct {
	mock *MockLikeRepo
}

// NewMockLikeRepo creates a new mock instance.
func NewMockLikeRepo(ctrl *gomock.Controller) *MockLikeRepo {
	mock := &MockLikeRepo{ctrl: ctrl}
	mock.recorder = &MockLikeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeRepo) EXPECT() *MockLikeRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLikeRepo) Get(arg0 context.Context, arg1 int64) (*models.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLikeRepoMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLikeRepo)(nil).Get), arg0, arg1)
}

// GetLikeCountOnPost mocks base method.
func (m *MockLikeRepo) GetLikeCountOnPost(arg0 context.Context, arg1 int64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikeCountOnPost", arg0, arg1)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetLikeCountOnPost indicates an expected call of GetLikeCountOnPost.
func (mr *MockLikeRepoMockRecorder) GetLikeCountOnPost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikeCountOnPost", reflect.TypeOf((*MockLikeRepo)(nil).GetLikeCountOnPost), arg0, arg1)
}

// GetPostLikeByAuthor mocks base method.
func (m *MockLikeRepo) GetPostLikeByAuthor(arg0 context.Context, arg1, arg2 int64) (*models.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostLikeByAuthor", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostLikeByAuthor indicates an expected call of GetPostLikeByAuthor.
func (mr *MockLikeRepoMockRecorder) GetPostLikeByAuthor(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostLikeByAuthor", reflect.TypeOf((*MockLikeRepo)(nil).GetPostLikeByAuthor), arg0, arg1, arg2)
}

// HasActivePostLike mocks base method.
func (m *MockLikeRepo) HasActivePostLike(arg0 context.Context, arg1, arg2 int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActivePostLike", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasActivePostLike indicates an expected call of HasActivePostLike.
func (mr *MockLikeRepoMockRecorder) HasActivePostLike(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActivePostLike", reflect.TypeOf((*MockLikeRepo)(nil).HasActivePostLike), arg0, arg1, arg2)
}

// Save mocks base method.
func (m *MockLikeRepo) Save(arg0 context.Context, arg1 models.Like) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockLikeRepoMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLikeRepo)(nil).Save), arg0, arg1)
}

// SetActive mocks base method.
func (m *MockLikeRepo) SetActive(arg0 context.Context, arg1 int64, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockLikeRepoMockRecorder) SetActive(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockLikeRepo)(nil).SetActive), arg0, arg1, arg2)
}
