// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_ARIS/tools/seed/internal/repository/repost (interfaces: RepostRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_ARIS/tools/seed/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepostRepo is a mock of RepostRepo interface.
type MockRepostRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepostRepoMockRecorder
}

// MockRepostRepoMockRecorder is the mock recorder for MockRepostRepo.
type MockRepostRepoMockRecorder struct {
	mock *MockRepostRepo
}

// NewMockRepostRepo creates a new mock instance.
func NewMockRepostRepo(ctrl *gomock.Controller) *MockRepostRepo {
	mock := &MockRepostRepo{ctrl: ctrl}
	mock.recorder = &MockRepostRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepostRepo) EXPECT() *MockRepostRepoMockRecorder {
	return m.recorder
}

// GetRepostCount mocks base method.
func (m *MockRepostRepo) GetRepostCount(arg0 context.Context, arg1 int64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepostCount", arg0, arg1)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRepostCount indicates an expected call of GetRepostCount.
func (mr *MockRepostRepoMockRecorder) GetRepostCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepostCount", reflect.TypeOf((*MockRepostRepo)(nil).GetRepostCount), arg0, arg1)
}

// Save mocks base method.
func (m *MockRepostRepo) Save(arg0 context.Context, arg1 models.Repost) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockRepostRepoMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepostRepo)(nil).Save), arg0, arg1)
}
