// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_ARIS/internal/service/media (interfaces: MediaService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_ARIS/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockMediaService is a mock of MediaService interface.
type MockMediaService struct {
	ctrl     *gomock.Controller
	recorder *MockMediaServiceMockRecorder
}

// MockMediaServiceMockRecorder is the mock recorder for MockMediaService.
type MockMediaServiceMockRecorder struct {
	mock *MockMediaService
}

// NewMockMediaService creates a new mock instance.
func NewMockMediaService(ctrl *gomock.Controller) *MockMediaService {
	mock := &MockMediaService{ctrl: ctrl}
	mock.recorder = &MockMediaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaService) EXPECT() *MockMediaServiceMockRecorder {
	return m.recorder
}

// GetAvatarByID mocks base method.
func (m *MockMediaService) GetAvatarByID(arg0 context.Context, arg1 *int64) (*models.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarByID indicates an expected call of GetAvatarByID.
func (mr *MockMediaServiceMockRecorder) GetAvatarByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarByID", reflect.TypeOf((*MockMediaService)(nil).GetAvatarByID), arg0, arg1)
}

// GetMediasByPostID mocks base method.
func (m *MockMediaService) GetMediasByPostID(arg0 context.Context, arg1 int64) []models.Media {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediasByPostID", arg0, arg1)
	ret0, _ := ret[0].([]models.Media)
	return ret0
}

// GetMediasByPostID indicates an expected call of GetMediasByPostID.
func (mr *MockMediaServiceMockRecorder) GetMediasByPostID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediasByPostID", reflect.TypeOf((*MockMediaService)(nil).GetMediasByPostID), arg0, arg1)
}

// Save mocks base method.
func (m *MockMediaService) Save(arg0 context.Context, arg1 string, arg2 int64, arg3 multipart.File, arg4 string, arg5 int64) (int64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Save indicates an expected call of Save.
func (mr *MockMediaServiceMockRecorder) Save(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMediaService)(nil).Save), arg0, arg1, arg2, arg3, arg4, arg5)
}
