// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_ARIS/internal/service/post (interfaces: PostService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_ARIS/internal/handler/dto"
	models "github.com/go-park-mail-ru/2026_1_ARIS/internal/models"
	post "github.com/go-park-mail-ru/2026_1_ARIS/internal/service/post"
	gomock "github.com/golang/mock/gomock"
)

// MockPostService is a mock of PostService interface.
type MockPostService struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceMockRecorder
}

// MockPostServiceMockRecorder is the mock recorder for MockPostService.
type MockPostServiceMockRecorder struct {
	mock *MockPostService
}

// NewMockPostService creates a new mock instance.
func NewMockPostService(ctrl *gomock.Controller) *MockPostService {
	mock := &MockPostService{ctrl: ctrl}
	mock.recorder = &MockPostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostService) EXPECT() *MockPostServiceMockRecorder {
	return m.recorder
}

// AttachMedia mocks base method.
func (m *MockPostService) AttachMedia(arg0 context.Context, arg1 int64, arg2 []dto.MediaRequestData) post.MediaErrors {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachMedia", arg0, arg1, arg2)
	ret0, _ := ret[0].(post.MediaErrors)
	return ret0
}

// AttachMedia indicates an expected call of AttachMedia.
func (mr *MockPostServiceMockRecorder) AttachMedia(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachMedia", reflect.TypeOf((*MockPostService)(nil).AttachMedia), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockPostService) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPostServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPostService)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockPostService) Get(arg0 context.Context, arg1 int64) (*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPostServiceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPostService)(nil).Get), arg0, arg1)
}

// GetByAuthorID mocks base method.
func (m *MockPostService) GetByAuthorID(arg0 context.Context, arg1 int64) ([]models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAuthorID", arg0, arg1)
	ret0, _ := ret[0].([]models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAuthorID indicates an expected call of GetByAuthorID.
func (mr *MockPostServiceMockRecorder) GetByAuthorID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAuthorID", reflect.TypeOf((*MockPostService)(nil).GetByAuthorID), arg0, arg1)
}

// GetCommentCount mocks base method.
func (m *MockPostService) GetCommentCount(arg0 context.Context, arg1 int64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentCount", arg0, arg1)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetCommentCount indicates an expected call of GetCommentCount.
func (mr *MockPostServiceMockRecorder) GetCommentCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentCount", reflect.TypeOf((*MockPostService)(nil).GetCommentCount), arg0, arg1)
}

// GetFeed mocks base method.
func (m *MockPostService) GetFeed(arg0 context.Context, arg1 string, arg2 int) (post.FeedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", arg0, arg1, arg2)
	ret0, _ := ret[0].(post.FeedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockPostServiceMockRecorder) GetFeed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockPostService)(nil).GetFeed), arg0, arg1, arg2)
}

// GetLikeCount mocks base method.
func (m *MockPostService) GetLikeCount(arg0 context.Context, arg1 int64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikeCount", arg0, arg1)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetLikeCount indicates an expected call of GetLikeCount.
func (mr *MockPostServiceMockRecorder) GetLikeCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikeCount", reflect.TypeOf((*MockPostService)(nil).GetLikeCount), arg0, arg1)
}

// GetPopularPosts mocks base method.
func (m *MockPostService) GetPopularPosts(arg0 context.Context) ([]models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularPosts", arg0)
	ret0, _ := ret[0].([]models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularPosts indicates an expected call of GetPopularPosts.
func (mr *MockPostServiceMockRecorder) GetPopularPosts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularPosts", reflect.TypeOf((*MockPostService)(nil).GetPopularPosts), arg0)
}

// GetPostAuthor mocks base method.
func (m *MockPostService) GetPostAuthor(arg0 context.Context, arg1 int64) (*models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostAuthor", arg0, arg1)
	ret0, _ := ret[0].(*models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostAuthor indicates an expected call of GetPostAuthor.
func (mr *MockPostServiceMockRecorder) GetPostAuthor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostAuthor", reflect.TypeOf((*MockPostService)(nil).GetPostAuthor), arg0, arg1)
}

// GetPublicFeed mocks base method.
func (m *MockPostService) GetPublicFeed(arg0 context.Context, arg1 string, arg2 int) (post.FeedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicFeed", arg0, arg1, arg2)
	ret0, _ := ret[0].(post.FeedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicFeed indicates an expected call of GetPublicFeed.
func (mr *MockPostServiceMockRecorder) GetPublicFeed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicFeed", reflect.TypeOf((*MockPostService)(nil).GetPublicFeed), arg0, arg1, arg2)
}

// GetPublicPopularPosts mocks base method.
func (m *MockPostService) GetPublicPopularPosts(arg0 context.Context) ([]models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicPopularPosts", arg0)
	ret0, _ := ret[0].([]models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicPopularPosts indicates an expected call of GetPublicPopularPosts.
func (mr *MockPostServiceMockRecorder) GetPublicPopularPosts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicPopularPosts", reflect.TypeOf((*MockPostService)(nil).GetPublicPopularPosts), arg0)
}

// GetRepostCount mocks base method.
func (m *MockPostService) GetRepostCount(arg0 context.Context, arg1 int64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepostCount", arg0, arg1)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRepostCount indicates an expected call of GetRepostCount.
func (mr *MockPostServiceMockRecorder) GetRepostCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepostCount", reflect.TypeOf((*MockPostService)(nil).GetRepostCount), arg0, arg1)
}

// ReplaceMedia mocks base method.
func (m *MockPostService) ReplaceMedia(arg0 context.Context, arg1 int64, arg2 []dto.MediaRequestData) post.MediaErrors {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceMedia", arg0, arg1, arg2)
	ret0, _ := ret[0].(post.MediaErrors)
	return ret0
}

// ReplaceMedia indicates an expected call of ReplaceMedia.
func (mr *MockPostServiceMockRecorder) ReplaceMedia(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceMedia", reflect.TypeOf((*MockPostService)(nil).ReplaceMedia), arg0, arg1, arg2)
}

// Save mocks base method.
func (m *MockPostService) Save(arg0 context.Context, arg1 models.Post) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockPostServiceMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPostService)(nil).Save), arg0, arg1)
}

// Update mocks base method.
func (m *MockPostService) Update(arg0 context.Context, arg1 models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPostServiceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPostService)(nil).Update), arg0, arg1)
}

// getFeed mocks base method.
func (m *MockPostService) getFeed(arg0 context.Context, arg1 func(context.Context, post.FeedParams) ([]models.Post, error), arg2 string, arg3 int) (post.FeedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getFeed", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(post.FeedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getFeed indicates an expected call of getFeed.
func (mr *MockPostServiceMockRecorder) getFeed(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getFeed", reflect.TypeOf((*MockPostService)(nil).getFeed), arg0, arg1, arg2, arg3)
}
