// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_ARIS/internal/service (interfaces: UserService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/go-park-mail-ru/2026_1_ARIS/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// CreateRealUserProfile mocks base method.
func (m *MockUserService) CreateRealUserProfile(arg0 context.Context, arg1, arg2, arg3, arg4, arg5, arg6 string, arg7 bool, arg8 *time.Time, arg9 models.Gender, arg10 *models.Media) (*models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRealUserProfile", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)
	ret0, _ := ret[0].(*models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRealUserProfile indicates an expected call of CreateRealUserProfile.
func (mr *MockUserServiceMockRecorder) CreateRealUserProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRealUserProfile", reflect.TypeOf((*MockUserService)(nil).CreateRealUserProfile), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)
}

// GetUserProfileByProfile mocks base method.
func (m *MockUserService) GetUserProfileByProfile(arg0 context.Context, arg1 uuid.UUID) (*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfileByProfile", arg0, arg1)
	ret0, _ := ret[0].(*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfileByProfile indicates an expected call of GetUserProfileByProfile.
func (mr *MockUserServiceMockRecorder) GetUserProfileByProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfileByProfile", reflect.TypeOf((*MockUserService)(nil).GetUserProfileByProfile), arg0, arg1)
}

// GetUserList mocks base method.
func (m *MockUserService) GetUserList(arg0 context.Context, arg1, arg2 int) []models.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserList", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.User)
	return ret0
}

// GetUserList indicates an expected call of GetUserList.
func (mr *MockUserServiceMockRecorder) GetUserList(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserList", reflect.TypeOf((*MockUserService)(nil).GetUserList), arg0, arg1, arg2)
}

// GetUserProfileByUserProfileID mocks base method.
func (m *MockUserService) GetUserProfileByUserProfileID(arg0 uuid.UUID) (*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfileByUserProfileID", arg0)
	ret0, _ := ret[0].(*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfileByUserProfileID indicates an expected call of GetUserProfileByUserProfileID.
func (mr *MockUserServiceMockRecorder) GetUserProfileByUserProfileID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfileByUserProfileID", reflect.TypeOf((*MockUserService)(nil).GetUserProfileByUserProfileID), arg0)
}
