// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_ARIS/internal/service/settings (interfaces: UserSettingsService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_ARIS/internal/handler/dto"
	models "github.com/go-park-mail-ru/2026_1_ARIS/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockUserSettingsService is a mock of UserSettingsService interface.
type MockUserSettingsService struct {
	ctrl     *gomock.Controller
	recorder *MockUserSettingsServiceMockRecorder
}

// MockUserSettingsServiceMockRecorder is the mock recorder for MockUserSettingsService.
type MockUserSettingsServiceMockRecorder struct {
	mock *MockUserSettingsService
}

// NewMockUserSettingsService creates a new mock instance.
func NewMockUserSettingsService(ctrl *gomock.Controller) *MockUserSettingsService {
	mock := &MockUserSettingsService{ctrl: ctrl}
	mock.recorder = &MockUserSettingsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSettingsService) EXPECT() *MockUserSettingsServiceMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockUserSettingsService) GetByUserID(arg0 context.Context, arg1 int64) (*models.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].(*models.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserSettingsServiceMockRecorder) GetByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserSettingsService)(nil).GetByUserID), arg0, arg1)
}

// Update mocks base method.
func (m *MockUserSettingsService) Update(arg0 context.Context, arg1 int64, arg2 dto.UserSettingsUpdate) (*models.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserSettingsServiceMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserSettingsService)(nil).Update), arg0, arg1, arg2)
}
