// Code generated by MockGen. DO NOT EDIT.
// Source: services/post/internal/handler/http/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	analytics "github.com/go-park-mail-ru/2026_1_ARIS/services/post/internal/analytics"
	usecase "github.com/go-park-mail-ru/2026_1_ARIS/services/post/internal/usecase"
	gomock "github.com/golang/mock/gomock"
)

// MockPostService is a mock of PostService interface.
type MockPostService struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceMockRecorder
}

// MockPostServiceMockRecorder is the mock recorder for MockPostService.
type MockPostServiceMockRecorder struct {
	mock *MockPostService
}

// NewMockPostService creates a new mock instance.
func NewMockPostService(ctrl *gomock.Controller) *MockPostService {
	mock := &MockPostService{ctrl: ctrl}
	mock.recorder = &MockPostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostService) EXPECT() *MockPostServiceMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockPostService) CreateComment(arg0 context.Context, arg1, arg2 int64, arg3 string, arg4 *int64) (*usecase.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*usecase.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockPostServiceMockRecorder) CreateComment(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockPostService)(nil).CreateComment), arg0, arg1, arg2, arg3, arg4)
}

// CreatePost mocks base method.
func (m *MockPostService) CreatePost(arg0 context.Context, arg1 int64, arg2 usecase.CreateInput) (*usecase.PostDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", arg0, arg1, arg2)
	ret0, _ := ret[0].(*usecase.PostDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostServiceMockRecorder) CreatePost(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostService)(nil).CreatePost), arg0, arg1, arg2)
}

// DeleteComment mocks base method.
func (m *MockPostService) DeleteComment(arg0 context.Context, arg1, arg2, arg3 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockPostServiceMockRecorder) DeleteComment(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockPostService)(nil).DeleteComment), arg0, arg1, arg2, arg3)
}

// DeletePost mocks base method.
func (m *MockPostService) DeletePost(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockPostServiceMockRecorder) DeletePost(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockPostService)(nil).DeletePost), arg0, arg1, arg2)
}

// GetCommentReplies mocks base method.
func (m *MockPostService) GetCommentReplies(arg0 context.Context, arg1, arg2, arg3 int64, arg4, arg5 int) ([]usecase.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentReplies", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]usecase.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentReplies indicates an expected call of GetCommentReplies.
func (mr *MockPostServiceMockRecorder) GetCommentReplies(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentReplies", reflect.TypeOf((*MockPostService)(nil).GetCommentReplies), arg0, arg1, arg2, arg3, arg4, arg5)
}

// GetCommentRepliesBatch mocks base method.
func (m *MockPostService) GetCommentRepliesBatch(arg0 context.Context, arg1, arg2 int64, arg3 []int64, arg4, arg5 int) (map[int64][]usecase.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentRepliesBatch", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(map[int64][]usecase.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentRepliesBatch indicates an expected call of GetCommentRepliesBatch.
func (mr *MockPostServiceMockRecorder) GetCommentRepliesBatch(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentRepliesBatch", reflect.TypeOf((*MockPostService)(nil).GetCommentRepliesBatch), arg0, arg1, arg2, arg3, arg4, arg5)
}

// GetCommunityOfficialPosts mocks base method.
func (m *MockPostService) GetCommunityOfficialPosts(arg0 context.Context, arg1, arg2 int64) ([]usecase.PostDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunityOfficialPosts", arg0, arg1, arg2)
	ret0, _ := ret[0].([]usecase.PostDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunityOfficialPosts indicates an expected call of GetCommunityOfficialPosts.
func (mr *MockPostServiceMockRecorder) GetCommunityOfficialPosts(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunityOfficialPosts", reflect.TypeOf((*MockPostService)(nil).GetCommunityOfficialPosts), arg0, arg1, arg2)
}

// GetCommunityPosts mocks base method.
func (m *MockPostService) GetCommunityPosts(arg0 context.Context, arg1, arg2 int64) ([]usecase.PostDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunityPosts", arg0, arg1, arg2)
	ret0, _ := ret[0].([]usecase.PostDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunityPosts indicates an expected call of GetCommunityPosts.
func (mr *MockPostServiceMockRecorder) GetCommunityPosts(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunityPosts", reflect.TypeOf((*MockPostService)(nil).GetCommunityPosts), arg0, arg1, arg2)
}

// GetFeed mocks base method.
func (m *MockPostService) GetFeed(arg0 context.Context, arg1 int64, arg2, arg3 string, arg4 int) (usecase.FeedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(usecase.FeedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockPostServiceMockRecorder) GetFeed(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockPostService)(nil).GetFeed), arg0, arg1, arg2, arg3, arg4)
}

// GetMyPosts mocks base method.
func (m *MockPostService) GetMyPosts(arg0 context.Context, arg1 int64) ([]usecase.PostDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyPosts", arg0, arg1)
	ret0, _ := ret[0].([]usecase.PostDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyPosts indicates an expected call of GetMyPosts.
func (mr *MockPostServiceMockRecorder) GetMyPosts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyPosts", reflect.TypeOf((*MockPostService)(nil).GetMyPosts), arg0, arg1)
}

// GetPostComments mocks base method.
func (m *MockPostService) GetPostComments(arg0 context.Context, arg1, arg2 int64, arg3, arg4 int) ([]usecase.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostComments", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]usecase.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostComments indicates an expected call of GetPostComments.
func (mr *MockPostServiceMockRecorder) GetPostComments(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostComments", reflect.TypeOf((*MockPostService)(nil).GetPostComments), arg0, arg1, arg2, arg3, arg4)
}

// GetPostForViewer mocks base method.
func (m *MockPostService) GetPostForViewer(arg0 context.Context, arg1, arg2 int64) (*usecase.PostDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostForViewer", arg0, arg1, arg2)
	ret0, _ := ret[0].(*usecase.PostDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostForViewer indicates an expected call of GetPostForViewer.
func (mr *MockPostServiceMockRecorder) GetPostForViewer(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostForViewer", reflect.TypeOf((*MockPostService)(nil).GetPostForViewer), arg0, arg1, arg2)
}

// GetProfilePosts mocks base method.
func (m *MockPostService) GetProfilePosts(arg0 context.Context, arg1, arg2 int64) ([]usecase.PostDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfilePosts", arg0, arg1, arg2)
	ret0, _ := ret[0].([]usecase.PostDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfilePosts indicates an expected call of GetProfilePosts.
func (mr *MockPostServiceMockRecorder) GetProfilePosts(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfilePosts", reflect.TypeOf((*MockPostService)(nil).GetProfilePosts), arg0, arg1, arg2)
}

// GetPublicFeed mocks base method.
func (m *MockPostService) GetPublicFeed(arg0 context.Context, arg1 string, arg2 int) (usecase.FeedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicFeed", arg0, arg1, arg2)
	ret0, _ := ret[0].(usecase.FeedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicFeed indicates an expected call of GetPublicFeed.
func (mr *MockPostServiceMockRecorder) GetPublicFeed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicFeed", reflect.TypeOf((*MockPostService)(nil).GetPublicFeed), arg0, arg1, arg2)
}

// LikeComment mocks base method.
func (m *MockPostService) LikeComment(arg0 context.Context, arg1, arg2, arg3 int64) (*usecase.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikeComment", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*usecase.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LikeComment indicates an expected call of LikeComment.
func (mr *MockPostServiceMockRecorder) LikeComment(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikeComment", reflect.TypeOf((*MockPostService)(nil).LikeComment), arg0, arg1, arg2, arg3)
}

// LikePost mocks base method.
func (m *MockPostService) LikePost(arg0 context.Context, arg1, arg2 int64) (*usecase.PostDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikePost", arg0, arg1, arg2)
	ret0, _ := ret[0].(*usecase.PostDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LikePost indicates an expected call of LikePost.
func (mr *MockPostServiceMockRecorder) LikePost(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikePost", reflect.TypeOf((*MockPostService)(nil).LikePost), arg0, arg1, arg2)
}

// RecordFeedEvents mocks base method.
func (m *MockPostService) RecordFeedEvents(arg0 context.Context, arg1 int64, arg2 []analytics.PostEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordFeedEvents", arg0, arg1, arg2)
}

// RecordFeedEvents indicates an expected call of RecordFeedEvents.
func (mr *MockPostServiceMockRecorder) RecordFeedEvents(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFeedEvents", reflect.TypeOf((*MockPostService)(nil).RecordFeedEvents), arg0, arg1, arg2)
}

// UnlikeComment mocks base method.
func (m *MockPostService) UnlikeComment(arg0 context.Context, arg1, arg2, arg3 int64) (*usecase.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlikeComment", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*usecase.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlikeComment indicates an expected call of UnlikeComment.
func (mr *MockPostServiceMockRecorder) UnlikeComment(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlikeComment", reflect.TypeOf((*MockPostService)(nil).UnlikeComment), arg0, arg1, arg2, arg3)
}

// UnlikePost mocks base method.
func (m *MockPostService) UnlikePost(arg0 context.Context, arg1, arg2 int64) (*usecase.PostDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlikePost", arg0, arg1, arg2)
	ret0, _ := ret[0].(*usecase.PostDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlikePost indicates an expected call of UnlikePost.
func (mr *MockPostServiceMockRecorder) UnlikePost(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlikePost", reflect.TypeOf((*MockPostService)(nil).UnlikePost), arg0, arg1, arg2)
}

// UpdateComment mocks base method.
func (m *MockPostService) UpdateComment(arg0 context.Context, arg1, arg2, arg3 int64, arg4 string) (*usecase.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*usecase.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockPostServiceMockRecorder) UpdateComment(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockPostService)(nil).UpdateComment), arg0, arg1, arg2, arg3, arg4)
}

// UpdatePost mocks base method.
func (m *MockPostService) UpdatePost(arg0 context.Context, arg1, arg2 int64, arg3 usecase.UpdateInput) (*usecase.PostDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*usecase.PostDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockPostServiceMockRecorder) UpdatePost(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockPostService)(nil).UpdatePost), arg0, arg1, arg2, arg3)
}
