// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/go-park-mail-ru/2026_1_ARIS/services/game/internal/model"
	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockDB) Exec(arg0 context.Context, arg1 string, arg2 ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBMockRecorder) Exec(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDB)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockDB) Query(arg0 context.Context, arg1 string, arg2 ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDBMockRecorder) Query(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDB)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockDB) QueryRow(arg0 context.Context, arg1 string, arg2 ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockDBMockRecorder) QueryRow(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockDB)(nil).QueryRow), varargs...)
}

// MockQuestionRepo is a mock of QuestionRepo interface.
type MockQuestionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionRepoMockRecorder
}

// MockQuestionRepoMockRecorder is the mock recorder for MockQuestionRepo.
type MockQuestionRepoMockRecorder struct {
	mock *MockQuestionRepo
}

// NewMockQuestionRepo creates a new mock instance.
func NewMockQuestionRepo(ctrl *gomock.Controller) *MockQuestionRepo {
	mock := &MockQuestionRepo{ctrl: ctrl}
	mock.recorder = &MockQuestionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionRepo) EXPECT() *MockQuestionRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockQuestionRepo) Create(ctx context.Context, q *model.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, q)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockQuestionRepoMockRecorder) Create(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuestionRepo)(nil).Create), ctx, q)
}

// Delete mocks base method.
func (m *MockQuestionRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQuestionRepoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQuestionRepo)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockQuestionRepo) Get(ctx context.Context, id int64) (*model.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockQuestionRepoMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockQuestionRepo)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockQuestionRepo) List(ctx context.Context, gameType string, includeInactive bool, limit, offset int) ([]model.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, gameType, includeInactive, limit, offset)
	ret0, _ := ret[0].([]model.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockQuestionRepoMockRecorder) List(ctx, gameType, includeInactive, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockQuestionRepo)(nil).List), ctx, gameType, includeInactive, limit, offset)
}

// Random mocks base method.
func (m *MockQuestionRepo) Random(ctx context.Context, gameType string, limit int) ([]model.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Random", ctx, gameType, limit)
	ret0, _ := ret[0].([]model.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Random indicates an expected call of Random.
func (mr *MockQuestionRepoMockRecorder) Random(ctx, gameType, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Random", reflect.TypeOf((*MockQuestionRepo)(nil).Random), ctx, gameType, limit)
}

// Update mocks base method.
func (m *MockQuestionRepo) Update(ctx context.Context, q *model.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, q)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQuestionRepoMockRecorder) Update(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQuestionRepo)(nil).Update), ctx, q)
}

// MockRoomRepo is a mock of RoomRepo interface.
type MockRoomRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRoomRepoMockRecorder
}

// MockRoomRepoMockRecorder is the mock recorder for MockRoomRepo.
type MockRoomRepoMockRecorder struct {
	mock *MockRoomRepo
}

// NewMockRoomRepo creates a new mock instance.
func NewMockRoomRepo(ctrl *gomock.Controller) *MockRoomRepo {
	mock := &MockRoomRepo{ctrl: ctrl}
	mock.recorder = &MockRoomRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomRepo) EXPECT() *MockRoomRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomRepo) Create(ctx context.Context, room *model.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomRepoMockRecorder) Create(ctx, room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomRepo)(nil).Create), ctx, room)
}

// Deactivate mocks base method.
func (m *MockRoomRepo) Deactivate(ctx context.Context, roomID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockRoomRepoMockRecorder) Deactivate(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockRoomRepo)(nil).Deactivate), ctx, roomID)
}

// DeactivateEmptyWaitingOlderThan mocks base method.
func (m *MockRoomRepo) DeactivateEmptyWaitingOlderThan(ctx context.Context, olderThan time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateEmptyWaitingOlderThan", ctx, olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateEmptyWaitingOlderThan indicates an expected call of DeactivateEmptyWaitingOlderThan.
func (mr *MockRoomRepoMockRecorder) DeactivateEmptyWaitingOlderThan(ctx, olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateEmptyWaitingOlderThan", reflect.TypeOf((*MockRoomRepo)(nil).DeactivateEmptyWaitingOlderThan), ctx, olderThan)
}

// ExpiredActiveIDsForProfile mocks base method.
func (m *MockRoomRepo) ExpiredActiveIDsForProfile(ctx context.Context, profileID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpiredActiveIDsForProfile", ctx, profileID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpiredActiveIDsForProfile indicates an expected call of ExpiredActiveIDsForProfile.
func (mr *MockRoomRepoMockRecorder) ExpiredActiveIDsForProfile(ctx, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpiredActiveIDsForProfile", reflect.TypeOf((*MockRoomRepo)(nil).ExpiredActiveIDsForProfile), ctx, profileID)
}

// Get mocks base method.
func (m *MockRoomRepo) Get(ctx context.Context, id int64) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoomRepoMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoomRepo)(nil).Get), ctx, id)
}

// GetByInviteCode mocks base method.
func (m *MockRoomRepo) GetByInviteCode(ctx context.Context, code string) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInviteCode", ctx, code)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInviteCode indicates an expected call of GetByInviteCode.
func (mr *MockRoomRepoMockRecorder) GetByInviteCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInviteCode", reflect.TypeOf((*MockRoomRepo)(nil).GetByInviteCode), ctx, code)
}

// GetForUpdate mocks base method.
func (m *MockRoomRepo) GetForUpdate(ctx context.Context, id int64) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForUpdate", ctx, id)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForUpdate indicates an expected call of GetForUpdate.
func (mr *MockRoomRepoMockRecorder) GetForUpdate(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForUpdate", reflect.TypeOf((*MockRoomRepo)(nil).GetForUpdate), ctx, id)
}

// GetWaitingCreatedByProfile mocks base method.
func (m *MockRoomRepo) GetWaitingCreatedByProfile(ctx context.Context, profileID int64) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWaitingCreatedByProfile", ctx, profileID)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWaitingCreatedByProfile indicates an expected call of GetWaitingCreatedByProfile.
func (mr *MockRoomRepoMockRecorder) GetWaitingCreatedByProfile(ctx, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWaitingCreatedByProfile", reflect.TypeOf((*MockRoomRepo)(nil).GetWaitingCreatedByProfile), ctx, profileID)
}

// HistoryForProfile mocks base method.
func (m *MockRoomRepo) HistoryForProfile(ctx context.Context, profileID int64, limit, offset int) ([]model.HistoryRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HistoryForProfile", ctx, profileID, limit, offset)
	ret0, _ := ret[0].([]model.HistoryRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HistoryForProfile indicates an expected call of HistoryForProfile.
func (mr *MockRoomRepoMockRecorder) HistoryForProfile(ctx, profileID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HistoryForProfile", reflect.TypeOf((*MockRoomRepo)(nil).HistoryForProfile), ctx, profileID, limit, offset)
}

// ListForProfile mocks base method.
func (m *MockRoomRepo) ListForProfile(ctx context.Context, profileID int64, limit, offset int) ([]model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForProfile", ctx, profileID, limit, offset)
	ret0, _ := ret[0].([]model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForProfile indicates an expected call of ListForProfile.
func (mr *MockRoomRepoMockRecorder) ListForProfile(ctx, profileID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForProfile", reflect.TypeOf((*MockRoomRepo)(nil).ListForProfile), ctx, profileID, limit, offset)
}

// TouchEmptyWaiting mocks base method.
func (m *MockRoomRepo) TouchEmptyWaiting(ctx context.Context, roomID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchEmptyWaiting", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchEmptyWaiting indicates an expected call of TouchEmptyWaiting.
func (mr *MockRoomRepoMockRecorder) TouchEmptyWaiting(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchEmptyWaiting", reflect.TypeOf((*MockRoomRepo)(nil).TouchEmptyWaiting), ctx, roomID)
}

// Update mocks base method.
func (m *MockRoomRepo) Update(ctx context.Context, room *model.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoomRepoMockRecorder) Update(ctx, room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoomRepo)(nil).Update), ctx, room)
}

// UpdateAdmin mocks base method.
func (m *MockRoomRepo) UpdateAdmin(ctx context.Context, roomID, profileID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdmin", ctx, roomID, profileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdmin indicates an expected call of UpdateAdmin.
func (mr *MockRoomRepoMockRecorder) UpdateAdmin(ctx, roomID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdmin", reflect.TypeOf((*MockRoomRepo)(nil).UpdateAdmin), ctx, roomID, profileID)
}

// UpdateTitle mocks base method.
func (m *MockRoomRepo) UpdateTitle(ctx context.Context, roomID int64, title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTitle", ctx, roomID, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTitle indicates an expected call of UpdateTitle.
func (mr *MockRoomRepoMockRecorder) UpdateTitle(ctx, roomID, title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTitle", reflect.TypeOf((*MockRoomRepo)(nil).UpdateTitle), ctx, roomID, title)
}

// MockMemberRepo is a mock of MemberRepo interface.
type MockMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMemberRepoMockRecorder
}

// MockMemberRepoMockRecorder is the mock recorder for MockMemberRepo.
type MockMemberRepoMockRecorder struct {
	mock *MockMemberRepo
}

// NewMockMemberRepo creates a new mock instance.
func NewMockMemberRepo(ctrl *gomock.Controller) *MockMemberRepo {
	mock := &MockMemberRepo{ctrl: ctrl}
	mock.recorder = &MockMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberRepo) EXPECT() *MockMemberRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockMemberRepo) Add(ctx context.Context, roomID, profileID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, roomID, profileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockMemberRepoMockRecorder) Add(ctx, roomID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockMemberRepo)(nil).Add), ctx, roomID, profileID)
}

// ClearForceResumeRequests mocks base method.
func (m *MockMemberRepo) ClearForceResumeRequests(ctx context.Context, roomID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearForceResumeRequests", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearForceResumeRequests indicates an expected call of ClearForceResumeRequests.
func (mr *MockMemberRepoMockRecorder) ClearForceResumeRequests(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearForceResumeRequests", reflect.TypeOf((*MockMemberRepo)(nil).ClearForceResumeRequests), ctx, roomID)
}

// ClearReady mocks base method.
func (m *MockMemberRepo) ClearReady(ctx context.Context, roomID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearReady", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearReady indicates an expected call of ClearReady.
func (mr *MockMemberRepoMockRecorder) ClearReady(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearReady", reflect.TypeOf((*MockMemberRepo)(nil).ClearReady), ctx, roomID)
}

// Deactivate mocks base method.
func (m *MockMemberRepo) Deactivate(ctx context.Context, roomID, profileID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", ctx, roomID, profileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockMemberRepoMockRecorder) Deactivate(ctx, roomID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockMemberRepo)(nil).Deactivate), ctx, roomID, profileID)
}

// DeactivateStaleWaiting mocks base method.
func (m *MockMemberRepo) DeactivateStaleWaiting(ctx context.Context, olderThan time.Duration) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateStaleWaiting", ctx, olderThan)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeactivateStaleWaiting indicates an expected call of DeactivateStaleWaiting.
func (mr *MockMemberRepoMockRecorder) DeactivateStaleWaiting(ctx, olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateStaleWaiting", reflect.TypeOf((*MockMemberRepo)(nil).DeactivateStaleWaiting), ctx, olderThan)
}

// DeactivateWaitingForProfile mocks base method.
func (m *MockMemberRepo) DeactivateWaitingForProfile(ctx context.Context, profileID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateWaitingForProfile", ctx, profileID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeactivateWaitingForProfile indicates an expected call of DeactivateWaitingForProfile.
func (mr *MockMemberRepoMockRecorder) DeactivateWaitingForProfile(ctx, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateWaitingForProfile", reflect.TypeOf((*MockMemberRepo)(nil).DeactivateWaitingForProfile), ctx, profileID)
}

// IncrementScore mocks base method.
func (m *MockMemberRepo) IncrementScore(ctx context.Context, roomID, profileID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementScore", ctx, roomID, profileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementScore indicates an expected call of IncrementScore.
func (mr *MockMemberRepoMockRecorder) IncrementScore(ctx, roomID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementScore", reflect.TypeOf((*MockMemberRepo)(nil).IncrementScore), ctx, roomID, profileID)
}

// IsMember mocks base method.
func (m *MockMemberRepo) IsMember(ctx context.Context, roomID, profileID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, roomID, profileID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockMemberRepoMockRecorder) IsMember(ctx, roomID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockMemberRepo)(nil).IsMember), ctx, roomID, profileID)
}

// List mocks base method.
func (m *MockMemberRepo) List(ctx context.Context, roomID int64) ([]model.RoomMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, roomID)
	ret0, _ := ret[0].([]model.RoomMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMemberRepoMockRecorder) List(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMemberRepo)(nil).List), ctx, roomID)
}

// ResetForReplay mocks base method.
func (m *MockMemberRepo) ResetForReplay(ctx context.Context, roomID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetForReplay", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetForReplay indicates an expected call of ResetForReplay.
func (mr *MockMemberRepoMockRecorder) ResetForReplay(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetForReplay", reflect.TypeOf((*MockMemberRepo)(nil).ResetForReplay), ctx, roomID)
}

// SetForceResumeRequested mocks base method.
func (m *MockMemberRepo) SetForceResumeRequested(ctx context.Context, roomID, profileID int64, requested bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetForceResumeRequested", ctx, roomID, profileID, requested)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetForceResumeRequested indicates an expected call of SetForceResumeRequested.
func (mr *MockMemberRepoMockRecorder) SetForceResumeRequested(ctx, roomID, profileID, requested interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetForceResumeRequested", reflect.TypeOf((*MockMemberRepo)(nil).SetForceResumeRequested), ctx, roomID, profileID, requested)
}

// SetPauseUsed mocks base method.
func (m *MockMemberRepo) SetPauseUsed(ctx context.Context, roomID, profileID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPauseUsed", ctx, roomID, profileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPauseUsed indicates an expected call of SetPauseUsed.
func (mr *MockMemberRepoMockRecorder) SetPauseUsed(ctx, roomID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPauseUsed", reflect.TypeOf((*MockMemberRepo)(nil).SetPauseUsed), ctx, roomID, profileID)
}

// SetReady mocks base method.
func (m *MockMemberRepo) SetReady(ctx context.Context, roomID, profileID int64, isReady bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReady", ctx, roomID, profileID, isReady)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReady indicates an expected call of SetReady.
func (mr *MockMemberRepoMockRecorder) SetReady(ctx, roomID, profileID, isReady interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReady", reflect.TypeOf((*MockMemberRepo)(nil).SetReady), ctx, roomID, profileID, isReady)
}

// Stats mocks base method.
func (m *MockMemberRepo) Stats(ctx context.Context, profileID int64) (model.ProfileStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx, profileID)
	ret0, _ := ret[0].(model.ProfileStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockMemberRepoMockRecorder) Stats(ctx, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockMemberRepo)(nil).Stats), ctx, profileID)
}

// TouchWaiting mocks base method.
func (m *MockMemberRepo) TouchWaiting(ctx context.Context, roomID, profileID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchWaiting", ctx, roomID, profileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchWaiting indicates an expected call of TouchWaiting.
func (mr *MockMemberRepoMockRecorder) TouchWaiting(ctx, roomID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchWaiting", reflect.TypeOf((*MockMemberRepo)(nil).TouchWaiting), ctx, roomID, profileID)
}

// MockRoomQuestionRepo is a mock of RoomQuestionRepo interface.
type MockRoomQuestionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRoomQuestionRepoMockRecorder
}

// MockRoomQuestionRepoMockRecorder is the mock recorder for MockRoomQuestionRepo.
type MockRoomQuestionRepoMockRecorder struct {
	mock *MockRoomQuestionRepo
}

// NewMockRoomQuestionRepo creates a new mock instance.
func NewMockRoomQuestionRepo(ctrl *gomock.Controller) *MockRoomQuestionRepo {
	mock := &MockRoomQuestionRepo{ctrl: ctrl}
	mock.recorder = &MockRoomQuestionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomQuestionRepo) EXPECT() *MockRoomQuestionRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRoomQuestionRepo) Add(ctx context.Context, roomID, questionID int64, position int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, roomID, questionID, position)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockRoomQuestionRepoMockRecorder) Add(ctx, roomID, questionID, position interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRoomQuestionRepo)(nil).Add), ctx, roomID, questionID, position)
}

// Clear mocks base method.
func (m *MockRoomQuestionRepo) Clear(ctx context.Context, roomID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockRoomQuestionRepoMockRecorder) Clear(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockRoomQuestionRepo)(nil).Clear), ctx, roomID)
}

// GetActive mocks base method.
func (m *MockRoomQuestionRepo) GetActive(ctx context.Context, roomID int64) (*model.RoomQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx, roomID)
	ret0, _ := ret[0].(*model.RoomQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockRoomQuestionRepoMockRecorder) GetActive(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockRoomQuestionRepo)(nil).GetActive), ctx, roomID)
}

// GetByPosition mocks base method.
func (m *MockRoomQuestionRepo) GetByPosition(ctx context.Context, roomID int64, position int) (*model.RoomQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPosition", ctx, roomID, position)
	ret0, _ := ret[0].(*model.RoomQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPosition indicates an expected call of GetByPosition.
func (mr *MockRoomQuestionRepoMockRecorder) GetByPosition(ctx, roomID, position interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPosition", reflect.TypeOf((*MockRoomQuestionRepo)(nil).GetByPosition), ctx, roomID, position)
}

// List mocks base method.
func (m *MockRoomQuestionRepo) List(ctx context.Context, roomID int64) ([]model.RoomQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, roomID)
	ret0, _ := ret[0].([]model.RoomQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRoomQuestionRepoMockRecorder) List(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoomQuestionRepo)(nil).List), ctx, roomID)
}

// Update mocks base method.
func (m *MockRoomQuestionRepo) Update(ctx context.Context, rq *model.RoomQuestion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rq)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoomQuestionRepoMockRecorder) Update(ctx, rq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoomQuestionRepo)(nil).Update), ctx, rq)
}

// MockAnswerRepo is a mock of AnswerRepo interface.
type MockAnswerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAnswerRepoMockRecorder
}

// MockAnswerRepoMockRecorder is the mock recorder for MockAnswerRepo.
type MockAnswerRepoMockRecorder struct {
	mock *MockAnswerRepo
}

// NewMockAnswerRepo creates a new mock instance.
func NewMockAnswerRepo(ctrl *gomock.Controller) *MockAnswerRepo {
	mock := &MockAnswerRepo{ctrl: ctrl}
	mock.recorder = &MockAnswerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnswerRepo) EXPECT() *MockAnswerRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockAnswerRepo) Add(ctx context.Context, answer *model.Answer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, answer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockAnswerRepoMockRecorder) Add(ctx, answer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockAnswerRepo)(nil).Add), ctx, answer)
}

// Count mocks base method.
func (m *MockAnswerRepo) Count(ctx context.Context, roomQuestionID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, roomQuestionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockAnswerRepoMockRecorder) Count(ctx, roomQuestionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockAnswerRepo)(nil).Count), ctx, roomQuestionID)
}

// List mocks base method.
func (m *MockAnswerRepo) List(ctx context.Context, roomQuestionID int64) ([]model.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, roomQuestionID)
	ret0, _ := ret[0].([]model.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAnswerRepoMockRecorder) List(ctx, roomQuestionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAnswerRepo)(nil).List), ctx, roomQuestionID)
}

// MockMessageRepo is a mock of MessageRepo interface.
type MockMessageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepoMockRecorder
}

// MockMessageRepoMockRecorder is the mock recorder for MockMessageRepo.
type MockMessageRepoMockRecorder struct {
	mock *MockMessageRepo
}

// NewMockMessageRepo creates a new mock instance.
func NewMockMessageRepo(ctrl *gomock.Controller) *MockMessageRepo {
	mock := &MockMessageRepo{ctrl: ctrl}
	mock.recorder = &MockMessageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepo) EXPECT() *MockMessageRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockMessageRepo) Add(ctx context.Context, message *model.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockMessageRepoMockRecorder) Add(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockMessageRepo)(nil).Add), ctx, message)
}

// List mocks base method.
func (m *MockMessageRepo) List(ctx context.Context, roomID int64, limit, offset int) ([]model.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, roomID, limit, offset)
	ret0, _ := ret[0].([]model.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMessageRepoMockRecorder) List(ctx, roomID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMessageRepo)(nil).List), ctx, roomID, limit, offset)
}

// MockRatingRepo is a mock of RatingRepo interface.
type MockRatingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRatingRepoMockRecorder
}

// MockRatingRepoMockRecorder is the mock recorder for MockRatingRepo.
type MockRatingRepoMockRecorder struct {
	mock *MockRatingRepo
}

// NewMockRatingRepo creates a new mock instance.
func NewMockRatingRepo(ctrl *gomock.Controller) *MockRatingRepo {
	mock := &MockRatingRepo{ctrl: ctrl}
	mock.recorder = &MockRatingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingRepo) EXPECT() *MockRatingRepoMockRecorder {
	return m.recorder
}

// AddMatch mocks base method.
func (m *MockRatingRepo) AddMatch(ctx context.Context, match *model.RatingMatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMatch", ctx, match)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMatch indicates an expected call of AddMatch.
func (mr *MockRatingRepoMockRecorder) AddMatch(ctx, match interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMatch", reflect.TypeOf((*MockRatingRepo)(nil).AddMatch), ctx, match)
}

// AddMatchPlayer mocks base method.
func (m *MockRatingRepo) AddMatchPlayer(ctx context.Context, player *model.RatingMatchPlayer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMatchPlayer", ctx, player)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMatchPlayer indicates an expected call of AddMatchPlayer.
func (mr *MockRatingRepoMockRecorder) AddMatchPlayer(ctx, player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMatchPlayer", reflect.TypeOf((*MockRatingRepo)(nil).AddMatchPlayer), ctx, player)
}

// ApplyPlayerRatingChange mocks base method.
func (m *MockRatingRepo) ApplyPlayerRatingChange(ctx context.Context, seasonID, profileID int64, delta int, isWin, isDraw bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyPlayerRatingChange", ctx, seasonID, profileID, delta, isWin, isDraw)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyPlayerRatingChange indicates an expected call of ApplyPlayerRatingChange.
func (mr *MockRatingRepoMockRecorder) ApplyPlayerRatingChange(ctx, seasonID, profileID, delta, isWin, isDraw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyPlayerRatingChange", reflect.TypeOf((*MockRatingRepo)(nil).ApplyPlayerRatingChange), ctx, seasonID, profileID, delta, isWin, isDraw)
}

// CountMatchesForGroup mocks base method.
func (m *MockRatingRepo) CountMatchesForGroup(ctx context.Context, gameType, groupHash string, from, to time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMatchesForGroup", ctx, gameType, groupHash, from, to)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMatchesForGroup indicates an expected call of CountMatchesForGroup.
func (mr *MockRatingRepoMockRecorder) CountMatchesForGroup(ctx, gameType, groupHash, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMatchesForGroup", reflect.TypeOf((*MockRatingRepo)(nil).CountMatchesForGroup), ctx, gameType, groupHash, from, to)
}

// EnsurePlayerRatings mocks base method.
func (m *MockRatingRepo) EnsurePlayerRatings(ctx context.Context, seasonID int64, gameType string, profileIDs []int64) ([]model.PlayerRating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsurePlayerRatings", ctx, seasonID, gameType, profileIDs)
	ret0, _ := ret[0].([]model.PlayerRating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsurePlayerRatings indicates an expected call of EnsurePlayerRatings.
func (mr *MockRatingRepoMockRecorder) EnsurePlayerRatings(ctx, seasonID, gameType, profileIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsurePlayerRatings", reflect.TypeOf((*MockRatingRepo)(nil).EnsurePlayerRatings), ctx, seasonID, gameType, profileIDs)
}

// EnsureSeason mocks base method.
func (m *MockRatingRepo) EnsureSeason(ctx context.Context, season *model.RatingSeason) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureSeason", ctx, season)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureSeason indicates an expected call of EnsureSeason.
func (mr *MockRatingRepoMockRecorder) EnsureSeason(ctx, season interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureSeason", reflect.TypeOf((*MockRatingRepo)(nil).EnsureSeason), ctx, season)
}

// Leaderboard mocks base method.
func (m *MockRatingRepo) Leaderboard(ctx context.Context, seasonID int64, limit, offset int) ([]model.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leaderboard", ctx, seasonID, limit, offset)
	ret0, _ := ret[0].([]model.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Leaderboard indicates an expected call of Leaderboard.
func (mr *MockRatingRepoMockRecorder) Leaderboard(ctx, seasonID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leaderboard", reflect.TypeOf((*MockRatingRepo)(nil).Leaderboard), ctx, seasonID, limit, offset)
}

// RatingChangesForRoom mocks base method.
func (m *MockRatingRepo) RatingChangesForRoom(ctx context.Context, roomID int64) ([]model.RatingChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RatingChangesForRoom", ctx, roomID)
	ret0, _ := ret[0].([]model.RatingChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RatingChangesForRoom indicates an expected call of RatingChangesForRoom.
func (mr *MockRatingRepoMockRecorder) RatingChangesForRoom(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RatingChangesForRoom", reflect.TypeOf((*MockRatingRepo)(nil).RatingChangesForRoom), ctx, roomID)
}
