// Code generated by MockGen. DO NOT EDIT.
// Source: services/chat/internal/handler/http/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/go-park-mail-ru/2026_1_ARIS/services/chat/internal/usecase"
	gomock "github.com/golang/mock/gomock"
)

// MockChatService is a mock of ChatService interface.
type MockChatService struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceMockRecorder
}

// MockChatServiceMockRecorder is the mock recorder for MockChatService.
type MockChatServiceMockRecorder struct {
	mock *MockChatService
}

// NewMockChatService creates a new mock instance.
func NewMockChatService(ctrl *gomock.Controller) *MockChatService {
	mock := &MockChatService{ctrl: ctrl}
	mock.recorder = &MockChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatService) EXPECT() *MockChatServiceMockRecorder {
	return m.recorder
}

// CheckUserInChat mocks base method.
func (m *MockChatService) CheckUserInChat(arg0 context.Context, arg1, arg2 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserInChat", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserInChat indicates an expected call of CheckUserInChat.
func (mr *MockChatServiceMockRecorder) CheckUserInChat(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserInChat", reflect.TypeOf((*MockChatService)(nil).CheckUserInChat), arg0, arg1, arg2)
}

// CreatePrivateChat mocks base method.
func (m *MockChatService) CreatePrivateChat(arg0 context.Context, arg1, arg2 int64) (usecase.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateChat", arg0, arg1, arg2)
	ret0, _ := ret[0].(usecase.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrivateChat indicates an expected call of CreatePrivateChat.
func (mr *MockChatServiceMockRecorder) CreatePrivateChat(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateChat", reflect.TypeOf((*MockChatService)(nil).CreatePrivateChat), arg0, arg1, arg2)
}

// CreateSticker mocks base method.
func (m *MockChatService) CreateSticker(arg0 context.Context, arg1, arg2 int64, arg3 usecase.StickerInput) (usecase.Sticker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSticker", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(usecase.Sticker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSticker indicates an expected call of CreateSticker.
func (mr *MockChatServiceMockRecorder) CreateSticker(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSticker", reflect.TypeOf((*MockChatService)(nil).CreateSticker), arg0, arg1, arg2, arg3)
}

// CreateStickerPack mocks base method.
func (m *MockChatService) CreateStickerPack(arg0 context.Context, arg1 int64, arg2 usecase.StickerPackInput) (usecase.StickerPack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStickerPack", arg0, arg1, arg2)
	ret0, _ := ret[0].(usecase.StickerPack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStickerPack indicates an expected call of CreateStickerPack.
func (mr *MockChatServiceMockRecorder) CreateStickerPack(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStickerPack", reflect.TypeOf((*MockChatService)(nil).CreateStickerPack), arg0, arg1, arg2)
}

// DeleteMessageReaction mocks base method.
func (m *MockChatService) DeleteMessageReaction(arg0 context.Context, arg1, arg2, arg3 int64) (usecase.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessageReaction", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(usecase.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMessageReaction indicates an expected call of DeleteMessageReaction.
func (mr *MockChatServiceMockRecorder) DeleteMessageReaction(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessageReaction", reflect.TypeOf((*MockChatService)(nil).DeleteMessageReaction), arg0, arg1, arg2, arg3)
}

// ForcePresenceOffline mocks base method.
func (m *MockChatService) ForcePresenceOffline(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForcePresenceOffline", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForcePresenceOffline indicates an expected call of ForcePresenceOffline.
func (mr *MockChatServiceMockRecorder) ForcePresenceOffline(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForcePresenceOffline", reflect.TypeOf((*MockChatService)(nil).ForcePresenceOffline), arg0, arg1)
}

// GetMessages mocks base method.
func (m *MockChatService) GetMessages(arg0 context.Context, arg1, arg2 int64, arg3, arg4 int) ([]usecase.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]usecase.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockChatServiceMockRecorder) GetMessages(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockChatService)(nil).GetMessages), arg0, arg1, arg2, arg3, arg4)
}

// GetMessagesAfter mocks base method.
func (m *MockChatService) GetMessagesAfter(arg0 context.Context, arg1, arg2, arg3 int64, arg4 int) ([]usecase.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesAfter", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]usecase.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesAfter indicates an expected call of GetMessagesAfter.
func (mr *MockChatServiceMockRecorder) GetMessagesAfter(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesAfter", reflect.TypeOf((*MockChatService)(nil).GetMessagesAfter), arg0, arg1, arg2, arg3, arg4)
}

// GetStickerPacks mocks base method.
func (m *MockChatService) GetStickerPacks(arg0 context.Context, arg1 int64, arg2 string, arg3 bool, arg4, arg5 int) ([]usecase.StickerPack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStickerPacks", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]usecase.StickerPack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStickerPacks indicates an expected call of GetStickerPacks.
func (mr *MockChatServiceMockRecorder) GetStickerPacks(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStickerPacks", reflect.TypeOf((*MockChatService)(nil).GetStickerPacks), arg0, arg1, arg2, arg3, arg4, arg5)
}

// GetStickersByPack mocks base method.
func (m *MockChatService) GetStickersByPack(arg0 context.Context, arg1, arg2 int64, arg3, arg4 int) ([]usecase.Sticker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStickersByPack", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]usecase.Sticker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStickersByPack indicates an expected call of GetStickersByPack.
func (mr *MockChatServiceMockRecorder) GetStickersByPack(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStickersByPack", reflect.TypeOf((*MockChatService)(nil).GetStickersByPack), arg0, arg1, arg2, arg3, arg4)
}

// GetUserChats mocks base method.
func (m *MockChatService) GetUserChats(arg0 context.Context, arg1 int64) ([]usecase.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserChats", arg0, arg1)
	ret0, _ := ret[0].([]usecase.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserChats indicates an expected call of GetUserChats.
func (mr *MockChatServiceMockRecorder) GetUserChats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserChats", reflect.TypeOf((*MockChatService)(nil).GetUserChats), arg0, arg1)
}

// HeartbeatPresence mocks base method.
func (m *MockChatService) HeartbeatPresence(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeartbeatPresence", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HeartbeatPresence indicates an expected call of HeartbeatPresence.
func (mr *MockChatServiceMockRecorder) HeartbeatPresence(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeartbeatPresence", reflect.TypeOf((*MockChatService)(nil).HeartbeatPresence), arg0, arg1)
}

// SendMessage mocks base method.
func (m *MockChatService) SendMessage(arg0 context.Context, arg1, arg2 int64, arg3 usecase.MessageInput) (usecase.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(usecase.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockChatServiceMockRecorder) SendMessage(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockChatService)(nil).SendMessage), arg0, arg1, arg2, arg3)
}

// SetMessageReaction mocks base method.
func (m *MockChatService) SetMessageReaction(arg0 context.Context, arg1, arg2, arg3 int64, arg4 string) (usecase.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMessageReaction", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(usecase.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMessageReaction indicates an expected call of SetMessageReaction.
func (mr *MockChatServiceMockRecorder) SetMessageReaction(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessageReaction", reflect.TypeOf((*MockChatService)(nil).SetMessageReaction), arg0, arg1, arg2, arg3, arg4)
}

// SetPresenceOffline mocks base method.
func (m *MockChatService) SetPresenceOffline(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPresenceOffline", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPresenceOffline indicates an expected call of SetPresenceOffline.
func (mr *MockChatServiceMockRecorder) SetPresenceOffline(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPresenceOffline", reflect.TypeOf((*MockChatService)(nil).SetPresenceOffline), arg0, arg1)
}

// SetPresenceOnline mocks base method.
func (m *MockChatService) SetPresenceOnline(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPresenceOnline", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPresenceOnline indicates an expected call of SetPresenceOnline.
func (mr *MockChatServiceMockRecorder) SetPresenceOnline(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPresenceOnline", reflect.TypeOf((*MockChatService)(nil).SetPresenceOnline), arg0, arg1)
}

// UpdateMessage mocks base method.
func (m *MockChatService) UpdateMessage(arg0 context.Context, arg1, arg2, arg3 int64, arg4 string) (usecase.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessage", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(usecase.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMessage indicates an expected call of UpdateMessage.
func (mr *MockChatServiceMockRecorder) UpdateMessage(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessage", reflect.TypeOf((*MockChatService)(nil).UpdateMessage), arg0, arg1, arg2, arg3, arg4)
}
