// Code generated by MockGen. DO NOT EDIT.
// Source: internal/search/repository/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	repository "github.com/go-park-mail-ru/2026_1_ARIS/internal/search/repository"
	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
)

// MockSearchRepo is a mock of SearchRepo interface.
type MockSearchRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRepoMockRecorder
}

// MockSearchRepoMockRecorder is the mock recorder for MockSearchRepo.
type MockSearchRepoMockRecorder struct {
	mock *MockSearchRepo
}

// NewMockSearchRepo creates a new mock instance.
func NewMockSearchRepo(ctrl *gomock.Controller) *MockSearchRepo {
	mock := &MockSearchRepo{ctrl: ctrl}
	mock.recorder = &MockSearchRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRepo) EXPECT() *MockSearchRepoMockRecorder {
	return m.recorder
}

// SearchCommunities mocks base method.
func (m *MockSearchRepo) SearchCommunities(ctx context.Context, query string, limit int) ([]repository.CommunityResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCommunities", ctx, query, limit)
	ret0, _ := ret[0].([]repository.CommunityResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCommunities indicates an expected call of SearchCommunities.
func (mr *MockSearchRepoMockRecorder) SearchCommunities(ctx, query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCommunities", reflect.TypeOf((*MockSearchRepo)(nil).SearchCommunities), ctx, query, limit)
}

// SearchUsers mocks base method.
func (m *MockSearchRepo) SearchUsers(ctx context.Context, query string, limit int) ([]repository.UserResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", ctx, query, limit)
	ret0, _ := ret[0].([]repository.UserResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockSearchRepoMockRecorder) SearchUsers(ctx, query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockSearchRepo)(nil).SearchUsers), ctx, query, limit)
}

// MocksearchDB is a mock of searchDB interface.
type MocksearchDB struct {
	ctrl     *gomock.Controller
	recorder *MocksearchDBMockRecorder
}

// MocksearchDBMockRecorder is the mock recorder for MocksearchDB.
type MocksearchDBMockRecorder struct {
	mock *MocksearchDB
}

// NewMocksearchDB creates a new mock instance.
func NewMocksearchDB(ctrl *gomock.Controller) *MocksearchDB {
	mock := &MocksearchDB{ctrl: ctrl}
	mock.recorder = &MocksearchDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksearchDB) EXPECT() *MocksearchDBMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MocksearchDB) Query(arg0 context.Context, arg1 string, arg2 ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MocksearchDBMockRecorder) Query(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MocksearchDB)(nil).Query), varargs...)
}
