// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/like/like.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_ARIS/internal/models"
	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
)

// MockLikeRepo is a mock of LikeRepo interface.
type MockLikeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLikeRepoMockRecorder
}

// MockLikeRepoMockRecorder is the mock recorder for MockLikeRepo.
type MockLikeRepoMockRecorder struct {
	mock *MockLikeRepo
}

// NewMockLikeRepo creates a new mock instance.
func NewMockLikeRepo(ctrl *gomock.Controller) *MockLikeRepo {
	mock := &MockLikeRepo{ctrl: ctrl}
	mock.recorder = &MockLikeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeRepo) EXPECT() *MockLikeRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLikeRepo) Get(ctx context.Context, likeID int64) (*models.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, likeID)
	ret0, _ := ret[0].(*models.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLikeRepoMockRecorder) Get(ctx, likeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLikeRepo)(nil).Get), ctx, likeID)
}

// GetLikeCountOnPost mocks base method.
func (m *MockLikeRepo) GetLikeCountOnPost(ctx context.Context, postID int64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikeCountOnPost", ctx, postID)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetLikeCountOnPost indicates an expected call of GetLikeCountOnPost.
func (mr *MockLikeRepoMockRecorder) GetLikeCountOnPost(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikeCountOnPost", reflect.TypeOf((*MockLikeRepo)(nil).GetLikeCountOnPost), ctx, postID)
}

// GetPostLikeByAuthor mocks base method.
func (m *MockLikeRepo) GetPostLikeByAuthor(ctx context.Context, postID, authorID int64) (*models.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostLikeByAuthor", ctx, postID, authorID)
	ret0, _ := ret[0].(*models.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostLikeByAuthor indicates an expected call of GetPostLikeByAuthor.
func (mr *MockLikeRepoMockRecorder) GetPostLikeByAuthor(ctx, postID, authorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostLikeByAuthor", reflect.TypeOf((*MockLikeRepo)(nil).GetPostLikeByAuthor), ctx, postID, authorID)
}

// HasActivePostLike mocks base method.
func (m *MockLikeRepo) HasActivePostLike(ctx context.Context, postID, authorID int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActivePostLike", ctx, postID, authorID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasActivePostLike indicates an expected call of HasActivePostLike.
func (mr *MockLikeRepoMockRecorder) HasActivePostLike(ctx, postID, authorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActivePostLike", reflect.TypeOf((*MockLikeRepo)(nil).HasActivePostLike), ctx, postID, authorID)
}

// Save mocks base method.
func (m *MockLikeRepo) Save(ctx context.Context, like models.Like) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, like)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockLikeRepoMockRecorder) Save(ctx, like interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLikeRepo)(nil).Save), ctx, like)
}

// SetActive mocks base method.
func (m *MockLikeRepo) SetActive(ctx context.Context, likeID int64, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, likeID, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockLikeRepoMockRecorder) SetActive(ctx, likeID, active interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockLikeRepo)(nil).SetActive), ctx, likeID, active)
}

// MocklikeDB is a mock of likeDB interface.
type MocklikeDB struct {
	ctrl     *gomock.Controller
	recorder *MocklikeDBMockRecorder
}

// MocklikeDBMockRecorder is the mock recorder for MocklikeDB.
type MocklikeDBMockRecorder struct {
	mock *MocklikeDB
}

// NewMocklikeDB creates a new mock instance.
func NewMocklikeDB(ctrl *gomock.Controller) *MocklikeDB {
	mock := &MocklikeDB{ctrl: ctrl}
	mock.recorder = &MocklikeDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklikeDB) EXPECT() *MocklikeDBMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MocklikeDB) Exec(arg0 context.Context, arg1 string, arg2 ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MocklikeDBMockRecorder) Exec(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MocklikeDB)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MocklikeDB) Query(arg0 context.Context, arg1 string, arg2 ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MocklikeDBMockRecorder) Query(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MocklikeDB)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MocklikeDB) QueryRow(arg0 context.Context, arg1 string, arg2 ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MocklikeDBMockRecorder) QueryRow(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MocklikeDB)(nil).QueryRow), varargs...)
}
