// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/media/media.proto

package mediapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMediaURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaURLRequest) Reset() {
	*x = GetMediaURLRequest{}
	mi := &file_proto_media_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaURLRequest) ProtoMessage() {}

func (x *GetMediaURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaURLRequest.ProtoReflect.Descriptor instead.
func (*GetMediaURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{0}
}

func (x *GetMediaURLRequest) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type GetMediaURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaURLResponse) Reset() {
	*x = GetMediaURLResponse{}
	mi := &file_proto_media_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaURLResponse) ProtoMessage() {}

func (x *GetMediaURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaURLResponse.ProtoReflect.Descriptor instead.
func (*GetMediaURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{1}
}

func (x *GetMediaURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_proto_media_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{2}
}

func (x *GetMediaRequest) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type GetMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	mi := &file_proto_media_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{3}
}

func (x *GetMediaResponse) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *GetMediaResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetMediaResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetMediaResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_media_media_proto protoreflect.FileDescriptor

const file_proto_media_media_proto_rawDesc = "" +
	"\n" +
	"\x17proto/media/media.proto\x12\raris.media.v1\"/\n" +
	"\x12GetMediaURLRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x03R\amediaId\"'\n" +
	"\x13GetMediaURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\",\n" +
	"\x0fGetMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x03R\amediaId\"n\n" +
	"\x10GetMediaResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x03R\amediaId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url2\xb1\x01\n" +
	"\fMediaService\x12T\n" +
	"\vGetMediaURL\x12!.aris.media.v1.GetMediaURLRequest\x1a\".aris.media.v1.GetMediaURLResponse\x12K\n" +
	"\bGetMedia\x12\x1e.aris.media.v1.GetMediaRequest\x1a\x1f.aris.media.v1.GetMediaResponseB<Z:github.com/go-park-mail-ru/2026_1_ARIS/proto/media;mediapbb\x06proto3"

var (
	file_proto_media_media_proto_rawDescOnce sync.Once
	file_proto_media_media_proto_rawDescData []byte
)

func file_proto_media_media_proto_rawDescGZIP() []byte {
	file_proto_media_media_proto_rawDescOnce.Do(func() {
		file_proto_media_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_media_media_proto_rawDesc), len(file_proto_media_media_proto_rawDesc)))
	})
	return file_proto_media_media_proto_rawDescData
}

var file_proto_media_media_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_media_media_proto_goTypes = []any{
	(*GetMediaURLRequest)(nil),  // 0: aris.media.v1.GetMediaURLRequest
	(*GetMediaURLResponse)(nil), // 1: aris.media.v1.GetMediaURLResponse
	(*GetMediaRequest)(nil),     // 2: aris.media.v1.GetMediaRequest
	(*GetMediaResponse)(nil),    // 3: aris.media.v1.GetMediaResponse
}
var file_proto_media_media_proto_depIdxs = []int32{
	0, // 0: aris.media.v1.MediaService.GetMediaURL:input_type -> aris.media.v1.GetMediaURLRequest
	2, // 1: aris.media.v1.MediaService.GetMedia:input_type -> aris.media.v1.GetMediaRequest
	1, // 2: aris.media.v1.MediaService.GetMediaURL:output_type -> aris.media.v1.GetMediaURLResponse
	3, // 3: aris.media.v1.MediaService.GetMedia:output_type -> aris.media.v1.GetMediaResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_media_media_proto_init() }
func file_proto_media_media_proto_init() {
	if File_proto_media_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_media_media_proto_rawDesc), len(file_proto_media_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_media_media_proto_goTypes,
		DependencyIndexes: file_proto_media_media_proto_depIdxs,
		MessageInfos:      file_proto_media_media_proto_msgTypes,
	}.Build()
	File_proto_media_media_proto = out.File
	file_proto_media_media_proto_goTypes = nil
	file_proto_media_media_proto_depIdxs = nil
}
