// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/community/community.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_ARIS/internal/models"
	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
)

// MockCommunityRepo is a mock of CommunityRepo interface.
type MockCommunityRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCommunityRepoMockRecorder
}

// MockCommunityRepoMockRecorder is the mock recorder for MockCommunityRepo.
type MockCommunityRepoMockRecorder struct {
	mock *MockCommunityRepo
}

// NewMockCommunityRepo creates a new mock instance.
func NewMockCommunityRepo(ctrl *gomock.Controller) *MockCommunityRepo {
	mock := &MockCommunityRepo{ctrl: ctrl}
	mock.recorder = &MockCommunityRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommunityRepo) EXPECT() *MockCommunityRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommunityRepo) Create(ctx context.Context, community models.Community, ownerProfileID int64, avatarID *int64) (*models.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, community, ownerProfileID, avatarID)
	ret0, _ := ret[0].(*models.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommunityRepoMockRecorder) Create(ctx, community, ownerProfileID, avatarID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommunityRepo)(nil).Create), ctx, community, ownerProfileID, avatarID)
}

// DeactivateMember mocks base method.
func (m *MockCommunityRepo) DeactivateMember(ctx context.Context, communityID, profileID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateMember", ctx, communityID, profileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateMember indicates an expected call of DeactivateMember.
func (mr *MockCommunityRepoMockRecorder) DeactivateMember(ctx, communityID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateMember", reflect.TypeOf((*MockCommunityRepo)(nil).DeactivateMember), ctx, communityID, profileID)
}

// Delete mocks base method.
func (m *MockCommunityRepo) Delete(ctx context.Context, communityID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, communityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommunityRepoMockRecorder) Delete(ctx, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommunityRepo)(nil).Delete), ctx, communityID)
}

// Get mocks base method.
func (m *MockCommunityRepo) Get(ctx context.Context, communityID int64) (*models.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, communityID)
	ret0, _ := ret[0].(*models.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCommunityRepoMockRecorder) Get(ctx, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCommunityRepo)(nil).Get), ctx, communityID)
}

// GetAvatarID mocks base method.
func (m *MockCommunityRepo) GetAvatarID(ctx context.Context, communityProfileID int64) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarID", ctx, communityProfileID)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarID indicates an expected call of GetAvatarID.
func (mr *MockCommunityRepoMockRecorder) GetAvatarID(ctx, communityProfileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarID", reflect.TypeOf((*MockCommunityRepo)(nil).GetAvatarID), ctx, communityProfileID)
}

// GetByProfileID mocks base method.
func (m *MockCommunityRepo) GetByProfileID(ctx context.Context, profileID int64) (*models.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProfileID", ctx, profileID)
	ret0, _ := ret[0].(*models.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProfileID indicates an expected call of GetByProfileID.
func (mr *MockCommunityRepoMockRecorder) GetByProfileID(ctx, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProfileID", reflect.TypeOf((*MockCommunityRepo)(nil).GetByProfileID), ctx, profileID)
}

// GetMember mocks base method.
func (m *MockCommunityRepo) GetMember(ctx context.Context, communityID, profileID int64) (*models.CommunityMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMember", ctx, communityID, profileID)
	ret0, _ := ret[0].(*models.CommunityMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMember indicates an expected call of GetMember.
func (mr *MockCommunityRepoMockRecorder) GetMember(ctx, communityID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMember", reflect.TypeOf((*MockCommunityRepo)(nil).GetMember), ctx, communityID, profileID)
}

// List mocks base method.
func (m *MockCommunityRepo) List(ctx context.Context, limit, offset int) ([]models.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]models.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCommunityRepoMockRecorder) List(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCommunityRepo)(nil).List), ctx, limit, offset)
}

// ListMembers mocks base method.
func (m *MockCommunityRepo) ListMembers(ctx context.Context, communityID int64, includeBlocked bool) ([]models.CommunityMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, communityID, includeBlocked)
	ret0, _ := ret[0].([]models.CommunityMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockCommunityRepoMockRecorder) ListMembers(ctx, communityID, includeBlocked interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockCommunityRepo)(nil).ListMembers), ctx, communityID, includeBlocked)
}

// Update mocks base method.
func (m *MockCommunityRepo) Update(ctx context.Context, community models.Community) (*models.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, community)
	ret0, _ := ret[0].(*models.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCommunityRepoMockRecorder) Update(ctx, community interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommunityRepo)(nil).Update), ctx, community)
}

// UpdateAvatar mocks base method.
func (m *MockCommunityRepo) UpdateAvatar(ctx context.Context, communityProfileID int64, avatarID *int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, communityProfileID, avatarID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockCommunityRepoMockRecorder) UpdateAvatar(ctx, communityProfileID, avatarID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockCommunityRepo)(nil).UpdateAvatar), ctx, communityProfileID, avatarID)
}

// UpsertMemberRole mocks base method.
func (m *MockCommunityRepo) UpsertMemberRole(ctx context.Context, communityID, profileID int64, role models.CommunityMemberRole) (*models.CommunityMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertMemberRole", ctx, communityID, profileID, role)
	ret0, _ := ret[0].(*models.CommunityMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertMemberRole indicates an expected call of UpsertMemberRole.
func (mr *MockCommunityRepoMockRecorder) UpsertMemberRole(ctx, communityID, profileID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertMemberRole", reflect.TypeOf((*MockCommunityRepo)(nil).UpsertMemberRole), ctx, communityID, profileID, role)
}

// MockcommunityDB is a mock of communityDB interface.
type MockcommunityDB struct {
	ctrl     *gomock.Controller
	recorder *MockcommunityDBMockRecorder
}

// MockcommunityDBMockRecorder is the mock recorder for MockcommunityDB.
type MockcommunityDBMockRecorder struct {
	mock *MockcommunityDB
}

// NewMockcommunityDB creates a new mock instance.
func NewMockcommunityDB(ctrl *gomock.Controller) *MockcommunityDB {
	mock := &MockcommunityDB{ctrl: ctrl}
	mock.recorder = &MockcommunityDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcommunityDB) EXPECT() *MockcommunityDBMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockcommunityDB) Begin(arg0 context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", arg0)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockcommunityDBMockRecorder) Begin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockcommunityDB)(nil).Begin), arg0)
}

// Exec mocks base method.
func (m *MockcommunityDB) Exec(arg0 context.Context, arg1 string, arg2 ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockcommunityDBMockRecorder) Exec(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockcommunityDB)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockcommunityDB) Query(arg0 context.Context, arg1 string, arg2 ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockcommunityDBMockRecorder) Query(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockcommunityDB)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockcommunityDB) QueryRow(arg0 context.Context, arg1 string, arg2 ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockcommunityDBMockRecorder) QueryRow(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockcommunityDB)(nil).QueryRow), varargs...)
}
