#!/usr/bin/env sh
set -eu

: "${DB_USER:?DB_USER is required}"
: "${DB_PASSWORD:?DB_PASSWORD is required}"
: "${DB_NAME:?DB_NAME is required}"
: "${MINIO_BUCKET_NAME:?MINIO_BUCKET_NAME is required}"
: "${MINIO_ROOT_USER:?MINIO_ROOT_USER is required}"
: "${MINIO_ROOT_PASSWORD:?MINIO_ROOT_PASSWORD is required}"

SSL_MODE="${SSL_MODE:-disable}"
POOL_MAX_CONNS="${POOL_MAX_CONNS:-10}"
POOL_MAX_CONN_LIFETIME="${POOL_MAX_CONN_LIFETIME:-1h}"
POOL_MAX_CONN_IDLE_TIME="${POOL_MAX_CONN_IDLE_TIME:-30m}"
REDIS_DB="${REDIS_DB:-0}"
REDIS_MAX_RETRIES="${REDIS_MAX_RETRIES:-3}"
REDIS_DIAL_TIMEOUT="${REDIS_DIAL_TIMEOUT:-3s}"
REDIS_TIMEOUT="${REDIS_TIMEOUT:-3s}"
TARANTOOL_USER="${TARANTOOL_USER:-cache}"
TARANTOOL_DIAL_TIMEOUT="${TARANTOOL_DIAL_TIMEOUT:-3s}"
TARANTOOL_TIMEOUT="${TARANTOOL_TIMEOUT:-500ms}"
TARANTOOL_RECONNECT_TIMEOUT="${TARANTOOL_RECONNECT_TIMEOUT:-1s}"
TARANTOOL_MAX_RECONNECTS="${TARANTOOL_MAX_RECONNECTS:-3}"
MINIO_USE_SSL="${MINIO_USE_SSL:-false}"
CLICKHOUSE_DB="${CLICKHOUSE_DB:-aris}"
CLICKHOUSE_USER="${CLICKHOUSE_USER:-default}"
CLICKHOUSE_PASSWORD="${CLICKHOUSE_PASSWORD:-}"
CLICKHOUSE_ASYNC_INSERT="${CLICKHOUSE_ASYNC_INSERT:-1}"
CLICKHOUSE_WAIT_FOR_ASYNC_INSERT="${CLICKHOUSE_WAIT_FOR_ASYNC_INSERT:-0}"
CLICKHOUSE_MAX_INSERT_BLOCK_SIZE="${CLICKHOUSE_MAX_INSERT_BLOCK_SIZE:-100000}"
APP_ENDPOINT="${APP_ENDPOINT:-https://arisnet.ru}"
APP_ENDPOINT="${APP_ENDPOINT%/}"
VKID_REDIRECT_URI="${VKID_REDIRECT_URI:-$APP_ENDPOINT/api/auth/vkid/callback}"
case "$APP_ENDPOINT" in
  ""|http://localhost:*|http://127.0.0.1:*|http://host.docker.internal:*)
    REDIS_USER_PASSWORD="${REDIS_USER_PASSWORD:-local-redis-password}"
    TARANTOOL_PASSWORD="${TARANTOOL_PASSWORD:-local-tarantool-password}"
    ;;
  *)
    : "${REDIS_USER_PASSWORD:?REDIS_USER_PASSWORD is required}"
    : "${TARANTOOL_PASSWORD:?TARANTOOL_PASSWORD is required}"
    ;;
esac

write_env() {
  file="$1"
  shift

  mkdir -p "$(dirname "$file")"
  umask 077
  : > "$file"

  while [ "$#" -gt 0 ]; do
    key="$1"
    value="$2"
    shift 2

    if [ "$key" = "" ]; then
      printf '\n' >> "$file"
    else
      printf '%s=%s\n' "$key" "$value" >> "$file"
    fi
  done
}

write_env services/auth/.env \
  APP_ENDPOINT "$APP_ENDPOINT" \
  AUTH_GRPC_PORT "${AUTH_GRPC_PORT:-8002}" \
  AUTH_HTTP_PORT "${AUTH_HTTP_PORT:-8085}" \
  "" "" \
  LOGGER_LEVEL "${LOGGER_LEVEL:-info}" \
  "" "" \
  REDIS_ADDR redis:6379 \
  REDIS_HOST redis \
  REDIS_PORT 6379 \
  REDIS_DB "$REDIS_DB" \
  REDIS_USER_PASSWORD "$REDIS_USER_PASSWORD" \
  REDIS_MAX_RETRIES "$REDIS_MAX_RETRIES" \
  REDIS_DIAL_TIMEOUT "$REDIS_DIAL_TIMEOUT" \
  REDIS_TIMEOUT "$REDIS_TIMEOUT" \
  "" "" \
  USER_GRPC_ADDR user:8004 \
  MEDIA_GRPC_ADDR media:8003 \
  SUPPORT_GRPC_ADDR support:8007 \
  "" "" \
  VKID_CLIENT_ID "${VKID_CLIENT_ID:-}" \
  VKID_CLIENT_SECRET "${VKID_CLIENT_SECRET:-}" \
  VKID_REDIRECT_URI "$VKID_REDIRECT_URI" \
  VKID_SCOPE "${VKID_SCOPE:-email}" \
  VKID_FRONTEND_SUCCESS_PATH "${VKID_FRONTEND_SUCCESS_PATH:-/feed?oauth=vkid}" \
  VKID_FRONTEND_ERROR_PATH "${VKID_FRONTEND_ERROR_PATH:-/login}"

write_env services/media/.env \
  APP_ENDPOINT "$APP_ENDPOINT" \
  MEDIA_GRPC_PORT 8003 \
  MEDIA_HTTP_PORT 8081 \
  "" "" \
  DB_HOST db \
  DB_PORT 5432 \
  DB_USER "$DB_USER" \
  DB_PASSWORD "$DB_PASSWORD" \
  DB_NAME "$DB_NAME" \
  SSL_MODE "$SSL_MODE" \
  POOL_MAX_CONNS "$POOL_MAX_CONNS" \
  POOL_MAX_CONN_LIFETIME "$POOL_MAX_CONN_LIFETIME" \
  POOL_MAX_CONN_IDLE_TIME "$POOL_MAX_CONN_IDLE_TIME" \
  "" "" \
  MINIO_HOST minio \
  MINIO_PORT 9000 \
  MINIO_BUCKET_NAME "$MINIO_BUCKET_NAME" \
  MINIO_ROOT_USER "$MINIO_ROOT_USER" \
  MINIO_ROOT_PASSWORD "$MINIO_ROOT_PASSWORD" \
  MINIO_USE_SSL "$MINIO_USE_SSL" \
  "" "" \
  USER_GRPC_ADDR user:8004 \
  AUTH_GRPC_ADDR auth:8002 \
  MEDIA_GRPC_ADDR media:8003

write_env services/user/.env \
  USER_GRPC_PORT 8004 \
  USER_HTTP_PORT 8082 \
  AUTH_GRPC_ADDR auth:8002 \
  MEDIA_GRPC_ADDR media:8003 \
  "" "" \
  DB_HOST db \
  DB_PORT 5432 \
  DB_USER "$DB_USER" \
  DB_PASSWORD "$DB_PASSWORD" \
  DB_NAME "$DB_NAME" \
  SSL_MODE "$SSL_MODE" \
  POOL_MAX_CONNS "$POOL_MAX_CONNS" \
  POOL_MAX_CONN_LIFETIME "$POOL_MAX_CONN_LIFETIME" \
  POOL_MAX_CONN_IDLE_TIME "$POOL_MAX_CONN_IDLE_TIME" \
  "" "" \
  TARANTOOL_HOST tarantool \
  TARANTOOL_PORT 3301 \
  TARANTOOL_USER "$TARANTOOL_USER" \
  TARANTOOL_PASSWORD "$TARANTOOL_PASSWORD" \
  TARANTOOL_DIAL_TIMEOUT "$TARANTOOL_DIAL_TIMEOUT" \
  TARANTOOL_TIMEOUT "$TARANTOOL_TIMEOUT" \
  TARANTOOL_RECONNECT_TIMEOUT "$TARANTOOL_RECONNECT_TIMEOUT" \
  TARANTOOL_MAX_RECONNECTS "$TARANTOOL_MAX_RECONNECTS"

write_env services/post/.env \
  POST_GRPC_PORT 8005 \
  POST_HTTP_PORT 8083 \
  "" "" \
  DB_HOST db \
  DB_PORT 5432 \
  DB_USER "$DB_USER" \
  DB_PASSWORD "$DB_PASSWORD" \
  DB_NAME "$DB_NAME" \
  SSL_MODE "$SSL_MODE" \
  POOL_MAX_CONNS "$POOL_MAX_CONNS" \
  POOL_MAX_CONN_LIFETIME "$POOL_MAX_CONN_LIFETIME" \
  POOL_MAX_CONN_IDLE_TIME "$POOL_MAX_CONN_IDLE_TIME" \
  "" "" \
  USER_GRPC_ADDR user:8004 \
  MEDIA_GRPC_ADDR media:8003 \
  AUTH_GRPC_ADDR auth:8002 \
  COMMUNITY_GRPC_ADDR community:8009 \
  "" "" \
  TARANTOOL_HOST tarantool \
  TARANTOOL_PORT 3301 \
  TARANTOOL_USER "$TARANTOOL_USER" \
  TARANTOOL_PASSWORD "$TARANTOOL_PASSWORD" \
  TARANTOOL_DIAL_TIMEOUT "$TARANTOOL_DIAL_TIMEOUT" \
  TARANTOOL_TIMEOUT "$TARANTOOL_TIMEOUT" \
  TARANTOOL_RECONNECT_TIMEOUT "$TARANTOOL_RECONNECT_TIMEOUT" \
  TARANTOOL_MAX_RECONNECTS "$TARANTOOL_MAX_RECONNECTS" \
  "" "" \
  CLICKHOUSE_ADDR clickhouse:9000 \
  CLICKHOUSE_DB "$CLICKHOUSE_DB" \
  CLICKHOUSE_USER "$CLICKHOUSE_USER" \
  CLICKHOUSE_PASSWORD "$CLICKHOUSE_PASSWORD" \
  CLICKHOUSE_ASYNC_INSERT "$CLICKHOUSE_ASYNC_INSERT" \
  CLICKHOUSE_WAIT_FOR_ASYNC_INSERT "$CLICKHOUSE_WAIT_FOR_ASYNC_INSERT" \
  CLICKHOUSE_MAX_INSERT_BLOCK_SIZE "$CLICKHOUSE_MAX_INSERT_BLOCK_SIZE"

write_env services/chat/.env \
  CHAT_GRPC_PORT 8006 \
  CHAT_HTTP_PORT 8084 \
  "" "" \
  DB_HOST db \
  DB_PORT 5432 \
  DB_USER "$DB_USER" \
  DB_PASSWORD "$DB_PASSWORD" \
  DB_NAME "$DB_NAME" \
  SSL_MODE "$SSL_MODE" \
  POOL_MAX_CONNS "$POOL_MAX_CONNS" \
  POOL_MAX_CONN_LIFETIME "$POOL_MAX_CONN_LIFETIME" \
  POOL_MAX_CONN_IDLE_TIME "$POOL_MAX_CONN_IDLE_TIME" \
  "" "" \
  USER_GRPC_ADDR user:8004 \
  AUTH_GRPC_ADDR auth:8002 \
  MEDIA_GRPC_ADDR media:8003 \
  "" "" \
  TARANTOOL_HOST tarantool \
  TARANTOOL_PORT 3301 \
  TARANTOOL_USER "$TARANTOOL_USER" \
  TARANTOOL_PASSWORD "$TARANTOOL_PASSWORD" \
  TARANTOOL_DIAL_TIMEOUT "$TARANTOOL_DIAL_TIMEOUT" \
  TARANTOOL_TIMEOUT "$TARANTOOL_TIMEOUT" \
  TARANTOOL_RECONNECT_TIMEOUT "$TARANTOOL_RECONNECT_TIMEOUT" \
  TARANTOOL_MAX_RECONNECTS "$TARANTOOL_MAX_RECONNECTS"

write_env services/support/.env \
  SUPPORT_GRPC_PORT "${SUPPORT_GRPC_PORT:-8007}" \
  SUPPORT_HTTP_PORT "${SUPPORT_HTTP_PORT:-8086}" \
  "" "" \
  DB_HOST db \
  DB_PORT 5432 \
  DB_USER "$DB_USER" \
  DB_PASSWORD "$DB_PASSWORD" \
  DB_NAME "$DB_NAME" \
  SSL_MODE "$SSL_MODE" \
  POOL_MAX_CONNS "$POOL_MAX_CONNS" \
  POOL_MAX_CONN_LIFETIME "$POOL_MAX_CONN_LIFETIME" \
  POOL_MAX_CONN_IDLE_TIME "$POOL_MAX_CONN_IDLE_TIME" \
  "" "" \
  AUTH_GRPC_ADDR auth:8002 \
  USER_GRPC_ADDR user:8004 \
  MEDIA_GRPC_ADDR media:8003

write_env services/community/.env \
  COMMUNITY_GRPC_PORT 8009 \
  COMMUNITY_HTTP_PORT 8087 \
  "" "" \
  DB_HOST db \
  DB_PORT 5432 \
  DB_USER "$DB_USER" \
  DB_PASSWORD "$DB_PASSWORD" \
  DB_NAME "$DB_NAME" \
  SSL_MODE "$SSL_MODE" \
  POOL_MAX_CONNS "$POOL_MAX_CONNS" \
  POOL_MAX_CONN_LIFETIME "$POOL_MAX_CONN_LIFETIME" \
  POOL_MAX_CONN_IDLE_TIME "$POOL_MAX_CONN_IDLE_TIME" \
  "" "" \
  USER_GRPC_ADDR user:8004 \
  MEDIA_GRPC_ADDR media:8003 \
  AUTH_GRPC_ADDR auth:8002

write_env services/search/.env \
  SEARCH_HTTP_PORT 8088 \
  "" "" \
  MEDIA_GRPC_ADDR media:8003 \
  "" "" \
  ELASTICSEARCH_ADDR http://elasticsearch:9200

write_env services/indexer/.env \
  DB_HOST db \
  DB_PORT 5432 \
  DB_USER "$DB_USER" \
  DB_PASSWORD "$DB_PASSWORD" \
  DB_NAME "$DB_NAME" \
  SSL_MODE "$SSL_MODE" \
  POOL_MAX_CONNS 4 \
  POOL_MAX_CONN_LIFETIME 6h \
  POOL_MAX_CONN_IDLE_TIME 3h \
  "" "" \
  ELASTICSEARCH_ADDR http://elasticsearch:9200

write_env services/game/.env \
  GAME_HTTP_PORT 8089 \
  "" "" \
  DB_HOST db \
  DB_PORT 5432 \
  DB_USER "$DB_USER" \
  DB_PASSWORD "$DB_PASSWORD" \
  DB_NAME "$DB_NAME" \
  SSL_MODE "$SSL_MODE" \
  POOL_MAX_CONNS "$POOL_MAX_CONNS" \
  POOL_MAX_CONN_LIFETIME "$POOL_MAX_CONN_LIFETIME" \
  POOL_MAX_CONN_IDLE_TIME "$POOL_MAX_CONN_IDLE_TIME" \
  "" "" \
  USER_GRPC_ADDR user:8004 \
  AUTH_GRPC_ADDR auth:8002
