// Code generated by MockGen. DO NOT EDIT.
// Source: services/user/internal/handler/http/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/go-park-mail-ru/2026_1_ARIS/services/user/internal/model"
	repository "github.com/go-park-mail-ru/2026_1_ARIS/services/user/internal/repository"
	usecase "github.com/go-park-mail-ru/2026_1_ARIS/services/user/internal/usecase"
	gomock "github.com/golang/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// AcceptFriendRequest mocks base method.
func (m *MockUserService) AcceptFriendRequest(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptFriendRequest", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptFriendRequest indicates an expected call of AcceptFriendRequest.
func (mr *MockUserServiceMockRecorder) AcceptFriendRequest(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptFriendRequest", reflect.TypeOf((*MockUserService)(nil).AcceptFriendRequest), arg0, arg1, arg2)
}

// DeclineFriendRequest mocks base method.
func (m *MockUserService) DeclineFriendRequest(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeclineFriendRequest", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeclineFriendRequest indicates an expected call of DeclineFriendRequest.
func (mr *MockUserServiceMockRecorder) DeclineFriendRequest(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeclineFriendRequest", reflect.TypeOf((*MockUserService)(nil).DeclineFriendRequest), arg0, arg1, arg2)
}

// DeleteFriend mocks base method.
func (m *MockUserService) DeleteFriend(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFriend", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFriend indicates an expected call of DeleteFriend.
func (mr *MockUserServiceMockRecorder) DeleteFriend(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFriend", reflect.TypeOf((*MockUserService)(nil).DeleteFriend), arg0, arg1, arg2)
}

// GetFriends mocks base method.
func (m *MockUserService) GetFriends(arg0 context.Context, arg1 int64, arg2 model.FriendshipStatus) ([]model.Friend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriends", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.Friend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriends indicates an expected call of GetFriends.
func (mr *MockUserServiceMockRecorder) GetFriends(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriends", reflect.TypeOf((*MockUserService)(nil).GetFriends), arg0, arg1, arg2)
}

// GetIncomingFriendRequests mocks base method.
func (m *MockUserService) GetIncomingFriendRequests(arg0 context.Context, arg1 int64, arg2 string) ([]model.Friend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomingFriendRequests", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.Friend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomingFriendRequests indicates an expected call of GetIncomingFriendRequests.
func (mr *MockUserServiceMockRecorder) GetIncomingFriendRequests(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomingFriendRequests", reflect.TypeOf((*MockUserService)(nil).GetIncomingFriendRequests), arg0, arg1, arg2)
}

// GetLatestEvents mocks base method.
func (m *MockUserService) GetLatestEvents(arg0 context.Context) ([]usecase.LatestEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestEvents", arg0)
	ret0, _ := ret[0].([]usecase.LatestEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestEvents indicates an expected call of GetLatestEvents.
func (mr *MockUserServiceMockRecorder) GetLatestEvents(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestEvents", reflect.TypeOf((*MockUserService)(nil).GetLatestEvents), arg0)
}

// GetOutgoingFriendRequests mocks base method.
func (m *MockUserService) GetOutgoingFriendRequests(arg0 context.Context, arg1 int64, arg2 string) ([]model.Friend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutgoingFriendRequests", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.Friend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutgoingFriendRequests indicates an expected call of GetOutgoingFriendRequests.
func (mr *MockUserServiceMockRecorder) GetOutgoingFriendRequests(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutgoingFriendRequests", reflect.TypeOf((*MockUserService)(nil).GetOutgoingFriendRequests), arg0, arg1, arg2)
}

// GetProfileByID mocks base method.
func (m *MockUserService) GetProfileByID(arg0 context.Context, arg1 int64) (*usecase.ProfileDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByID", arg0, arg1)
	ret0, _ := ret[0].(*usecase.ProfileDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByID indicates an expected call of GetProfileByID.
func (mr *MockUserServiceMockRecorder) GetProfileByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByID", reflect.TypeOf((*MockUserService)(nil).GetProfileByID), arg0, arg1)
}

// GetProfileMe mocks base method.
func (m *MockUserService) GetProfileMe(arg0 context.Context, arg1 int64) (*usecase.ProfileDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileMe", arg0, arg1)
	ret0, _ := ret[0].(*usecase.ProfileDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileMe indicates an expected call of GetProfileMe.
func (mr *MockUserServiceMockRecorder) GetProfileMe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileMe", reflect.TypeOf((*MockUserService)(nil).GetProfileMe), arg0, arg1)
}

// GetPublicPopularUsers mocks base method.
func (m *MockUserService) GetPublicPopularUsers(arg0 context.Context) ([]usecase.UserCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicPopularUsers", arg0)
	ret0, _ := ret[0].([]usecase.UserCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicPopularUsers indicates an expected call of GetPublicPopularUsers.
func (mr *MockUserServiceMockRecorder) GetPublicPopularUsers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicPopularUsers", reflect.TypeOf((*MockUserService)(nil).GetPublicPopularUsers), arg0)
}

// GetSettings mocks base method.
func (m *MockUserService) GetSettings(arg0 context.Context, arg1 int64) (*model.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettings", arg0, arg1)
	ret0, _ := ret[0].(*model.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettings indicates an expected call of GetSettings.
func (mr *MockUserServiceMockRecorder) GetSettings(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettings", reflect.TypeOf((*MockUserService)(nil).GetSettings), arg0, arg1)
}

// GetSuggestedUsers mocks base method.
func (m *MockUserService) GetSuggestedUsers(arg0 context.Context, arg1 int64) ([]usecase.UserCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuggestedUsers", arg0, arg1)
	ret0, _ := ret[0].([]usecase.UserCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuggestedUsers indicates an expected call of GetSuggestedUsers.
func (mr *MockUserServiceMockRecorder) GetSuggestedUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuggestedUsers", reflect.TypeOf((*MockUserService)(nil).GetSuggestedUsers), arg0, arg1)
}

// GetUsersFriends mocks base method.
func (m *MockUserService) GetUsersFriends(arg0 context.Context, arg1 int64) ([]model.Friend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersFriends", arg0, arg1)
	ret0, _ := ret[0].([]model.Friend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersFriends indicates an expected call of GetUsersFriends.
func (mr *MockUserServiceMockRecorder) GetUsersFriends(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersFriends", reflect.TypeOf((*MockUserService)(nil).GetUsersFriends), arg0, arg1)
}

// RequestFriendship mocks base method.
func (m *MockUserService) RequestFriendship(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestFriendship", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestFriendship indicates an expected call of RequestFriendship.
func (mr *MockUserServiceMockRecorder) RequestFriendship(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestFriendship", reflect.TypeOf((*MockUserService)(nil).RequestFriendship), arg0, arg1, arg2)
}

// RevokeFriendRequest mocks base method.
func (m *MockUserService) RevokeFriendRequest(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeFriendRequest", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeFriendRequest indicates an expected call of RevokeFriendRequest.
func (mr *MockUserServiceMockRecorder) RevokeFriendRequest(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeFriendRequest", reflect.TypeOf((*MockUserService)(nil).RevokeFriendRequest), arg0, arg1, arg2)
}

// UpdateMe mocks base method.
func (m *MockUserService) UpdateMe(arg0 context.Context, arg1 int64, arg2 usecase.UpdateFullProfileInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMe", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMe indicates an expected call of UpdateMe.
func (mr *MockUserServiceMockRecorder) UpdateMe(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMe", reflect.TypeOf((*MockUserService)(nil).UpdateMe), arg0, arg1, arg2)
}

// UpdateSettings mocks base method.
func (m *MockUserService) UpdateSettings(arg0 context.Context, arg1 int64, arg2 repository.SettingsUpdate) (*model.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockUserServiceMockRecorder) UpdateSettings(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockUserService)(nil).UpdateSettings), arg0, arg1, arg2)
}
