basePath: /api
consumes:
- application/json
definitions:
  auth.CommonResponse:
    properties:
      message:
        type: string
    type: object
  auth.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  auth.LoginResponse:
    properties:
      createdAt:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
    type: object
  auth.RegisterRequest:
    properties:
      birthday:
        example: 24/02/2005
        maxLength: 10
        minLength: 8
        type: string
      firstName:
        type: string
      gender:
        enum:
        - 1
        - 2
        type: integer
      lastName:
        type: string
      login:
        type: string
      password1:
        maxLength: 72
        minLength: 6
        type: string
      password2:
        maxLength: 72
        minLength: 6
        type: string
    required:
    - birthday
    - firstName
    - gender
    - lastName
    - login
    - password1
    - password2
    type: object
  auth.RegisterStepOneRequest:
    properties:
      login:
        type: string
      password1:
        maxLength: 72
        minLength: 6
        type: string
      password2:
        maxLength: 72
        minLength: 6
        type: string
    required:
    - login
    - password1
    - password2
    type: object
  auth.ValidationErrorsResponse:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      ok:
        type: boolean
    type: object
  dto.CommonErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.UpdateFullProfileRequestDTO:
    properties:
      bio:
        type: string
      birthdayDate:
        example: "2000-11-26"
        maxLength: 10
        minLength: 8
        type: string
      company:
        type: string
      email:
        type: string
      favMusic:
        type: string
      firstName:
        type: string
      gender:
        allOf:
        - $ref: '#/definitions/models.Gender'
        enum:
        - male
        - female
      group:
        type: string
      institution:
        type: string
      interests:
        type: string
      jobTitle:
        type: string
      lastName:
        type: string
      login:
        type: string
      nativeTown:
        type: string
      phone:
        type: string
      town:
        type: string
    type: object
  feed.FeedResponse:
    properties:
      hasMore:
        type: boolean
      nextCursor:
        type: string
      posts:
        items:
          $ref: '#/definitions/feed.postFeedDTO'
        type: array
    type: object
  feed.authorFeedDTO:
    properties:
      avatarLink:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      username:
        type: string
    type: object
  feed.mediaFeedDTO:
    properties:
      id:
        type: string
      mediaLink:
        type: string
      mimeType:
        type: string
    type: object
  feed.popularPostDTO:
    properties:
      title:
        type: string
    type: object
  feed.popularPostsResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/feed.popularPostDTO'
        type: array
    type: object
  feed.postFeedDTO:
    properties:
      author:
        $ref: '#/definitions/feed.authorFeedDTO'
      comments:
        type: integer
      createdAt:
        type: string
      id:
        type: string
      likes:
        type: integer
      medias:
        items:
          $ref: '#/definitions/feed.mediaFeedDTO'
        type: array
      reposts:
        type: integer
      text:
        type: string
    type: object
  models.Gender:
    enum:
    - male
    - female
    type: string
    x-enum-varnames:
    - Male
    - Female
  models.Profile:
    properties:
      avatarID:
        type: integer
      createdAt:
        type: string
      id:
        type: integer
      isActive:
        type: boolean
      uid:
        type: string
      updatedAt:
        type: string
    type: object
  models.UserAccount:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      isActive:
        type: boolean
      passwordHash:
        type: string
      phone:
        type: string
      uid:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  profile.EducationResponse:
    properties:
      grade:
        description: '? naming'
        type: string
      institution:
        type: string
    type: object
  profile.GetProfileMeResponse:
    properties:
      bio:
        type: string
      birthday:
        description: '? type'
        type: string
      education:
        items:
          $ref: '#/definitions/profile.EducationResponse'
        type: array
      email:
        type: string
      favMusic:
        type: string
      firstName:
        type: string
      gender:
        allOf:
        - $ref: '#/definitions/models.Gender'
        enum:
        - "1"
        - "2"
      imageLink:
        type: string
      interests:
        type: string
      lastName:
        type: string
      nativeTown:
        type: string
      phone:
        type: string
      town:
        type: string
      work:
        items:
          $ref: '#/definitions/profile.WorkResponse'
        type: array
    required:
    - firstName
    - lastName
    type: object
  profile.WorkResponse:
    properties:
      company:
        type: string
      jobTitle:
        type: string
    type: object
  user.suggestedUserDTO:
    properties:
      avatarLink:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      username:
        type: string
    type: object
  user.suggestedUsersResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/user.suggestedUserDTO'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: Description of ARIS backend API
  title: ARIS backend API
  version: 1.0.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: User login
      operationId: login
      parameters:
      - description: post data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.CommonResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/auth.CommonResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/auth.CommonResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/auth.CommonResponse'
      summary: Login user
      tags:
      - auth
  /auth/logout:
    post:
      description: User logout
      operationId: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.CommonResponse'
      security:
      - SessionAuth: []
      summary: Logout user
      tags:
      - auth
  /auth/me:
    get:
      description: Get current user from context
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserAccount'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/auth.CommonResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/auth.CommonResponse'
      security:
      - SessionAuth: []
      summary: Get current user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: User registration
      operationId: registration
      parameters:
      - description: post data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Profile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
      summary: Register user
      tags:
      - auth
  /auth/register/step-one:
    post:
      consumes:
      - application/json
      description: Validate register first step
      operationId: validate-register-step-one
      parameters:
      - description: step one data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterStepOneRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.ValidationErrorsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.CommonResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/auth.CommonResponse'
      summary: Validate register step one
      tags:
      - auth
  /feed:
    get:
      consumes:
      - application/json
      description: Getting feed
      operationId: get-feed
      parameters:
      - description: number of posts
        in: query
        name: limit
        type: integer
      - description: cursor string responded by feed request
        in: query
        name: cursor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/feed.FeedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
      security:
      - SessionAuth: []
      summary: Get feed
      tags:
      - feed
  /image-proxy:
    get:
      consumes:
      - application/json
      description: Get image via proxy
      operationId: image-proxy
      parameters:
      - description: image url
        in: query
        name: image_url
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
      summary: Get image
      tags:
      - proxy
  /posts/popular:
    get:
      description: Getting popular posts
      operationId: get-popular-users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/feed.popularPostsResponse'
      security:
      - SessionAuth: []
      summary: Get popular posts
      tags:
      - feed
  /profile/me:
    get:
      consumes:
      - application/json
      description: Get current user profile data
      operationId: get-profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/profile.GetProfileMeResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
      security:
      - SessionAuth: []
      summary: Get current profile
      tags:
      - profile
  /profile/me/edit:
    patch:
      consumes:
      - application/json
      description: Edit current user profile
      operationId: edit-profile
      parameters:
      - description: patch data
        in: body
        name: updated_fields
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateFullProfileRequestDTO'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
      security:
      - SessionAuth: []
      summary: Edit current profile
      tags:
      - profile
  /public/feed:
    get:
      consumes:
      - application/json
      description: Getting public feed
      operationId: get-public-feed
      parameters:
      - description: number of posts
        in: query
        name: limit
        type: integer
      - description: cursor string responded by feed request
        in: query
        name: cursor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/feed.FeedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
      summary: Get public feed
      tags:
      - feed
  /public/popular-posts:
    get:
      description: Getting public popular posts
      operationId: get-public-popular-users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/feed.popularPostsResponse'
      summary: Get public popular posts
      tags:
      - feed
  /public/popular-users:
    get:
      description: Get public suggested users
      operationId: get-pub-pop-users
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.suggestedUsersResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
      summary: Get public suggested users
      tags:
      - feed
  /users/latest-events:
    get:
      description: Get latest events
      operationId: get-latest-events
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.suggestedUsersResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
      security:
      - SessionAuth: []
      summary: Get latest events
      tags:
      - feed
  /users/suggested:
    get:
      description: Get suggested users
      operationId: get-sug-users
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.suggestedUsersResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonErrorResponse'
      security:
      - SessionAuth: []
      summary: Get suggested users
      tags:
      - feed
produces:
- application/json
schemes:
- http
securityDefinitions:
  SessionAuth:
    in: cookie
    name: session_id
    type: apiKey
swagger: "2.0"
