// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_ARIS/services/media/internal/repository (interfaces: MediaRepo,S3Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	model "github.com/go-park-mail-ru/2026_1_ARIS/services/media/internal/model"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	minio "github.com/minio/minio-go/v7"
)

// MockMediaRepo is a mock of MediaRepo interface.
type MockMediaRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMediaRepoMockRecorder
}

// MockMediaRepoMockRecorder is the mock recorder for MockMediaRepo.
type MockMediaRepoMockRecorder struct {
	mock *MockMediaRepo
}

// NewMockMediaRepo creates a new mock instance.
func NewMockMediaRepo(ctrl *gomock.Controller) *MockMediaRepo {
	mock := &MockMediaRepo{ctrl: ctrl}
	mock.recorder = &MockMediaRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaRepo) EXPECT() *MockMediaRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockMediaRepo) Get(arg0 context.Context, arg1 int64) (*model.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*model.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMediaRepoMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMediaRepo)(nil).Get), arg0, arg1)
}

// GetLink mocks base method.
func (m *MockMediaRepo) GetLink(arg0 context.Context, arg1 int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLink", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLink indicates an expected call of GetLink.
func (mr *MockMediaRepoMockRecorder) GetLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLink", reflect.TypeOf((*MockMediaRepo)(nil).GetLink), arg0, arg1)
}

// Save mocks base method.
func (m *MockMediaRepo) Save(arg0 context.Context, arg1 model.Media) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockMediaRepoMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMediaRepo)(nil).Save), arg0, arg1)
}

// UpdateLink mocks base method.
func (m *MockMediaRepo) UpdateLink(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLink", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLink indicates an expected call of UpdateLink.
func (mr *MockMediaRepoMockRecorder) UpdateLink(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLink", reflect.TypeOf((*MockMediaRepo)(nil).UpdateLink), arg0, arg1, arg2)
}

// MockS3Repo is a mock of S3Repo interface.
type MockS3Repo struct {
	ctrl     *gomock.Controller
	recorder *MockS3RepoMockRecorder
}

// MockS3RepoMockRecorder is the mock recorder for MockS3Repo.
type MockS3RepoMockRecorder struct {
	mock *MockS3Repo
}

// NewMockS3Repo creates a new mock instance.
func NewMockS3Repo(ctrl *gomock.Controller) *MockS3Repo {
	mock := &MockS3Repo{ctrl: ctrl}
	mock.recorder = &MockS3RepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Repo) EXPECT() *MockS3RepoMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockS3Repo) Save(arg0 context.Context, arg1 string, arg2 io.Reader, arg3 uuid.UUID, arg4 int64, arg5 string, arg6 minio.PutObjectOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockS3RepoMockRecorder) Save(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockS3Repo)(nil).Save), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}
