// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/post/post_with_media.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_ARIS/internal/models"
	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
)

// MockPostWithMediaRepo is a mock of PostWithMediaRepo interface.
type MockPostWithMediaRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPostWithMediaRepoMockRecorder
}

// MockPostWithMediaRepoMockRecorder is the mock recorder for MockPostWithMediaRepo.
type MockPostWithMediaRepoMockRecorder struct {
	mock *MockPostWithMediaRepo
}

// NewMockPostWithMediaRepo creates a new mock instance.
func NewMockPostWithMediaRepo(ctrl *gomock.Controller) *MockPostWithMediaRepo {
	mock := &MockPostWithMediaRepo{ctrl: ctrl}
	mock.recorder = &MockPostWithMediaRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostWithMediaRepo) EXPECT() *MockPostWithMediaRepoMockRecorder {
	return m.recorder
}

// DeleteByPostID mocks base method.
func (m *MockPostWithMediaRepo) DeleteByPostID(ctx context.Context, postID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPostID", ctx, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByPostID indicates an expected call of DeleteByPostID.
func (mr *MockPostWithMediaRepoMockRecorder) DeleteByPostID(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPostID", reflect.TypeOf((*MockPostWithMediaRepo)(nil).DeleteByPostID), ctx, postID)
}

// GetMediaByPostID mocks base method.
func (m *MockPostWithMediaRepo) GetMediaByPostID(ctx context.Context, postID int64) []int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaByPostID", ctx, postID)
	ret0, _ := ret[0].([]int64)
	return ret0
}

// GetMediaByPostID indicates an expected call of GetMediaByPostID.
func (mr *MockPostWithMediaRepoMockRecorder) GetMediaByPostID(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaByPostID", reflect.TypeOf((*MockPostWithMediaRepo)(nil).GetMediaByPostID), ctx, postID)
}

// Save mocks base method.
func (m *MockPostWithMediaRepo) Save(ctx context.Context, postWithMedia models.PostWithMedia) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, postWithMedia)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPostWithMediaRepoMockRecorder) Save(ctx, postWithMedia interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPostWithMediaRepo)(nil).Save), ctx, postWithMedia)
}

// MockpostWithMediaDB is a mock of postWithMediaDB interface.
type MockpostWithMediaDB struct {
	ctrl     *gomock.Controller
	recorder *MockpostWithMediaDBMockRecorder
}

// MockpostWithMediaDBMockRecorder is the mock recorder for MockpostWithMediaDB.
type MockpostWithMediaDBMockRecorder struct {
	mock *MockpostWithMediaDB
}

// NewMockpostWithMediaDB creates a new mock instance.
func NewMockpostWithMediaDB(ctrl *gomock.Controller) *MockpostWithMediaDB {
	mock := &MockpostWithMediaDB{ctrl: ctrl}
	mock.recorder = &MockpostWithMediaDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpostWithMediaDB) EXPECT() *MockpostWithMediaDBMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockpostWithMediaDB) Exec(arg0 context.Context, arg1 string, arg2 ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockpostWithMediaDBMockRecorder) Exec(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockpostWithMediaDB)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockpostWithMediaDB) Query(arg0 context.Context, arg1 string, arg2 ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockpostWithMediaDBMockRecorder) Query(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockpostWithMediaDB)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockpostWithMediaDB) QueryRow(arg0 context.Context, arg1 string, arg2 ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockpostWithMediaDBMockRecorder) QueryRow(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockpostWithMediaDB)(nil).QueryRow), varargs...)
}
