// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/user/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileByUserAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAccountId int64                  `protobuf:"varint,1,opt,name=user_account_id,json=userAccountId,proto3" json:"user_account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByUserAccountRequest) Reset() {
	*x = GetProfileByUserAccountRequest{}
	mi := &file_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByUserAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByUserAccountRequest) ProtoMessage() {}

func (x *GetProfileByUserAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByUserAccountRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByUserAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileByUserAccountRequest) GetUserAccountId() int64 {
	if x != nil {
		return x.UserAccountId
	}
	return 0
}

type GetProfileByUserAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int64                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByUserAccountResponse) Reset() {
	*x = GetProfileByUserAccountResponse{}
	mi := &file_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByUserAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByUserAccountResponse) ProtoMessage() {}

func (x *GetProfileByUserAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByUserAccountResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByUserAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileByUserAccountResponse) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type GetUserProfileByUserAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAccountId int64                  `protobuf:"varint,1,opt,name=user_account_id,json=userAccountId,proto3" json:"user_account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileByUserAccountRequest) Reset() {
	*x = GetUserProfileByUserAccountRequest{}
	mi := &file_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileByUserAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileByUserAccountRequest) ProtoMessage() {}

func (x *GetUserProfileByUserAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileByUserAccountRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileByUserAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserProfileByUserAccountRequest) GetUserAccountId() int64 {
	if x != nil {
		return x.UserAccountId
	}
	return 0
}

type GetUserProfileByUserAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProfileId int64                  `protobuf:"varint,1,opt,name=user_profile_id,json=userProfileId,proto3" json:"user_profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileByUserAccountResponse) Reset() {
	*x = GetUserProfileByUserAccountResponse{}
	mi := &file_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileByUserAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileByUserAccountResponse) ProtoMessage() {}

func (x *GetUserProfileByUserAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileByUserAccountResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileByUserAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProfileByUserAccountResponse) GetUserProfileId() int64 {
	if x != nil {
		return x.UserProfileId
	}
	return 0
}

type GetProfileSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int64                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileSummaryRequest) Reset() {
	*x = GetProfileSummaryRequest{}
	mi := &file_proto_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileSummaryRequest) ProtoMessage() {}

func (x *GetProfileSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetProfileSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfileSummaryRequest) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type GetProfileSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int64                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	UserAccountId int64                  `protobuf:"varint,2,opt,name=user_account_id,json=userAccountId,proto3" json:"user_account_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	AvatarId      *int64                 `protobuf:"varint,6,opt,name=avatar_id,json=avatarId,proto3,oneof" json:"avatar_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileSummaryResponse) Reset() {
	*x = GetProfileSummaryResponse{}
	mi := &file_proto_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileSummaryResponse) ProtoMessage() {}

func (x *GetProfileSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetProfileSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetProfileSummaryResponse) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *GetProfileSummaryResponse) GetUserAccountId() int64 {
	if x != nil {
		return x.UserAccountId
	}
	return 0
}

func (x *GetProfileSummaryResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetProfileSummaryResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetProfileSummaryResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetProfileSummaryResponse) GetAvatarId() int64 {
	if x != nil && x.AvatarId != nil {
		return *x.AvatarId
	}
	return 0
}

var File_proto_user_user_proto protoreflect.FileDescriptor

const file_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x15proto/user/user.proto\x12\faris.user.v1\"H\n" +
	"\x1eGetProfileByUserAccountRequest\x12&\n" +
	"\x0fuser_account_id\x18\x01 \x01(\x03R\ruserAccountId\"@\n" +
	"\x1fGetProfileByUserAccountResponse\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x03R\tprofileId\"L\n" +
	"\"GetUserProfileByUserAccountRequest\x12&\n" +
	"\x0fuser_account_id\x18\x01 \x01(\x03R\ruserAccountId\"M\n" +
	"#GetUserProfileByUserAccountResponse\x12&\n" +
	"\x0fuser_profile_id\x18\x01 \x01(\x03R\ruserProfileId\"9\n" +
	"\x18GetProfileSummaryRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x03R\tprofileId\"\xea\x01\n" +
	"\x19GetProfileSummaryResponse\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x03R\tprofileId\x12&\n" +
	"\x0fuser_account_id\x18\x02 \x01(\x03R\ruserAccountId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12 \n" +
	"\tavatar_id\x18\x06 \x01(\x03H\x00R\bavatarId\x88\x01\x01B\f\n" +
	"\n" +
	"_avatar_id2\xf0\x02\n" +
	"\vUserService\x12v\n" +
	"\x17GetProfileByUserAccount\x12,.aris.user.v1.GetProfileByUserAccountRequest\x1a-.aris.user.v1.GetProfileByUserAccountResponse\x12\x82\x01\n" +
	"\x1bGetUserProfileByUserAccount\x120.aris.user.v1.GetUserProfileByUserAccountRequest\x1a1.aris.user.v1.GetUserProfileByUserAccountResponse\x12d\n" +
	"\x11GetProfileSummary\x12&.aris.user.v1.GetProfileSummaryRequest\x1a'.aris.user.v1.GetProfileSummaryResponseB:Z8github.com/go-park-mail-ru/2026_1_ARIS/proto/user;userpbb\x06proto3"

var (
	file_proto_user_user_proto_rawDescOnce sync.Once
	file_proto_user_user_proto_rawDescData []byte
)

func file_proto_user_user_proto_rawDescGZIP() []byte {
	file_proto_user_user_proto_rawDescOnce.Do(func() {
		file_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_user_proto_rawDesc), len(file_proto_user_user_proto_rawDesc)))
	})
	return file_proto_user_user_proto_rawDescData
}

var file_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_user_user_proto_goTypes = []any{
	(*GetProfileByUserAccountRequest)(nil),      // 0: aris.user.v1.GetProfileByUserAccountRequest
	(*GetProfileByUserAccountResponse)(nil),     // 1: aris.user.v1.GetProfileByUserAccountResponse
	(*GetUserProfileByUserAccountRequest)(nil),  // 2: aris.user.v1.GetUserProfileByUserAccountRequest
	(*GetUserProfileByUserAccountResponse)(nil), // 3: aris.user.v1.GetUserProfileByUserAccountResponse
	(*GetProfileSummaryRequest)(nil),            // 4: aris.user.v1.GetProfileSummaryRequest
	(*GetProfileSummaryResponse)(nil),           // 5: aris.user.v1.GetProfileSummaryResponse
}
var file_proto_user_user_proto_depIdxs = []int32{
	0, // 0: aris.user.v1.UserService.GetProfileByUserAccount:input_type -> aris.user.v1.GetProfileByUserAccountRequest
	2, // 1: aris.user.v1.UserService.GetUserProfileByUserAccount:input_type -> aris.user.v1.GetUserProfileByUserAccountRequest
	4, // 2: aris.user.v1.UserService.GetProfileSummary:input_type -> aris.user.v1.GetProfileSummaryRequest
	1, // 3: aris.user.v1.UserService.GetProfileByUserAccount:output_type -> aris.user.v1.GetProfileByUserAccountResponse
	3, // 4: aris.user.v1.UserService.GetUserProfileByUserAccount:output_type -> aris.user.v1.GetUserProfileByUserAccountResponse
	5, // 5: aris.user.v1.UserService.GetProfileSummary:output_type -> aris.user.v1.GetProfileSummaryResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_user_proto_init() }
func file_proto_user_user_proto_init() {
	if File_proto_user_user_proto != nil {
		return
	}
	file_proto_user_user_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_user_proto_rawDesc), len(file_proto_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_user_proto_goTypes,
		DependencyIndexes: file_proto_user_user_proto_depIdxs,
		MessageInfos:      file_proto_user_user_proto_msgTypes,
	}.Build()
	File_proto_user_user_proto = out.File
	file_proto_user_user_proto_goTypes = nil
	file_proto_user_user_proto_depIdxs = nil
}
